### ISSUE TITLE
Puzzle Bobble 2 (Neo Geo OPNB) VGM has no sound

### ISSUE THREAD

**Issue by denjhang** [kuma4649/MDPlayer#100]
There was no sound at all

**Comment by kuma4649** [comment]
検証データが無いので、サンプルが必要です。。。がオリジナルのデータをアップロードしないでくださいね。
ご面倒かと思いますが、同じ現象が発生するデータを作成してください。

**Comment by kuma4649** [comment]
YouTubeで確認するとストリーム形式のようでした。
そこから想像するに、vgmファイルにControl2レジスタを初期化するデータが含まれていないと思われます。
(吸い出し時には既に初期化済みの為、そのデータが送信されない)

よって、VGM再生時に強制的にリセットすることにします。

**Comment by kuma4649** [comment]
STBL117で対応してみました。直ってますでしょうか。

**Comment by denjhang** [comment]
ok

**Comment by kuma4649** [comment]
おぉ！よかった。

ではとじますね
