### ISSUE TITLE
When playing the zip package, the play list repeatedly loads multiple files with the same name

### ISSUE THREAD

**Issue by denjhang** [kuma4649/MDPlayer#101]
![截图未命名210129210734](https://user-images.githubusercontent.com/61811583/106278702-24eb5e80-6276-11eb-87e8-a47fba7aacf7.jpeg)
Every time you play a file, the number of files in the play list doubles

**Comment by kuma4649** [comment]
これは今のところ仕様かな...
zipのなかにプレイリストファイルがあったらそれを優先するといった処理が必要そう。

**Comment by denjhang** [comment]
![截图未命名210202201732](https://user-images.githubusercontent.com/61811583/106599208-b408b700-6593-11eb-9708-631774766889.jpeg)

**Comment by kuma4649** [comment]
STBL128で対応

**Comment by denjhang** [comment]
ok
