### ISSUE TITLE
QSound keyboard display abnormal

### ISSUE THREAD

**Issue by denjhang** [kuma4649/MDPlayer#102]
![截图未命名210129210935](https://user-images.githubusercontent.com/61811583/106278967-9fb47980-6276-11eb-8954-1656085c914c.jpeg)

**Comment by kuma4649** [comment]
これは作成途中...

**Comment by kuma4649** [comment]
実装。(ミュートはまだ)

**Comment by kuma4649** [comment]
ミュートも実装完了。
閉じますね
