### ISSUE TITLE
The pan scintillation frequency of NGP is too high

### ISSUE THREAD

**Issue by denjhang** [kuma4649/MDPlayer#105]
![截图未命名210131123319](https://user-images.githubusercontent.com/61811583/106374754-d9919700-63c0-11eb-9cd4-af4cd7f9a1df.jpeg)

**Comment by denjhang** [comment]
The pan logo is missing？

**Comment by kuma4649** [comment]
scintillation ? logo ?

**Comment by kuma4649** [comment]
あ、「Pan」っていう表記が無いってことか...

**Comment by denjhang** [comment]
> scintillation ? logo ?


On the one hand,I mean pan flashes too much, so it should be optimized.When the note is excited quickly, it's flashing all over. Other chips don't.That's where I marked the red circle. The flashing is too strong.
On the other hand, the "pan" logo is missing...

**Comment by kuma4649** [comment]
成程...しかしNGPのpanは左右それぞれに割り当てられたDCSGの所謂ボリュームなんですよね...
なので、ボリュームを頻繁にオンオフするようなデータであればパンもそのような表示になります。

オーディオ機器によくある、上蓋みたいなものつけたいですか？
(でも蓋を付けられるほど解像度高くないしなぁ...)

**Comment by kuma4649** [comment]
Added "Pan" logo.;P
