### ISSUE TITLE
Double click to open or close  specified channels for piano keyboard

### ISSUE THREAD

**Issue by denjhang** [kuma4649/MDPlayer#106]
Or click to open or close all channels.It's like a lot of songwriting software.

**Comment by kuma4649** [comment]
open ? close ?
ミュートのこと？

**Comment by denjhang** [comment]
Double-click a channel to close other channels. Double click it again to open other channels and close this channel.

**Comment by denjhang** [comment]
![截图未命名210202110034](https://user-images.githubusercontent.com/61811583/106546323-f2778500-6545-11eb-8839-b6931af0b7ae.jpeg)
![截图未命名210202110049](https://user-images.githubusercontent.com/61811583/106546335-f5727580-6545-11eb-8f5e-4bedf63fab23.jpeg)

**Comment by denjhang** [comment]
Just like these two screenshots

**Comment by kuma4649** [comment]
なるほど、反転ですか。。。うーん。「「Ch」をクリックで反転する」のほうが良いのでは

**Comment by kuma4649** [comment]
STBL127 で大体対応。(一部対応していないChipあり)
