### ISSUE TITLE
Does the ADPCM 6ch of ym2610 have pitch? Can it be made into a piano keyboard

### ISSUE THREAD

**Issue by denjhang** [kuma4649/MDPlayer#107]
![截图未命名210201222923](https://user-images.githubusercontent.com/61811583/106471832-02a74a00-64dd-11eb-8870-e6b1532ed2fc.jpeg)

**Comment by kuma4649** [comment]
ごめんなさい、できません(^^;
音声を分析してピッチを算出するつもりはありません。
