### ISSUE TITLE
No sound output from midi keyboard

### ISSUE THREAD

**Issue by denjhang** [kuma4649/MDPlayer#113]
Is my setting wrong?

**Comment by denjhang** [comment]
![截图未命名0204003530](https://user-images.githubusercontent.com/61811583/106779267-ccef9600-6681-11eb-8b87-988df78053fa.jpeg)

**Comment by kuma4649** [comment]
しばらくMIDI系の機能いじってなかったんでわからないのですけど、あとで調べてみます

**Comment by kuma4649** [comment]
https://user-images.githubusercontent.com/7453752/106961021-55546080-6780-11eb-8a1e-0a7b370d2d11.mp4

修正してみました。。。

**Comment by denjhang** [comment]
I tried it according to the video, but when I pressed a key on the midi keyboard, there was no change in the log and there was no sound.

**Comment by denjhang** [comment]
When I changed the midi input setting to polyphony, it's ok now

**Comment by denjhang** [comment]
This is very helpful for building my own OPN2 instrument library, thank you so much.

**Comment by denjhang** [comment]
The current MDPlayer is much better than when I first met. Many of my wishes have been fulfilled functionally, and many bugs have been fixed.I feel very lucky to meet such open source software and developers.
感謝.
どうもありがとうございます
