### ISSUE TITLE
midi input to add basic CC controller events

### ISSUE THREAD

**Issue by denjhang** [kuma4649/MDPlayer#115]
Such as pedal, pitch bend, modulation, etc.

**Comment by denjhang** [comment]
Currently there is no volume and velocity control.

**Comment by kuma4649** [comment]
とりあえず、いまはそこまでしっかりと対応させる予定はありません(^^;
itokenさんの開発されているMAmidiMEmoをお勧めします。
https://github.com/110-kenichi/mame/releases
