### ISSUE TITLE
Make the midi input chip optional

### ISSUE THREAD

**Issue by denjhang** [kuma4649/MDPlayer#116]
Currently it can only be ym2612,I wish to add ym2151, ymf262, etc.

**Comment by kuma4649** [comment]
ここら辺しっかりサポートするつもりはありません。
MIDIキーボードの機能は他のツールと共用するときに
ちょっと確認できると便利だろうというレベルの用途で
用意したものです。
(他のアプリケーションに任せるべきだと思います。
例えば...↓
https://github.com/110-kenichi/mame/releases
）
