### ISSUE TITLE
Can it support ものおき / S98/VGMプレイヤー hardware ?

### ISSUE THREAD

**Issue by denjhang** [kuma4649/MDPlayer#118]
Have you seen this hardware VGM project?

**Comment by denjhang** [comment]
http://sue.niko.to/ps98/index.html

**Comment by kuma4649** [comment]
今のところサポートしているのは
SCCIとGIMICのみです。(^^;
SCCI
 http://www.pyonpyon.jp/~gasshi/fm/scci.html
GIMIC
 https://gimic.net/

**Comment by denjhang** [comment]
I can hardly buy GIMIC at the moment..I hope to support more hardware in the future.

**Comment by kuma4649** [comment]
実機と詳細な仕様書が手に入れば、サポートするんですけどねぇ(^^;
denjhangさんの国では、こういうものあったりするんでしょうか？

**Comment by denjhang** [comment]
I understand that GIMIC does not seem to ship overseas.

**Comment by denjhang** [comment]
The detailed specifications of this hardware are in the above webpage. Although it feels strange, it supports many kinds of chips. I personally think that the chip support exceeds most of the current similar projects.

**Comment by denjhang** [comment]
Currently, the only way I want to buy GIMIC is to buy it in Japan.eleshop.jp seems to be in stock.

**Comment by denjhang** [comment]
(In fact, the real reason is the high price of GIMIC)

**Comment by kuma4649** [comment]
私も高額なのは否定しませんw
でも価格に見合うものだと信じています。
