### ISSUE TITLE
Automatically open two piano windows when playing midi

### ISSUE THREAD

**Issue by denjhang** [kuma4649/MDPlayer#120]
One of the windows has content, the other does not, it should be a BUG

**Comment by kuma4649** [comment]
これは仕様です。
データからはマルチポートかどうか正確に判断できないからです。。。
出ないほうが良いと思いますか？

**Comment by denjhang** [comment]
I suggest only one window pop up by default

**Comment by kuma4649** [comment]
OK

**Comment by kuma4649** [comment]
次の公開で対応しますね

**Comment by kuma4649** [comment]
STBL134 で対応

**Comment by kuma4649** [comment]
こちら、いかがでしょうか？

**Comment by denjhang** [comment]
ok
