### ISSUE TITLE
An error was found while playing midi

### ISSUE THREAD

**Issue by denjhang** [kuma4649/MDPlayer#121]
MIDI channels 1 and 2 stopped playing for a few seconds

**Comment by denjhang** [comment]
(kuma4649:ファイルを削除しました。)
[aibomb midi.zip]

**Comment by kuma4649** [comment]
これは再現しましたので調査できそうです...

**Comment by kuma4649** [comment]
STBL135にて対応

**Comment by kuma4649** [comment]
こちら、いかがでしょうか？

**Comment by denjhang** [comment]
There are still the bug in STBL136

**Comment by denjhang** [comment]
https://user-images.githubusercontent.com/61811583/107837444-ced0fc00-6ddb-11eb-8045-f5a0c300b9cd.mp4

**Comment by denjhang** [comment]
https://user-images.githubusercontent.com/61811583/107837506-148dc480-6ddc-11eb-824a-63e926200e42.mp4

**Comment by kuma4649** [comment]
こちら問題ないんですよねぇ。
何が原因なんだろう。。。

**Comment by kuma4649** [comment]
[binTest.zip](https://github.com/kuma4649/MDPlayer/files/5975093/binTest.zip)
これを試していただいてよろしいでしょうか

**Comment by denjhang** [comment]
binTest.zip is ok

**Comment by kuma4649** [comment]
おぉ、なおりましたか？
ビルドしなおしただけでコードは前のままなんですよねぇ。。。
間違って古いbin.zipを登録したのかなぁ。

**Comment by kuma4649** [comment]
一旦、とじますね
