### ISSUE TITLE
When playing MIDI, drag VGM file to trigger error pop-up

### ISSUE THREAD

**Issue by denjhang** [kuma4649/MDPlayer#122]
![截图未命名210211175124](https://user-images.githubusercontent.com/61811583/107621875-e56b3c00-6c91-11eb-955a-7fa50a819ce8.jpeg)

**Comment by denjhang** [comment]
In fact, now the problem is very serious, now play all VGM will appear this problem

**Comment by denjhang** [comment]
![截图未命名210211175435](https://user-images.githubusercontent.com/61811583/107622072-43981f00-6c92-11eb-9303-c55dc1d25116.jpeg)

**Comment by denjhang** [comment]
In the last version, there was no such problem

**Comment by kuma4649** [comment]
VoiceMeeter以外で試してもダメでしょうか。

**Comment by denjhang** [comment]
After testing, the other three are normal

**Comment by denjhang** [comment]
Only Wasapiout has this bug

**Comment by kuma4649** [comment]
wasapioutのデバイスをvoice meeter以外にする。
↑の設定で、正常に演奏しますか？

こちらでは例によって再現しないので、直せそうにないのです...

**Comment by denjhang** [comment]
I'm really surprised that it's back to normal after switching several times

**Comment by denjhang** [comment]
now is ok

**Comment by kuma4649** [comment]
治った？！

😱

**Comment by denjhang** [comment]
I set the wasapiout device to other options, switched several other options, and found that they were all normal, and then switched back to voice meeter, but everything was ok and the bug disappeared

**Comment by kuma4649** [comment]
治ったので有れば、それは良かった…

設定は終了時に保存されるので、
その前にエラーなので終了してしまうと、
元に戻ります。

**Comment by denjhang** [comment]
Now this problem appears again. It seems that just playing MIDI first and then playing VGM will trigger a bug

**Comment by kuma4649** [comment]
此方では発生しません。

MIDIデバイスもエミュレーションをお使いでしょうか。
その場合、MIDIデバイスがAUDIOデバイスを占有しているからかもしれません。
試しにMIDIデバイスを外部のハードウェアに変更してみてください。

**Comment by kuma4649** [comment]
こちらいかがでしょうか

**Comment by denjhang** [comment]
I feel OK recently

**Comment by kuma4649** [comment]
それではとりあえずクローズしますね
