### ISSUE TITLE
Pitch calculation error of NGP piano keyboard

### ISSUE THREAD

**Issue by denjhang** [kuma4649/MDPlayer#124]
Since the clock frequency of NGP is 307200, but the frequency of sn76489 is 3579545, the tone displayed in NGP is higher than the actual one.

**Comment by denjhang** [comment]
(kuma4649:ファイルは削除しました)
[NGP and DCSG.zip]

**Comment by denjhang** [comment]
I transplanted NGP music to DCSG, and then I found this problem.You can compare the difference between the two files in the compressed package, and pay attention to the piano keyboard

**Comment by kuma4649** [comment]
STBL136にて対応。

**Comment by denjhang** [comment]
ok
