### ISSUE TITLE
When you click stop, the last tone of MIDI can't stop

### ISSUE THREAD

**Issue by denjhang** [kuma4649/MDPlayer#125]

**Comment by kuma4649** [comment]
止まりますよ？

**Comment by denjhang** [comment]
This problem occurs in a few cases

**Comment by kuma4649** [comment]
うーむ、稀にとなるとなかなか直せないですね...(T_T

**Comment by denjhang** [comment]
When MIDI plays a continuous instrument such as square wave, it is easy to trigger the bug when you click stop

**Comment by kuma4649** [comment]
強制的に音を止めることもできますけど、残響音がなくなってしまうんですよね。。。

**Comment by kuma4649** [comment]
リセットを行うようにしてみました。いかがでしょうか

**Comment by denjhang** [comment]
STBL139 ok

**Comment by kuma4649** [comment]
とじますね
