### ISSUE TITLE
There is no sound when playing midi and the piano keyboard does not show any notes

### ISSUE THREAD

**Issue by denjhang** [kuma4649/MDPlayer#126]
Seems to be a new problem

**Comment by denjhang** [comment]
[midi test.zip](https://github.com/kuma4649/MDPlayer/files/6019330/midi.test.zip)

**Comment by denjhang** [comment]
Currently playing VGM is normal

**Comment by kuma4649** [comment]
使い方通りに操作されてもダメでしょうか？

**Comment by denjhang** [comment]
![截图未命名210321233432](https://user-images.githubusercontent.com/61811583/111910855-ffbce480-8a9d-11eb-8f56-6042f46e2222.jpeg)
In this case, there is no sound from midi and no piano keyboard display

**Comment by kuma4649** [comment]
midiは外部音源でしょうか？ソフトウェアによるエミュレーションでしょうか？

**Comment by denjhang** [comment]
Midi uses an emulator sound source. I seem to know the problem.

**Comment by kuma4649** [comment]
エミュレーションであれば、デバイスの取り合いになっている可能性が高いです。
他のデバイスを割り当てるか、外部MIDI音源の使用をお勧めしますw

**Comment by denjhang** [comment]
ok

**Comment by kuma4649** [comment]
ではとじますね
