### ISSUE TITLE
Change output sample rate from 44.1khz?

### ISSUE THREAD

**Issue by Soundshock** [kuma4649/MDPlayer#128]
Output sample rate appears to be locked to 44.1khz. Would it be possible to make an option to change this to a custom value for playback and WAV output?

**Comment by kuma4649** [comment]
今のところ44.1kHz固定です。。。
処理が重いのであまり高い値に出来ないのではないかという気持ちと、
変更可能にすることによって新たな厄介なバグを産むのを恐れています。
(^^;;;

**Comment by kuma4649** [comment]
変更できるようにしてみました。
が色々バグが出ると思いますので、聴くときは音量やその他に十分気を付けてください。

**Comment by Soundshock** [comment]
48khz works great! Thank you! :)
