### ISSUE TITLE
Application doesn't start under Wine (Linux)

### ISSUE THREAD

**Issue by freq-mod** [kuma4649/MDPlayer#129]
Hello. Trying to run this program using Wine compatibility layer for Linux produces following error message about missing file mucomDotNetCompiler.dll
![image](https://user-images.githubusercontent.com/32672779/109274953-5f63ff00-7814-11eb-837e-f997505e10eb.png)

.net 4.0 and .net 4.8 were installed previously.

===
こんにちは。Linux用のWine互換性レイヤーを使用してこのプログラムを実行しようとすると、ファイルが見つからないというエラーメッセージが表示されます。
.net4.0および.net4.8は以前にインストールされていました。

**Comment by kuma4649** [comment]
Wineで動くか試したことないのでわかりません。;P

ファイル自体はエラーメッセージが示すパスに存在するのでしょうか

**Comment by freq-mod** [comment]
Hmmm, for some weird reason, file unpacker I used didn't extract folders inside .zip archive, including `/driver`. I have no idea why did this happen :thinking: 

After manually unpacking the archive properly, application runs. While sounds plays without problems, UI is rather laggy, and CPU load is rather high.

---
奇妙な理由で、私が使用したファイルアンパッカーは、 `/ driver`を含む.zipアーカイブ内のフォルダーを抽出しませんでした。 なぜこれが起こったのか分かりません :thinking: 

アーカイブを手動で適切に解凍した後、アプリケーションが実行されます。 サウンドは問題なく再生されますが、UIはかなり遅く、CPU使用率はかなり高くなります。

**Comment by kuma4649** [comment]
おぉすごい！動くんですね！
デバイスは設定からwasapiやasioを選ぶとだいぶ軽いはずなのですがそこらへんはいかがでしょうか

**Comment by freq-mod** [comment]
I'm unable to select asio option, and under WASAPI, CPU load is still at around 60%... I don't think my PC is that weak (Intel Core i5 2520M @ 2.5 GHz), it might be a problem with Wine.

---
asioオプションを選択できず、WASAPIではCPU負荷はまだ約60％です...私のPCはそれほど弱いとは思いません（Intel Core i5 2520M @ 2.5 GHz), Wineに問題があるかもしれません。

**Comment by denjhang** [comment]
@freq-mod Even the 4th generation i5, the CPU occupancy rate is 30% under win7

**Comment by denjhang** [comment]
Basically, it takes quad-core i7 to run this software smoothly, other dual-core or low voltage is very difficult. The Core 2 processor of more than ten years ago is even worse.
At present, I think the software seems to be an indicator of cpu performance. If a computer cannot play music smoothly with MDPlayer, please upgrade the hardware or buy a new computer.

**Comment by freq-mod** [comment]
>At present, I think the software seems to be an indicator of cpu performance. If a computer cannot play music smoothly with MDPlayer, please upgrade the hardware or buy a new computer.

I cannot afford that at this moment. Also, music itself plays fine, it's the UI that has performance issues.

@kuma4649 それでも、問題はもうありません。 プログラムは実行されますが、いくつかの追加のセットアップと小さな不便があります。ありがとうございました!

**Comment by kuma4649** [comment]
WINEが凄いことがよくわかりました。
ご報告ありがとうございました！
