### ISSUE TITLE
Quickly switch the setting interface

### ISSUE THREAD

**Issue by denjhang** [kuma4649/MDPlayer#130]
The small switch button of the setting interface is not very convenient to use, and all the settings cannot be seen intuitively. It is recommended to change to a multi-level menu or multi-line display.
![sshot-20210311-203722](https://user-images.githubusercontent.com/61811583/110789138-80affb00-82aa-11eb-9ca4-a9c311dec355.png)

**Comment by kuma4649** [comment]
STBL142 にて対応

**Comment by denjhang** [comment]
ok

**Comment by kuma4649** [comment]
とじますね
