### ISSUE TITLE
Main interface icon prompt

### ISSUE THREAD

**Issue by denjhang** [kuma4649/MDPlayer#131]
![截图未命名0313003458](https://user-images.githubusercontent.com/61811583/110970297-91d53680-8394-11eb-9df6-e270b184df38.jpeg)

Just like this.I feel that sometimes, these icons are confusing. Add a reminder label, and it will be automatically displayed when the mouse is moved here.

**Comment by kuma4649** [comment]
昔、実装しようとして苦労したけど出来なかった機能ですねぇ。。。
最初は戸惑うでしょうから、TIPSがでると親切なのはわかるんですけど、
慣れるとウザったくなる機能なので再挑戦する気にもあまりなれなくて。

denjhangさんはこの機能本当に必要でしょうか？

**Comment by kuma4649** [comment]
すみません！
再挑戦してみたところ、実装できそうです！！
もうしばらくお待ちください！

**Comment by kuma4649** [comment]
STBL143にて対応

**Comment by denjhang** [comment]
I recommend the next mode button to indicate which mode it is, such as sequential, random, repeat, etc.

**Comment by denjhang** [comment]
This feature is very friendly for beginners

**Comment by kuma4649** [comment]
>I recommend the next mode button to indicate which mode it is, such as sequential, random, repeat, etc.
??
詳しくお願いできますか？

**Comment by denjhang** [comment]
![截图未命名210321231111](https://user-images.githubusercontent.com/61811583/111910092-f2522b00-8a9a-11eb-974d-d5ddf6699501.jpeg)

**Comment by denjhang** [comment]
![截图未命名210321231322](https://user-images.githubusercontent.com/61811583/111910155-2f1e2200-8a9b-11eb-882e-7f12b50737c5.jpeg)

**Comment by denjhang** [comment]
![截图未命名210321231111](https://user-images.githubusercontent.com/61811583/111910246-8a501480-8a9b-11eb-9137-e4a4c50c81fe.jpeg)

**Comment by kuma4649** [comment]
成程、ボタンを押さずとも次の機能がわかるということですねw
対応させていただきます。

**Comment by kuma4649** [comment]
STBL146にて対応しました。

**Comment by denjhang** [comment]
ok

**Comment by kuma4649** [comment]
とじますね
