### ISSUE TITLE
Random track function

### ISSUE THREAD

**Issue by denjhang** [kuma4649/MDPlayer#132]
![截图未命名0313004330](https://user-images.githubusercontent.com/61811583/110970931-348db500-8395-11eb-9c79-f49939e9e94b.jpeg)
Is this a random selection? I feel it’s still playing sequentially

**Comment by kuma4649** [comment]
動作してますよ？

**Comment by denjhang** [comment]
Shuffle mode seems to only play sequentially

**Comment by denjhang** [comment]
I feel abnormal

**Comment by kuma4649** [comment]
この機能は、
　「次の曲に遷移するとき」に
　「どのように次の曲を決めるか」の
機能になります。
よって、ランダムモードの場合は
曲が鳴り終わった直後に、次の曲を決めるのがランダム
になります。

**Comment by denjhang** [comment]
My idea is that in random mode, clicking the next song will be random, instead of waiting until the playback is complete. Because most music players are this kind of operation logic.

**Comment by kuma4649** [comment]
理解しました。
修正します。
但し、リワインドボタンを押したときは、リストのひとつ上の曲を演奏してしまいますが問題無いですね？

**Comment by denjhang** [comment]
ok

**Comment by denjhang** [comment]
In normal players, clicking on the previous track in the random state will play the track that was played before the random, not the previous track in the playlist. The actual playback sequence should have been recorded.

**Comment by kuma4649** [comment]
知ってます。
その機能を作るのに手間がかかるから、今の状態になっているのです。

**Comment by denjhang** [comment]
I understand

**Comment by kuma4649** [comment]
STBL144 で対応しました

**Comment by denjhang** [comment]
ok

**Comment by kuma4649** [comment]
とじますね
