### ISSUE TITLE
zoom function drop-down menu

### ISSUE THREAD

**Issue by denjhang** [kuma4649/MDPlayer#133]
![截图未命名0313114642](https://user-images.githubusercontent.com/61811583/111018126-2fab1e80-83f2-11eb-94ab-3bf3807ab88e.jpeg)

**Comment by kuma4649** [comment]
要ります？？
ｗ

**Comment by denjhang** [comment]
In the case of high dpi, adjust the zoom to the maximum, the button will exceed the screen and then disappear. So if there is such a menu, it will be more intuitive.

**Comment by kuma4649** [comment]
![image](https://user-images.githubusercontent.com/7453752/111021455-d652d900-8378-11eb-9862-d8bfa155b2a6.png)
すでにありますよ？

**Comment by denjhang** [comment]
![截图未命名0313141344](https://user-images.githubusercontent.com/61811583/111021354-9b978200-8406-11eb-9301-4cd7f475e081.jpeg)
You can long press this button to display this drop-down menu

**Comment by kuma4649** [comment]
私は既にあるので、要らないと思ってます。
それでも更に欲しいと思うのであれば、その理由を教えてください。

**Comment by denjhang** [comment]
![截图未命名0313004302](https://user-images.githubusercontent.com/61811583/111021552-2462ed80-8408-11eb-9bee-a26729389556.jpeg)
My opinion is that you can directly cancel the right-click menu and change all to icons. Then use multi-line icons to arrange.

**Comment by kuma4649** [comment]
？？？

**Comment by denjhang** [comment]
Although the changes are large, it is much more convenient to make all icons.

**Comment by kuma4649** [comment]
Zoomの話はどこに繋がるのでしょうか...?

**Comment by denjhang** [comment]
Regarding zoom, I have a handheld device with a 6-inch screen. When adjusting the zoom, I often accidentally let the picture exceed the screen. So I have this need.

**Comment by kuma4649** [comment]
アイコンとZoomの話はどのようにつながるのでしょう。

**Comment by denjhang** [comment]
Because I just learned that there is a right-click menu, I haven't realized it before. So if the right-click menu can be directly displayed as an icon, then there will be no problems with zoom.

**Comment by denjhang** [comment]
Before today, I never knew there was a right-click menu.

**Comment by kuma4649** [comment]
メニューの項目に対応するアイコンがメニューに並んでほしいということでよろしいでしょうか。

グラフィック描画関連の改修は大変な場合が多く、慎重に考える必要があるのです...

**Comment by denjhang** [comment]
As shown in the picture, I think it is like this

![截图未命名0313161532](https://user-images.githubusercontent.com/61811583/111024150-0bfacf00-8418-11eb-8f06-3d11f434a0c5.jpeg)

**Comment by denjhang** [comment]
![截图未命名0313161532](https://user-images.githubusercontent.com/61811583/111024238-89264400-8418-11eb-8ab6-5009b39c6c29.jpeg)
This is my idea

**Comment by denjhang** [comment]
Consider this function carefully.Related icons need to be drawn.

**Comment by kuma4649** [comment]
？？？？ > This is my idea.

理解できなくて困ってしまいます。
このような画面にするとどのようなメリットがあるのでしょうか。。。

**Comment by denjhang** [comment]
My idea may be more casual, but I think it seems more intuitive to use the icon to cancel the right-click menu.

**Comment by denjhang** [comment]
My thoughts may be more casual, but I think it seems more intuitive to use icons and cancel the right-click menu.

**Comment by denjhang** [comment]
Because there is no prompt at present, I don't even know that there is a right-click menu function.

**Comment by kuma4649** [comment]
うーむ...右クリックするとメニューが開くことを分からせるために、スパナアイコンを並べるということでしょうか？
もしそうであれば、今のところ私は同意できないです。
右クリックによるメニューが開くかどうかを示すようなUIは見たことがないので違和感を感じるからです。

例えばエクスプローラはファイルのリストを右クリックするとメニューがでますが、
それを示すようなものは何も表示されていません。

**Comment by denjhang** [comment]
So my real idea is to draw some new icons, and the function corresponds to the right-click menu, and then remove the right-click menu. Turn all functions into one-click icons to complete.
I think this is much more intuitive. What do you think?

**Comment by kuma4649** [comment]
でも、その新しいアイコンの位置が問題になるのですよね？

**Comment by denjhang** [comment]
Yes, so consider carefully.

**Comment by kuma4649** [comment]
(^^;;;
私は今のままで十分だと思っています...

**Comment by denjhang** [comment]
So keep the status ..

**Comment by kuma4649** [comment]
では一旦とじますね。
