### ISSUE TITLE
Certain PMD .M2 song does not play properly

### ISSUE THREAD

**Issue by freq-mod** [kuma4649/MDPlayer#135]
MISC.zip - これは奇妙な問題を引き起こすYM2608 + PPZ8の曲です。曲はFMPMD2000で正しく再生されますが、MDPlayerではFMセクションのみが問題なく聞こえます。 PCMセクションは非常に歪んでいて、速度が速く、奇妙な、ブーンという音が聞こえます。 約20秒後、次のエラーメッセージが表示されます: 
![bug](https://user-images.githubusercontent.com/32672779/111154071-0d043b80-8593-11eb-8ca4-86d4afe5ed69.PNG)

要求された範囲が配列の終わりを超えています...

KUMA:ファイルへのリンクは削除させていただきました。

**Comment by kuma4649** [comment]
調査します

**Comment by kuma4649** [comment]
STBL145 で修正しました。ご確認お願いします。

**Comment by freq-mod** [comment]
私は、問題が修正されていることを確認することができます。 
ありがとうございました！
