### ISSUE TITLE
OPN series channel mask inversion error

### ISSUE THREAD

**Issue by denjhang** [kuma4649/MDPlayer#136]
Interesting phenomenon
![截图未命名210321230730](https://user-images.githubusercontent.com/61811583/111909995-79eb6a00-8a9a-11eb-8d4d-b2d65190f8d7.jpeg)
![截图未命名210321230738](https://user-images.githubusercontent.com/61811583/111909997-7ce65a80-8a9a-11eb-9fc7-98f1e186b7cc.jpeg)
![截图未命名210321230750](https://user-images.githubusercontent.com/61811583/111910000-7ce65a80-8a9a-11eb-83f6-3be71763c6a3.jpeg)
![截图未命名210321230759](https://user-images.githubusercontent.com/61811583/111910002-7d7ef100-8a9a-11eb-83c9-cb9d166a9b91.jpeg)
![截图未命名210321230807](https://user-images.githubusercontent.com/61811583/111910004-7e178780-8a9a-11eb-8f6f-78b5cab037a3.jpeg)

**Comment by kuma4649** [comment]
？？？
上手く反転しないということでしょうか？

**Comment by denjhang** [comment]
I first close the non-fm third channel, such as the second channel. Then click "ch" to reverse, and then something funny happens.
It can be seen that in the second picture, the fm3 extra channel has not been closed, which means that the fm3 channel has not been closed at all.
Click "ch" again to invert, and it turns out that both the second and third channels of fm are masked.
The problem here is obvious.

**Comment by denjhang** [comment]
Continue to click "ch" to reverse, and a different channel will be masked each time.

**Comment by denjhang** [comment]
During the whole reversal process, there seemed to be some problems with the processing of the fm third channel.

**Comment by kuma4649** [comment]
成程。。。
承知しました。確認後、修正してみます！

**Comment by kuma4649** [comment]
STBL146にて対応しました。

**Comment by denjhang** [comment]
ok

**Comment by kuma4649** [comment]
とじますね
