### ISSUE TITLE
Add a universal pause button

### ISSUE THREAD

**Issue by denjhang** [kuma4649/MDPlayer#137]
Let the sound stop immediately (not the existing pause function, which will not stop the sound immediately.), and the play icon changes to pause, click again to resume playback.
Just like a normal player.
![截图未命名210321231932](https://user-images.githubusercontent.com/61811583/111910346-f763aa00-8a9b-11eb-98b1-f2a5c47a4f39.jpeg)
![截图未命名210321231956](https://user-images.githubusercontent.com/61811583/111910507-a1433680-8a9c-11eb-9635-bb25fc739797.jpeg)

**Comment by kuma4649** [comment]
停止アイコンの隣のポーズアイコンは不要ということですか？

**Comment by denjhang** [comment]
The pause function I described is not the same as the pause function next to the stop button. So it might be reasonable to have two pause buttons.

**Comment by denjhang** [comment]
The pause button next to the stop button does not immediately stop the sound. The pause I described is the kind of pause that understands the stop sound, similar to the existing "stop" button, except that clicking the button again will return to the position before the pause and continue playing.

**Comment by kuma4649** [comment]
同じ形のアイコンが並ぶと混乱を招きます。
ましてや機能が異なるのであればなおさらです。

**Comment by denjhang** [comment]
So I suggest redrawing the pause icon next to the "stop" icon to show the difference.

**Comment by kuma4649** [comment]
??
元々隣にいますよね？
うーむ、いまいち話が進まないですねぇ...

**Comment by denjhang** [comment]
In fact, many people need a universal pause function. Several people around me have responded to this problem.

**Comment by kuma4649** [comment]
すみません、結局のところどうしたいのでしょうか？

**Comment by denjhang** [comment]
(KUMA:動画へのリンクは削除しました)

What I need is the pause function in the winamp player as shown in the video.

**Comment by denjhang** [comment]
For the problem of icon confusion, I suggest to make the new pause button red and distinguish it by color.

**Comment by kuma4649** [comment]
「動作中に有効になっている状態をアイコンで視認できるようにしてほしい」
ということでよろしいでしょうか？

**Comment by kuma4649** [comment]
![image](https://user-images.githubusercontent.com/7453752/113566436-a630ea00-9647-11eb-9565-5f7dc77af718.png)
こんな感じでしょうか

**Comment by denjhang** [comment]
ok

**Comment by denjhang** [comment]
However, I still recommend that there are two pause icons. The pause icon to the right of the stop icon is very useful for extracting tone data.
Maybe you can draw new graphics for these two pause icons.

**Comment by kuma4649** [comment]
なぜでしょうか？
必要だと思う理由が知りたいです。。。

**Comment by denjhang** [comment]
The pause icon to the right of the stop icon is useful for extracting tone data, because it can hold a continuous note.
The universal pause function is convenient for daily use. For example, when I am playing music, I suddenly have something to interrupt listening to the music, and I want to continue playing the music after I'm done.
In the current MDPlayer, if I suddenly have something to pause the music, click the pause button but the sound cannot be stopped. However, although the stop function can stop the music immediately, when I want to play, I cannot return to the place where I stopped before. Fast forward or repeat the previous part.
Of course, I think the universal pause function can also extract timbre data.

**Comment by kuma4649** [comment]
なるほど理由は理解しました。

でもそれでも一時ボタンを二つ用意するのは反対です。
![image](https://user-images.githubusercontent.com/7453752/113575298-9c63b280-9658-11eb-92e5-06ca2120e59f.png)
このオプションで切り替えるようにしてください。

**Comment by denjhang** [comment]
ok

**Comment by kuma4649** [comment]
STBL149にて　6つのボタンだけ対応してみました。いかがでしょうか

**Comment by kuma4649** [comment]
一旦閉じます
問題あればまたopenしてくださいませ。
