### ISSUE TITLE
Invalid DCSG mask

### ISSUE THREAD

**Issue by denjhang** [kuma4649/MDPlayer#140]
Rare problem
a vgz file.zip(KUMA:ファイルへのリンクは削除しました)

**Comment by denjhang** [comment]
![截图未命名210330192826](https://user-images.githubusercontent.com/61811583/112981686-2067f700-918e-11eb-82e7-8c7874248404.jpeg)
After I masked all DCSG channels, the sound did not disappear.

**Comment by kuma4649** [comment]
しばらくmml2vgmのほうに時間がかかりそうなので対応はその後になります。

**Comment by kuma4649** [comment]
現象確認しました。修正します。

**Comment by kuma4649** [comment]
STBL147で修正しました。ご確認ください。

**Comment by denjhang** [comment]
ok

**Comment by kuma4649** [comment]
とじますね
