### ISSUE TITLE
Playing 2xYM2203 VGM output by TFM Music Maker has no sound.

### ISSUE THREAD

**Issue by denjhang** [kuma4649/MDPlayer#141]
TFM music maker  vgm.zip(KUMA:ファイルへのリンクは削除しました)

**Comment by denjhang** [comment]
Actually this track uses YM2612

**Comment by kuma4649** [comment]
しばらくmml2vgmのほうに時間がかかりそうなので対応はその後になります。

**Comment by kuma4649** [comment]
現象確認しました。
vgm のversionが1.01の場合はYM2413のクロックを
YM2612とYM2151のクロックとして使用する必要があるようです。
この件の修正を行うと、MDPlayerでVersion1.01のvgmファイルを再生した時、YM2413、YM2612、YM2151の鍵盤が表示されることになりますのでご了承ください。

**Comment by kuma4649** [comment]
STBL147で修正しました。ご確認ください。

**Comment by denjhang** [comment]
ok

**Comment by kuma4649** [comment]
とじますね
