### ISSUE TITLE
Support PMD format.m86/.m26

### ISSUE THREAD

**Issue by denjhang** [kuma4649/MDPlayer#143]
![截图未命名0403211323](https://user-images.githubusercontent.com/61811583/113479399-735ce980-94c1-11eb-84d0-ec75f60ba077.jpeg)

**Comment by kuma4649** [comment]
ファイル持ってないのでわかりませんが、
拡張子を.mとか.m2に変えてダメなら未サポートということで。

**Comment by denjhang** [comment]
In fact, m26 and m86 files are .m and .m2.
Th4 Lotus Land Story.zip(KUMA:ファイルへのリンクは削除しました)

**Comment by kuma4649** [comment]
であれば、拡張子を変更お願いします...
MDPlayerでのPMDファイル再生処理では
OPN向けが.m
OPNAむけが.m2
という基準で作っています。

**Comment by kuma4649** [comment]
仕様ということで、閉じます
