### ISSUE TITLE
OPNB mask confusion

### ISSUE THREAD

**Issue by denjhang** [kuma4649/MDPlayer#144]
When I clicked adpcmA, the sound of adpcmB disappeared.
When I clicked adpcmB, the sound of adpcmA disappeared.
草

**Comment by denjhang** [comment]
(KUMA:動画へのリンクは削除しました)

**Comment by kuma4649** [comment]
調査しますね。

**Comment by kuma4649** [comment]
再現しないです

**Comment by denjhang** [comment]
STBL146 does have this problem, but STBL147 is completely fine.

**Comment by kuma4649** [comment]
では閉じますね
