### ISSUE TITLE
Right-click the "ch" button to cancel all masks

### ISSUE THREAD

**Issue by denjhang** [kuma4649/MDPlayer#145]
For example, OPL4 has dozens of channels. If I want to cancel all the masks, I have to click one by one.

**Comment by kuma4649** [comment]
右クリックするとmask全解除ですよ。

**Comment by denjhang** [comment]
yes

**Comment by kuma4649** [comment]
ではとじますね

**Comment by denjhang** [comment]
Has this function been implemented?

**Comment by kuma4649** [comment]
はい...

**Comment by denjhang** [comment]
？？？
At present, the functions of the left and right clicks are exactly the same, both of which are inverted masks.

**Comment by denjhang** [comment]
I hope every chip has this function

**Comment by kuma4649** [comment]
もしかすると'ch'を右クリックしている？
