### ISSUE TITLE
When playing a new track again, the mask is displayed incorrectly

### ISSUE THREAD

**Issue by denjhang** [kuma4649/MDPlayer#147]
After masking all channels, stop playing and clear the playlist. When playing a new track again, the mask is displayed incorrectly
Very strange question.
(KUMA:ファイルへのリンクは削除しました)

**Comment by denjhang** [comment]
(KUMA:ファイルへのリンクは削除しました)

**Comment by denjhang** [comment]
In fact, this problem occurs when the window is minimized.
草

**Comment by denjhang** [comment]
(KUMA:ファイルへのリンクは削除しました)

**Comment by kuma4649** [comment]
うーん、表示に問題がありそうですね。

**Comment by kuma4649** [comment]
再現しないです。

**Comment by denjhang** [comment]
This problem occurs when playing OPLL vgm.

**Comment by denjhang** [comment]
STBL147 does have this problem, but only when the keyboard of OPLL is displayed.

**Comment by denjhang** [comment]
This problem does not occur with other chips.

**Comment by kuma4649** [comment]
なるほどOPLLですか。

**Comment by kuma4649** [comment]
STBL148にて対応しました。

**Comment by kuma4649** [comment]
閉じます。
また必要であればopenしてください
