### ISSUE TITLE
Add "Always show on the front " button

### ISSUE THREAD

**Issue by denjhang** [kuma4649/MDPlayer#149]
![截图未命名210405001522](https://user-images.githubusercontent.com/61811583/113515006-68c75080-95a4-11eb-9164-6fdb48be16fa.jpeg)
Let a window always be displayed on the front.

**Comment by kuma4649** [comment]
申し訳ありませんが、その機能を追加するメリットをあまり感じません。
どんな時に有用なのでしょうか。

**Comment by denjhang** [comment]
In fact, I think it's convenient. Many music players have this function, which is displayed at the forefront to facilitate users to switch tracks, such as winamp.

**Comment by denjhang** [comment]
If the realization of this function is not too complicated, I suggest to do it.

**Comment by kuma4649** [comment]
うーん、在れば便利なんでしょうね...
ウィンドウのタイトルバーに独自のアイコンを付けるのがトラブルの原因になりそうで避けたい。

**Comment by kuma4649** [comment]
STBL149にてOPNBのみ対応。
お試しで、OPNBの鍵盤のタイトルバーをダブルクリックすることで常に前面にひょうじするようにしてみました。いかがでしょう？
ボタンは残念ながら、実装は難しかったので見送ることにします。

**Comment by denjhang** [comment]
ok,I suggest adding a hint somewhere to indicate that this feature is available.

**Comment by kuma4649** [comment]
READMEあたりにかいておきます

**Comment by kuma4649** [comment]
STBL150にて対応しました。

**Comment by denjhang** [comment]
The icon has more green fill.
笑

**Comment by denjhang** [comment]
ok
w...

**Comment by kuma4649** [comment]
iconは後で描くんです！

**Comment by denjhang** [comment]
I suggest that the play list also add this function, because the current play list is easy to minimize. With this function, it is more convenient to add tracks.

**Comment by kuma4649** [comment]
プレイリストはリサイズ可能なウィンドウなので、この件の機能を追加できません。
