### ISSUE TITLE
Left-click and right-click "ch" have the same function

### ISSUE THREAD

**Issue by denjhang** [kuma4649/MDPlayer#151]
At present, the functions of the left and right clicks are exactly the same, both of which are inverted masks.

**Comment by kuma4649** [comment]
「右クリックで'ch'をクリックした時」が同じということでしょうか

**Comment by denjhang** [comment]
I mean, click the right mouse button to cancel the mask of all channels.I hope chips with more than three channels have this function.

**Comment by kuma4649** [comment]
それで正しいと思います。

?違う？

**Comment by denjhang** [comment]
I mentioned this requirement in #145.

**Comment by kuma4649** [comment]
？？
どうしたいのでしょうか

**Comment by denjhang** [comment]
![截图未命名0406190707](https://user-images.githubusercontent.com/61811583/113702851-a7781a80-970c-11eb-8198-1f5c82a969e6.jpeg)

**Comment by denjhang** [comment]
I mean unmask all ch.

**Comment by kuma4649** [comment]
？
右クリックするとマスク解除する機能があるのに、
さらに欲しいということですか？

**Comment by denjhang** [comment]
I realized that the current right-click position is not on the "ch" icon, but on the channel.

**Comment by kuma4649** [comment]
？？？？？？？？？？？

**Comment by denjhang** [comment]
It seems more reasonable to right-click on a channel to solo.
Right-click "ch" to remove all masks.

**Comment by denjhang** [comment]
＃156

**Comment by kuma4649** [comment]
'Ch'をクリックした時の動作は、
右も左も同じはずですよ

**Comment by denjhang** [comment]
![截图未命名210321230730](https://user-images.githubusercontent.com/61811583/113706157-f031d280-9710-11eb-9fdd-ecfdd1e07842.jpeg)

**Comment by kuma4649** [comment]
こちら、重複してますのでとじますね。
