### ISSUE TITLE
PSG mask 无效

### ISSUE THREAD

**Issue by denjhang** [kuma4649/MDPlayer#157]
（動画へのリンクは削除しました)

**Comment by kuma4649** [comment]
キーオフ・キーオンしないでボリュームのみ変化するデータではないでしょうか？
その場合はマスク非対応です。

**Comment by denjhang** [comment]
It doesn't seem to be the case as you said.
sid2psg.zip(ファイルへのリンクは削除しました)

**Comment by kuma4649** [comment]
逆にボリュームが全く変化しないのもダメです。

**Comment by kuma4649** [comment]
対応できました！！

**Comment by kuma4649** [comment]
STBL151にて対応しました。

**Comment by denjhang** [comment]
ok

**Comment by kuma4649** [comment]
とじますね。
