### ISSUE TITLE
Keyboard display problem at 1280x720 resolution

### ISSUE THREAD

**Issue by denjhang** [kuma4649/MDPlayer#158]
![截图未命名210411104359](https://user-images.githubusercontent.com/61811583/114290620-84a28900-9ab3-11eb-8c7e-818267cc56a4.jpeg)
![截图未命名210411104938](https://user-images.githubusercontent.com/61811583/114290665-d0553280-9ab3-11eb-9eea-45898de1bb8c.jpeg)
![截图未命名210411105000](https://user-images.githubusercontent.com/61811583/114290666-d21ef600-9ab3-11eb-9152-566890893892.jpeg)
Many people have responded that MDPlayer has display problems at low screen resolutions.

**Comment by kuma4649** [comment]
前にも話したかと思いますが、
画面より大きなウィンドウが作成できないからではないでしょうか。

zoomを1倍にするか、もっと大きな解像度に変更してください。

**Comment by denjhang** [comment]
The zoom is adjusted to x1, which is too small. If zoom is x2, the display is not complete.
The maximum resolution for this device is 1280x720, which cannot be increased.

**Comment by kuma4649** [comment]
申し訳ありませんが、現状ではどうすることもできません。
