### ISSUE TITLE
The playback of OPL4 VGM after using custom PCM sampling and trimming is abnormal

### ISSUE THREAD

**Issue by denjhang** [kuma4649/MDPlayer#161]
There are three VGM files in the compressed package. The ones with trimmed are the ones that have been trimmed, and the ones without the words are the original ones.
These three files can be played normally using in_vgm 0.50 and foo_input_vgm 0.40.9, and the PCM sample playback is normal.
But in MDPlayer, the untrimmed files can only be played normally, and the trimmed files sound PCM samples very unpleasant.
mdrv opl4 demo.zip(KUMA:ファイルは削除しました)

**Comment by kuma4649** [comment]
どんな方法を使ったトリムが適用されているのでしょうか...

**Comment by denjhang** [comment]
I recommend updating the vgm core.
The tool for trimming vgm is vgm_trim

**Comment by kuma4649** [comment]
これ、MDRで聴けばよいのでは？

**Comment by denjhang** [comment]
Of course there is no problem listening directly to the MDR.

**Comment by kuma4649** [comment]
STBL153で対応

**Comment by denjhang** [comment]
ok
