### ISSUE TITLE
C352 VGM cycle error, and abnormal stop icon.

### ISSUE THREAD

**Issue by denjhang** [kuma4649/MDPlayer#165]
![截图未命名210424082047](https://user-images.githubusercontent.com/61811583/115941082-7eaaa000-a4d6-11eb-9a70-924568aff553.png)

https://user-images.githubusercontent.com/61811583/115941086-85391780-a4d6-11eb-9d7e-f2ac2440a452.mp4

**Comment by denjhang** [comment]
The_Tower_of_Druaga_(Namco_Super_Pacman).zip(ファイルは削除しました)

**Comment by kuma4649** [comment]
発生しませんよ？

**Comment by kuma4649** [comment]
一旦閉じますね。
原因がわかったらまたお願いします。
