### ISSUE TITLE
Add an oscilloscope to the PWM channel

### ISSUE THREAD

**Issue by denjhang** [kuma4649/MDPlayer#167]
Just like this.
![F508ADB30F56ADF64CFE9532CC354DC5](https://user-images.githubusercontent.com/61811583/115966942-76984200-a562-11eb-903b-1689f63c232a.png)

**Comment by kuma4649** [comment]
波形は処理が重いのであまり積極的に対応する気になれないのです。
見た目は楽しいのですが、解析したいときは結局wavに出力して音声加工ツールなどを使うでしょうし。

**Comment by denjhang** [comment]
I suggest that you can add a switch first to turn on or off the oscilloscope function.
After turning on this function, convert the tracks to be played into wav in the background in advance, then use the wav analysis tool, and finally delete these temporary wavs automatically.

**Comment by kuma4649** [comment]
そのアイデアは悪くないのですが、wavに変換するのに時間がかかり、演奏開始まで待たされることになります。
現状でもそんなに速くないのに。

**Comment by denjhang** [comment]
I suggest you can refer to the following modizer project.https://github.com/yoyofr/modizer
This is a chiptune player on the iPhone, which can realize the independent oscilloscope display function of each channel of VGM, as shown in the figure above. The modizer can display not only PCM, but also FM and SSG.

**Comment by denjhang** [comment]
I think that a smart phone can easily implement a function, and the modizer will not feel too much resource occupation when it is running, then this function should not be a big problem on the PC, after all, the CPU performance of most PCs is far stronger With iPhone.

**Comment by denjhang** [comment]
![0247F28F161A98C88293A79137DEFA90](https://user-images.githubusercontent.com/61811583/115996707-fed62000-a612-11eb-9d01-d7298e1aab37.png)
Look at this, OPL4's 42 all channels have independent display oscilloscopes, and they run without stress.

**Comment by denjhang** [comment]
If you have a fast waveform analysis tool that does not consume too much resources, not only the display oscilloscope, but also the pitch can also be analyzed, such as the keyboard display function of ADPCM-A.

**Comment by kuma4649** [comment]
私の技術では十分な速度をだすことが難しいのです。
フォークして改造してもらうことを望みます。

**Comment by kuma4649** [comment]
とじますね
