### ISSUE TITLE
YM2610/BやQsoundのmidiファイル出力について

### ISSUE THREAD

**Issue by Tk-takuya** [kuma4649/MDPlayer#170]
素晴らしいプログラム作成ありがとうございます！
表題の件は対応可能でしょうか。
ご検討をお願いします。

**Comment by denjhang** [comment]
To convert YM2610 to midi, I recommend using vgm2mid.
For q-sound, I recommend using vgmtrans, this tool can directly extract midi and SF2/DLS from CPS2 ROM.

**Comment by Tk-takuya** [comment]
ご回答ありがとうございます。
vgm2midについてはありがとうございます。YM2610は変換できました。

vgmtransは自分でコンパイルしたものを所持していて、他のPSF等の変換では使用できているのですが
CPS2ROMからmidi変換については細かいやり方が分からず、断念していました。
なので、こちらのプログラムで出来ないかと思って投稿しました。

**Comment by denjhang** [comment]
Regarding CPS2 ROM, in fact, just drag the ROM package in zip format directly into vgmtrans. Note that the file name of the zip package cannot be changed at will, and must correspond to the file name in mame_roms.xml one to one. The mame_roms.xml file is usually in the same directory as vgmtrans.
For example, 1944.zip, ddsom.zip.
But it should be noted that only part of CPS2 ROM is supported, and all roms that support conversion can be viewed in mame_roms.xml.

**Comment by denjhang** [comment]
Even if MDPlayer implements the midi conversion function of many chips, the effect is very general. I have tried the existing conversion function and found that the accuracy is not very good.
So if you have a dedicated tool, please try to use it.

**Comment by Tk-takuya** [comment]
回答ありがとうございます。
またご相談に乗っていただき、情報提供もありがとうございます。

vgmtransのmame_roms.xmlファイルを確認してみましたが、1944.zipやdstl.zip等のファイル名、ROM内容は合っているようです。
しかしZIPファイルをドラッグしても無反応で何も生成されない状況です。

**Comment by denjhang** [comment]
![截图未命名210429105114](https://user-images.githubusercontent.com/61811583/116497115-30800d00-a8d9-11eb-9a0c-3fe173b70832.png)

**Comment by Tk-takuya** [comment]
![1](https://user-images.githubusercontent.com/81399932/116497955-8e195700-a8e3-11eb-826f-baaf70b8c0c7.png)
何が違うのでしょうか…

**Comment by denjhang** [comment]
I suggest you use the compiled version.I did not compile vgmtrans by myself.

**Comment by Tk-takuya** [comment]
ご返信ありがとうございます。
vgmtransはソースコードを各自がコンパイルするものだと思っていました。
どこかにコンパイルされたアップロードされているのでしょうか。

**Comment by denjhang** [comment]
https://github.com/vgmtrans/vgmtrans/releases/download/interim-20170225/vgmtrans-interim-20170225.7z
I use this link to download the compiled program.

**Comment by denjhang** [comment]
https://dl.smwcentral.net/11655/VGMTrans_by_loveemu.zip

**Comment by Tk-takuya** [comment]
ついにたどり着きました！
https://github.com/vgmtrans/vgmtrans/releases/download/interim-20170225/vgmtrans-interim-20170225.7z
のプログラムでmidi変換されました！！！
ご協力ありがとうございました！
非常に助かりました！
深く感謝、御礼申し上げます。

Y2610は、vgm2midでのmidi変換が、一部のパートしか変換できず、残念でした。
他に手段はな無いですかね。。。
vgmtransのような変換の精度がほしいですね。。。

**Comment by denjhang** [comment]
Currently there is no such tool.
But there are alternative methods. For example, the King of Fighters has released a ported version on the PS platform. I suggest using the music packs of platforms such as PS1, PS2, GBA, NDS and the like to convert.

**Comment by denjhang** [comment]
If YM2610 music is converted to midi to achieve the desired accuracy, you must crack NEOGEO's sound driver, and each game may use a different driver, which is very complicated. Currently ValleyBell has done a lot of music-related cracking programs, usually a cracking program only corresponds to one or a few games.

**Comment by Tk-takuya** [comment]
ご返信、情報提供をありがとうございます。
そうなのですね！
ValleyBellのところもウォッチしておきます。

色々とご相談に乗っていただき誠にありがとうございました。
またお願いします！

**Comment by kuma4649** [comment]
とじますね
