### ISSUE TITLE
[Feature Request] FMP曲の再生に対応

### ISSUE THREAD

**Issue by freq-mod** [kuma4649/MDPlayer#173]
こんにちは. このプログラムはPMDの曲を再生することができるので、FMPへの対応についてお聞きしたいと思います。これらはMML配列です; PMDの.M/.M2/.MZファイルに似ている. 

.OPIファイルは標準的なYM2203の曲です。
.OVIファイルは、標準的なYM2608の曲です。
.OZIファイルは多少異なります。元々、これらのファイルは、PPZ (PSG PCM Driver Z)を使用したYM2203の曲でした. このドライバーでは、SSGチャンネルでPCMサンプル(5-bit, 16 KHz)を再生することができます (FM 3ch + PCM 3ch !!). 。その後、.OZI形式は86ボードとPPZ8をサポートするために再利用されましたが、PPZ8は古いPPZとの下位互換性があるように設計されています。FMPのシーケンス表記も変更なし.つまり、PCMは3チャンネルしか使えないということだ。(FM 6ch, SSG 0ch (w), RSS 6ch, ADPCM 1ch (ちびおと), 86PCM 3ch). 最後に、PDZF拡張ドライバによって、FMPはFM3ch、RSS、ADPCMの各表記で8つのPCMチャンネルをすべて使用できるようになりました。(FM 6ch, 86PCM 8ch)

また、FMPはPVIとPZIのバンクファイルを使用しました。この機能が実装可能であれば、曲例を提供するかもしれません。

**Comment by kuma4649** [comment]
FMP/FMP7の対応は未定です。ごめんなさい。
(本当は対応させていただきたいのです。)
ソースが公開されたら考えるかも...です。

**Comment by freq-mod** [comment]
わかります。[ fmplayer](https://github.com/takamichih/fmplayer)はすでにFMPをサポートしているので、そのサポートを追加することは可能だと思いました。
