### ISSUE TITLE
RYM2612 FM musical instrument format

### ISSUE THREAD

**Issue by ghost** [kuma4649/MDPlayer#174]
If it's not too much trouble... could the RYM2612 FM preset format from [Inphonik's FM Synth](https://www.inphonik.com/products/rym2612-iconic-fm-synthesizer/) be added to the musical instrument extraction feature? 

お願いします！ InphonikのFMシンセからRYM2612FMプリセットフォーマットを楽器抽出機能に追加してください！(I tried my best with Google Translate ☺)

**Comment by kuma4649** [comment]
STBL163で対応しました。。。が、RYM2612を持っていない為動作確認できておりません。
どうか、動作確認をお願いします。。。

**Comment by ghost** [comment]
Thank you so much for the quick update Kuma-san! 
クマさんのクイックアップデートありがとうございます ! 

Althought it is not converting properly :( Here are the problems that i have found so far: 
-Algoritms are wrong when it's not set in 0---MDPlayer says Alg 3; RYM2612 also says 3 but should be 4
-Complete lack of convertion for LFO On, LFO Frq, AMS, PMS. Does not work at all.
-There's a problem with the order. OP3 should be OP2 and viceversa. (Extraction makes this order of FM OPs: 1,3,2,4 instead of 1,2,3,4)
-Wrong FM OP4-->TL value, sometimes it happens with other FM OP-TL
-SL values are always on 0, so does not work properly at all. 
-DT values are just wrong 

Anyway, thanks again for the update but it's not the top priority, take your time!
とにかく、アップデートにもう一度感謝しますが、それは最優先事項ではありません、時間をかけてください！

**Comment by kuma4649** [comment]
STBL164にて対応しました。

サンプルありがとうございます。
DTの値のパターンが少なく、計算式を想像できません。
各オペレータに違う数値をいれて変換したものをレポートお願いできますでしょうか。
また、LFO ONとLFO Frqについては、今のところあてはまるレジスタが無いので困難です。
（LFO ONはAMS/PMSが０以外の時だけON?）

**Comment by ghost** [comment]
最新のアップデートありがとうございます! 
Thank you so much for the latest update! 

There are still minor issues, probably because i didn't give optimal feedback. Sorry. 
おそらく私が最適なフィードバックを提供しなかったために、まだ小さな問題があります。 ごめんなさい。

This time i added .dmf patches for better feedback with the correspondent extracted rym2612 fm presets. 
今回は、対応する抽出されたrym2612 fmプリセットを使用してフィードバックを改善するために、.dmfパッチを追加しました。
[FMins.zip](https://github.com/kuma4649/MDPlayer/files/6455672/FMins.zip)

Both .rym2612 and .dmf presets are accurate. Last time some values were incorrect. 
.rym2612と.dmfの両方のプリセットは正確です。 前回、一部の値が正しくありませんでした。

頑張ってくれてありがとう！

**Comment by kuma4649** [comment]
ごめんなさい、もう少し具体的に違いを教えていただけますでしょうか。
.dmpファイルは不要です。

**Comment by kuma4649** [comment]
STBL165にて対応しました。

**Comment by ghost** [comment]
すごい！

これで、値はほぼ同じになりました。 SSG-EGを除いて、広く使われていないのでそれほど重要ではないと思います。
Now the values are almost the same! except for SSG-EG but i don't think is that important as it's not widely used.

プリセット間で.jpgを簡単に比較しました。
I've done a quick .jpg comparison between the presets: 
[QuickCompRYMjpg.zip](https://github.com/kuma4649/MDPlayer/files/6459882/QuickCompRYMjpg.zip)
念のため...
[FMinsUPDATE.zip](https://github.com/kuma4649/MDPlayer/files/6459885/FMinsUPDATE.zip)

クマさん、どうもありがとうございました！ 結果にとても満足しています。

**Comment by kuma4649** [comment]
STBL166にて対応しました。

**Comment by kuma4649** [comment]
SSGEGの件とファイル名、パッチ名を修正しています。
ほかのパラメータも微調整いれてます。

**Comment by ghost** [comment]
今、すべてが正しいです。
LFO ON / OFFとRATEの2つのボタンだけをチェックする必要があります。 それは私にとって十分です。
私はとても幸せだ！ 熊さん、どうもありがとうございました！ この号を締めくくります。
