### ISSUE TITLE
This Genesis VGM seems to break it?

### ISSUE THREAD

**Issue by Genatari** [kuma4649/MDPlayer#175]
Intro is missing an instrument, may have something to do with the Ch3 Special Mode

https://drive.google.com/file/d/1IDwwsQpmJjbJqGBjS2sfNN1FUTBsBjgb/view?usp=sharing

**Comment by Genatari** [comment]
Same with this VGM, it seems like Ch3 isn't outputting any noise

https://drive.google.com/file/d/1iQ-_ZAzzj8sZb_JZV_hyLBQ4tonFpAY_/view?usp=sharing

**Comment by kuma4649** [comment]
詳しい症状が知りたいです。
先ず、正しいサウンドは何かで聞くことは可能ですか？

**Comment by Genatari** [comment]
Here's how the VGMs are supposed to sound
https://drive.google.com/drive/folders/1F40QQy3L0YtQnjBt71Vi-Sdt-KSQcqqb?usp=sharing

**Comment by kuma4649** [comment]
![image](https://user-images.githubusercontent.com/7453752/121877595-bea73a00-cd45-11eb-9c6e-ee23e448be13.png)

おそらく、NukedOPN2で聴かないと正しく再生できないかと思われます。

YM2612(Primary) Group 
Choice 'Emulation(Nuked-OPN2)'

**Comment by denjhang** [comment]
@Genatari Your vgm music is really amazing, is there more? I am very interested in it.

**Comment by kuma4649** [comment]
こちらはいかがでしょうか

**Comment by Genatari** [comment]
Oh boy, I think I was being dumb and disabled CH3's output and didn't realize it. Sorry for the trouble!
