### ISSUE TITLE
Re:birth利用時の不具合？

### ISSUE THREAD

**Issue by eikouhide** [kuma4649/MDPlayer#177]
RESPFMに、SPW2 for RESPFMとRE1-YM2151、RE1-YM2608、RE1-YM2612、RE1-SN76489の4枚で利用しています。
MDPlayerのオプション－サウンドでRe:birthを使う設定にして、YM2612が使用されているデータを再生するのですが、鳴ってくれません。
RE1-YM2151、RE1-YM2608、RE1-SN76489については、問題なく鳴っています。
他のソフト利用時には、RE1-YM2612を鳴らすことができるので、MDPlayer側でなにかあるのかと思ったので報告です。
（添付のSCCIはRESPFMを認識しなかったので、最新版と差し替えて試しました）

それと、Re:birthの初代マザーボード(RE1-MB100 REV1.2)では、設定時にエラーが出てMDPlayerが固まってしまいます。
対応していただけるとありがたいです。（非対応ということであれば、そのままでも・・・）
よろしくおねがいします。

エラーメッセージを以下に載せておきます。

ーーーーー以下、エラーメッセージーーーーーーーーー
Just-In-Time (JIT) デバッグを呼び出すための詳細については、
ダイアログ ボックスではなく、このメッセージの最後を参照してください。

************** 例外テキスト **************
System.FormatException: 入力文字列の形式が正しくありません。
   場所 System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   場所 System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   場所 MDPlayer.form.frmSetting.SetChipType2FromControls(ChipType2 ct, RadioButton rb_SCCI, ComboBox cmb_SCCI, RadioButton rb_EMU0, RadioButton rb_EMU1, RadioButton rb_EMU2, RadioButton rb_SCCI_E, ComboBox cmb_SCCI_E1, ComboBox cmb_SCCI_E2)
   場所 MDPlayer.form.frmSetting.btnOK_Click(Object sender, EventArgs e)
   場所 System.Windows.Forms.Control.OnClick(EventArgs e)
   場所 System.Windows.Forms.Button.OnClick(EventArgs e)
   場所 System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   場所 System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   場所 System.Windows.Forms.Control.WndProc(Message& m)
   場所 System.Windows.Forms.ButtonBase.WndProc(Message& m)
   場所 System.Windows.Forms.Button.WndProc(Message& m)
   場所 System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   場所 System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   場所 System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** 読み込まれたアセンブリ **************
mscorlib
    アセンブリ バージョン:4.0.0.0
    Win32 バージョン:4.8.4360.0 built by: NET48REL1LAST_C
    コードベース:file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
MDPlayer
    アセンブリ バージョン:1.0.0.0
    Win32 バージョン:1.0.0.0
    コードベース:file:///D:/MDPlayer/MDPlayer.exe
----------------------------------------
System.Windows.Forms
    アセンブリ バージョン:4.0.0.0
    Win32 バージョン:4.8.4341.0 built by: NET48REL1LAST_C
    コードベース:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    アセンブリ バージョン:4.0.0.0
    Win32 バージョン:4.8.4360.0 built by: NET48REL1LAST_C
    コードベース:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    アセンブリ バージョン:4.0.0.0
    Win32 バージョン:4.8.4084.0 built by: NET48REL1
    コードベース:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
MDSound
    アセンブリ バージョン:1.0.3.0
    Win32 バージョン:1.0.3.0
    コードベース:file:///D:/MDPlayer/MDSound.DLL
----------------------------------------
netstandard
    アセンブリ バージョン:2.0.0.0
    Win32 バージョン:4.8.4084.0
    コードベース:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/netstandard/v4.0_2.0.0.0__cc7b13ffcd2ddd51/netstandard.dll
----------------------------------------
System.Core
    アセンブリ バージョン:4.0.0.0
    Win32 バージョン:4.8.4360.0 built by: NET48REL1LAST_C
    コードベース:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
NAudio.Midi
    アセンブリ バージョン:2.0.0.0
    Win32 バージョン:2.0.0.0
    コードベース:file:///D:/MDPlayer/NAudio.Midi.DLL
----------------------------------------
NAudio
    アセンブリ バージョン:2.0.0.0
    Win32 バージョン:2.0.0.0
    コードベース:file:///D:/MDPlayer/NAudio.DLL
----------------------------------------
NAudio.Core
    アセンブリ バージョン:2.0.0.0
    Win32 バージョン:2.0.0.0
    コードベース:file:///D:/MDPlayer/NAudio.Core.DLL
----------------------------------------
System.Xml
    アセンブリ バージョン:4.0.0.0
    Win32 バージョン:4.8.4084.0 built by: NET48REL1
    コードベース:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
MDPlayer.resources
    アセンブリ バージョン:1.0.0.0
    Win32 バージョン:1.0.0.0
    コードベース:file:///D:/MDPlayer/ja/MDPlayer.resources.DLL
----------------------------------------
System.Configuration
    アセンブリ バージョン:4.0.0.0
    Win32 バージョン:4.8.4190.0 built by: NET48REL1LAST_B
    コードベース:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
Microsoft.GeneratedCode
    アセンブリ バージョン:1.0.0.0
    Win32 バージョン:4.8.4084.0 built by: NET48REL1
    コードベース:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    アセンブリ バージョン:1.0.0.0
    Win32 バージョン:4.8.4084.0 built by: NET48REL1
    コードベース:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
musicDriverInterface
    アセンブリ バージョン:1.0.0.0
    Win32 バージョン:1.0.0.0
    コードベース:file:///D:/MDPlayer/musicDriverInterface.DLL
----------------------------------------
NAudio.WinMM
    アセンブリ バージョン:2.0.0.0
    Win32 バージョン:2.0.0.0
    コードベース:file:///D:/MDPlayer/NAudio.WinMM.DLL
----------------------------------------
NAudio.Wasapi
    アセンブリ バージョン:2.0.0.0
    Win32 バージョン:2.0.0.0
    コードベース:file:///D:/MDPlayer/NAudio.Wasapi.DLL
----------------------------------------
NAudio.Asio
    アセンブリ バージョン:2.0.0.0
    Win32 バージョン:2.0.0.0
    コードベース:file:///D:/MDPlayer/NAudio.Asio.DLL
----------------------------------------
RealChipCtlWrap
    アセンブリ バージョン:0.0.0.0
    Win32 バージョン:
    コードベース:file:///D:/MDPlayer/RealChipCtlWrap.DLL
----------------------------------------
Jacobi.Vst.Interop
    アセンブリ バージョン:1.1.0.0
    Win32 バージョン:
    コードベース:file:///D:/MDPlayer/Jacobi.Vst.Interop.DLL
----------------------------------------
Jacobi.Vst.Core
    アセンブリ バージョン:1.1.0.0
    Win32 バージョン:1.1.0.0
    コードベース:file:///D:/MDPlayer/Jacobi.Vst.Core.DLL
----------------------------------------
mucomDotNETCompiler
    アセンブリ バージョン:1.0.0.0
    Win32 バージョン:1.0.0.0
    コードベース:file:///D:/MDPlayer/plugin/driver/mucomDotNETCompiler.dll
----------------------------------------
mucomDotNETDriver
    アセンブリ バージョン:1.0.0.0
    Win32 バージョン:1.0.0.0
    コードベース:file:///D:/MDPlayer/plugin/driver/mucomDotNETDriver.dll
----------------------------------------
PMDDotNETCompiler
    アセンブリ バージョン:1.0.0.0
    Win32 バージョン:1.0.0.0
    コードベース:file:///D:/MDPlayer/plugin/driver/PMDDotNETCompiler.dll
----------------------------------------
PMDDotNETDriver
    アセンブリ バージョン:1.0.0.0
    Win32 バージョン:1.0.0.0
    コードベース:file:///D:/MDPlayer/plugin/driver/PMDDotNETDriver.dll
----------------------------------------
NAudio.WinForms
    アセンブリ バージョン:2.0.0.0
    Win32 バージョン:2.0.0.0
    コードベース:file:///D:/MDPlayer/NAudio.WinForms.DLL
----------------------------------------
Microsoft.Win32.Registry
    アセンブリ バージョン:5.0.0.0
    Win32 バージョン:5.0.20.51904
    コードベース:file:///D:/MDPlayer/Microsoft.Win32.Registry.DLL
----------------------------------------
System.Windows.Forms.resources
    アセンブリ バージョン:4.0.0.0
    Win32 バージョン:4.8.4084.0 built by: NET48REL1
    コードベース:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_ja_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------
Microsoft.GeneratedCode
    アセンブリ バージョン:1.0.0.0
    Win32 バージョン:4.8.4084.0 built by: NET48REL1
    コードベース:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
mscorlib.resources
    アセンブリ バージョン:4.0.0.0
    Win32 バージョン:4.8.4084.0 built by: NET48REL1
    コードベース:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_ja_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------
Accessibility
    アセンブリ バージョン:4.0.0.0
    Win32 バージョン:4.8.4084.0 built by: NET48REL1
    コードベース:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
System.IO.Compression.FileSystem
    アセンブリ バージョン:4.0.0.0
    Win32 バージョン:4.8.4084.0
    コードベース:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.IO.Compression.FileSystem/v4.0_4.0.0.0__b77a5c561934e089/System.IO.Compression.FileSystem.dll
----------------------------------------
System.IO.Compression
    アセンブリ バージョン:4.0.0.0
    Win32 バージョン:4.8.4084.0 built by: NET48REL1
    コードベース:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.IO.Compression/v4.0_4.0.0.0__b77a5c561934e089/System.IO.Compression.dll
----------------------------------------

************** JIT デバッグ **************
Just-In-Time (JIT) デバッグを有効にするには、このアプリケーション、
またはコンピューター (machine.config) の構成ファイルの jitDebugging 
値を system.windows.forms セクションで設定しなければなりません。
アプリケーションはまた、デバッグを有効にしてコンパイルされなければ
なりません。

例:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

JIT デバッグが有効なときは、このダイアログ ボックスで処理するよりも、
ハンドルされていない例外はすべてコンピューターに登録された
JIT デバッガーに設定されなければなりません。

**Comment by kuma4649** [comment]
所持していないので確認ができないです。。。
どうしようかな...

**Comment by kuma4649** [comment]
![image](https://user-images.githubusercontent.com/7453752/124190725-b3059280-dafd-11eb-9471-ad1b39a62f0d.png)
画面の様にコンボボックスにインターフェイス名が出るかと思うのですが
そこに表示される文字列を教えていただけますでしょうか。

**Comment by eikouhide** [comment]
kuma4649 様へ
コンボボックスの画像添付します。
よろしくおねがいします。

○RE1-MB100
[image: Sound01.png]
[image: Sound02.png]

○Real選んでOK押した時
[image: Sound03.png]


○RESPFM
[image: Sound04.png]
[image: Sound05.png]

○VGM（メガドライブのデータ）演奏時の様子
SCCI DispのSN76489は反応してるが、2612の反応が無いです。
[image: Sound06.png]


2021年7月2日(金) 6:22 kuma ***@***.***>:

**Comment by kuma4649** [comment]
すみません、画像が見れないです。。。

**Comment by eikouhide** [comment]
すいませんでした～
kuma4649 様へ
コンボボックスの画像添付します。
よろしくおねがいします。

○RE1-MB100

![Sound01](https://user-images.githubusercontent.com/86804023/124317951-e9511980-dbb2-11eb-8c7b-e69c38f39582.png)
![Sound02](https://user-images.githubusercontent.com/86804023/124317999-fa9a2600-dbb2-11eb-9d48-c3e9fd323ae4.png)

○Real選んでOK押した時
![Sound03](https://user-images.githubusercontent.com/86804023/124318030-038af780-dbb3-11eb-80d4-a8322175594a.png)


○RESPFM
![Sound04](https://user-images.githubusercontent.com/86804023/124318156-2f0de200-dbb3-11eb-852f-f07d5b2fcf3f.png)
![Sound05](https://user-images.githubusercontent.com/86804023/124318171-3339ff80-dbb3-11eb-9ff4-ca6fa0564161.png)

○VGM（メガドライブのデータ）演奏時の様子
SCCI DispのSN76489は反応してるが、2612の反応が無いです。
![Sound06](https://user-images.githubusercontent.com/86804023/124318186-39c87700-dbb3-11eb-9be7-06d00473e54f.png)

**Comment by kuma4649** [comment]
ありがとうございます！
画像のお陰で、大体予想はつきました！

**Comment by kuma4649** [comment]
STBL178 2021/07/03
をリリースしました。もしかしたら初代のほうは動くかもしれないです。
但し、OPN２はダメかと思いますが。。。

**Comment by eikouhide** [comment]
初代(RE1-MB100)での動作確認、できました。
ありがとうございます。
OPN2は・・・やっぱり駄目でした。
RE1-MB100とRESPFMで、別々のRE1-YM2612をつなげてるので、個体差ではないと思います

**Comment by kuma4649** [comment]
一応、RESPFMを昨日注文しましたので、それが届いたら調査を続けようと思います

**Comment by kuma4649** [comment]
音出るようになりました。お確かめください。

**Comment by eikouhide** [comment]
ありがとうございます。
音が出ること、確認しました。

**Comment by kuma4649** [comment]
では閉めますね。。。
