### ISSUE TITLE
Could no load the file or assembly

### ISSUE THREAD

**Issue by firealboy** [kuma4649/MDPlayer#178]
![Problem](https://user-images.githubusercontent.com/86969208/124483990-51edf100-dd81-11eb-89e7-06776a5c2cd7.jpg)
Hi!
i cannot run the program.
It apears a window that says "Exception message: could not load the file or assembly 'RealChipCtlWrap.dll' or one of its dependencies. Could not find the specific module."

My regards.

**Comment by kuma4649** [comment]
先ずは　'RealChipCtlWrap.dll' が存在していますでしょうか。
その後に'removeZoneIdent.bat'を一度実行してみてください。

それでもダメなら...どうしよう(T_T

**Comment by kuma4649** [comment]
こちらはいかがでしょうか

**Comment by kuma4649** [comment]
とじますね
