### ISSUE TITLE
Jacobi.Vst.Interop.dll error (プログラムが実行できない)

### ISSUE THREAD

**Issue by freq-mod** [kuma4649/MDPlayer#180]
![Przechwytywanie](https://user-images.githubusercontent.com/32672779/128528304-d2dfc19b-54bb-490c-9e2e-0ec291cfe05a.PNG)

このアプリケーションは、存在するファイルを見つけることができません。Windows 10, .NET 4.8がインストールされている.

P.S: LinuxシステムでWineを使用した場合、アプリケーションは動作しますが、非常に不安定で、VGM再生中にキーボードのプレビューが表示されませんでした。

**Comment by kuma4649** [comment]
バッチファイル(removeZonIdent.bat)は実行しましたか？

**Comment by freq-mod** [comment]
そのバッチファイルを実行しましたが、効果はありませんでした。

また、binwithoutVST.zipファイルをダウンロードしました。何かエラーメッセージが表示された後に起動しますが、動作は不安定です。
![md](https://user-images.githubusercontent.com/32672779/128594971-d766aa77-40d5-4609-a9b2-53bc347bfb95.PNG)
Linux+Wineの下でのように。

**Comment by kuma4649** [comment]
Linux環境での操作は想定しておりません...
ごめんなさい。

**Comment by freq-mod** [comment]
それでも、問題はWindows 10にもあります... これは本当に奇妙です

**Comment by erio2018** [comment]
横から失礼します。
ご無沙汰しております＞kumaさん

自分も新調したPCではbin.zip(2021/08/07 v2)のバイナリで同じエラーが出たので、binWithoutVST.zipのバイナリを使わせてもらっていて、こちらは問題なくWin10で実行できています。
古いPC(Win8.1から育てた奴)では真面目にパッケージ入れまくってたのでbin.zipのバイナリでも問題なく動いているので、
おそらくC++の再配布パッケージ辺りの必要物が足りてないのではないでしょうか。
ライブラリ等揃っているか確認をお勧めします。＞freq-modさん

　
全然別件なのですが、FireHD10でDebian noroot上のmonoではmml2vgmはコマンドライン版共々動きました。(IDEは無理)
相変わらず変な使い方ですみません。

![fire10hd2021_20210728](https://user-images.githubusercontent.com/35863829/128743194-efd81883-6cb5-4ba1-8e7f-2d952cd53c6e.png)

MDPlayerは変な怒られ方しました。こっちは流石にネタですねｗ

![firehd10_mdplayer_20210728](https://user-images.githubusercontent.com/35863829/128744358-0d6c11c4-7a7b-4999-9329-00637722da25.png)

以上、同エラー発生時の自分の解決策とネタ報告でした。

**Comment by kuma4649** [comment]
どうも～。
情報ありがとうございます。

Linux対応したいけど流石に負担が大きすぎるので私には今のところ無理...
(.NET 5でビルドできればまた違うかも知れないのですが...)

まだまだ当分、Linuxは「わかる人はがんばってね」状態です。
mvc,mml2vgmが動くのも多分たまたまだろうなぁ...(^^;;;

**Comment by freq-mod** [comment]
@erio2018 Microsoft C++ redistributable 2010, 2012, 2013, 2015 packagesをインストールしましたが、効果はありませんでした。プログラムは相変わらずエラーになります。
@kuma4649 `System.Security.Principal.IdentityNotMappedException: Nie można przetłumaczyć niektórych lub żadnych odwołań do tożsamości. (アイデンティティへの言及の一部または全部は翻訳できません)
   w System.Security.Principal.NTAccount.Translate(IdentityReferenceCollection sourceAccounts, Type targetType, Boolean forceSuccess)
   w System.Security.Principal.NTAccount.Translate(Type targetType)
   w System.Security.AccessControl.CommonObjectSecurity.ModifyAccess(AccessControlModification modification, AccessRule rule, Boolean& modified)
   w System.Security.AccessControl.CommonObjectSecurity.AddAccessRule(AccessRule rule)
   w System.Security.AccessControl.ObjectSecurity`1.AddAccessRule(AccessRule`1 rule)
   w MDPlayer.mmfControl.Open(String mmfName, Int32 mmfSize)
   w MDPlayer.mmfControl..ctor(Boolean isClient, String mmfName, Int32 mmfSize)
   w MDPlayer.form.frmMain.frmMain_Load(Object sender, EventArgs e)
   w System.Windows.Forms.Form.OnLoad(EventArgs e)
   w System.Windows.Forms.Form.OnCreateControl()
   w System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   w System.Windows.Forms.Control.CreateControl()
   w System.Windows.Forms.Control.WmShowWindow(Message& m)
   w System.Windows.Forms.Control.WndProc(Message& m)
   w System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   w System.Windows.Forms.ContainerControl.WndProc(Message& m)
   w System.Windows.Forms.Form.WmShowWindow(Message& m)
   w System.Windows.Forms.Form.WndProc(Message& m)
   w MDPlayer.form.frmMain.WndProc(Message& m)
   w System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   w System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   w System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)`

**Comment by kuma4649** [comment]
権限関連のエラーメッセージがでていますね.
試しにroot権限で実行してみてはいかがでしょうか。

また、logファイルが出力されているかもしれませんので以下のフォルダに
log.txtが出力されていたらその内容を教えてください。

C:\Users\(ユーザー名)\AppData\Roaming\KumaApp\MDPlayer

**Comment by freq-mod** [comment]
管理者としてプログラムを実行しても、同じエラーメッセージが表示されます。
[log.txt](https://github.com/kuma4649/MDPlayer/files/6967127/log.txt)

**Comment by kuma4649** [comment]
いつのプログラムから現象が発生する様になりましたか？

**Comment by freq-mod** [comment]
私が正しく理解しているかどうかはわかりませんが (DeepL w), が、STBL185をダウンロードした際にこれらの問題に気づきました。STBL183も正常に動作していませんでしたが、どのバージョンでこれらの問題が発生したのかはわかりません。

最新のものを試してみようかな...  壊れたまま

**Comment by kuma4649** [comment]
今までのbin.zipを試して、どの時点のSTBLから不具合がでるようになったか確認してください。
こちらでは現象がでないので、色々試してもらうしかない状況です。
申し訳ありません...

**Comment by kuma4649** [comment]
こちらその後いかがでしょうか？

**Comment by freq-mod** [comment]
まだ正しく動作しません.

**Comment by kuma4649** [comment]
そうですか。。。
binWithoutVSTのほうもダメでしょうか？

**Comment by freq-mod** [comment]
binWithoutVSTも同様に動作しません。

**Comment by kuma4649** [comment]
そうですか。。。
万策尽きた感じですね(T_T

**Comment by Weeppiko** [comment]
I'm having the same issue here. It start to happen from the STBL176

**Comment by kuma4649** [comment]
当然、STBL175は大丈夫だったということですね？

binWithoutVST.zipは試されましたか？
removeZoneIdent.batは実行しましたか?
OSは?(Linuxは対象外とさせていただきます...)

**Comment by kuma4649** [comment]
STBL175と比較していて気付いたのですが、共有メモリの権限付与に問題があるのかもしれないです。
(everyoneの権限を付与できずに例外が出るっぽい)
@freq-mod さんの例外メッセージにもそれっぽいメソッドをコールすることによって引き起こされていることが確認できます。

とりあえず、この共有メモリの操作をがっちりtryCatchで括ってみようと思います。
これで現象に変化が見られればまた次の対策が打てるかもしれないです。

**Comment by kuma4649** [comment]
対応入れてみましたのでお試しください。

＞STBL210 2021/11/23
  共有メモリ:権限付与でエラーが出る環境向け対策として、trycatchで処理をがっつり括り例外潰し。

**Comment by Weeppiko** [comment]
Everything seems to work now with STBL210, thanks!

**Comment by kuma4649** [comment]
うーむ、これが原因だったのかな...
とりあえず動いて良かったです>Weeppiko さん
ただ、恐らく共有メモリが使用できていない状態だと思われます。。。

**Comment by freq-mod** [comment]
問題が修正されたことを確認できました。ありがとうございました!
