### ISSUE TITLE
Inexplicable system tone

### ISSUE THREAD

**Issue by denjhang** [kuma4649/MDPlayer#181]
Every time a track in the playlist is switched, the system prompt sound will be activated automatically. I feel this is a BUG.

**Comment by denjhang** [comment]
https://user-images.githubusercontent.com/61811583/128886643-a19afc9d-3075-4d30-86c9-33de1f058e5b.mp4

**Comment by kuma4649** [comment]
こちらではでませんね…
log.txtに何かメッセージが記録されていませんか？
場所は
C:\Users\(ユーザー名)\AppData\Roaming\KumaApp\MDPlayer
です

**Comment by denjhang** [comment]
2021/08/10 22:36:32    起動処理開始
2021/08/10 22:36:32    frmMain(コンストラクタ):STEP 00
2021/08/10 22:36:32    frmMain(コンストラクタ):STEP 01
2021/08/10 22:36:32    frmMain(コンストラクタ):STEP 02
2021/08/10 22:36:32    frmMain(コンストラクタ):STEP 03
2021/08/10 22:36:32    起動時のAudio初期化処理開始
2021/08/10 22:36:32    Audio:Init:Begin
2021/08/10 22:36:32    Audio:Init:STEP 01
2021/08/10 22:36:32    Audio:Init:STEP 02
2021/08/10 22:36:32    Audio:Init:STEP 03
2021/08/10 22:36:32    Audio:Init:STEP 04
2021/08/10 22:36:32    RealChip:Ctr:STEP 00(Start)
2021/08/10 22:36:32    RealChip:Ctr:Found SCCI.(Interface count=1)
2021/08/10 22:36:32    RealChip:Ctr:STEP 01
2021/08/10 22:36:32    RealChip:Ctr:Not found G.I.M.I.C.
2021/08/10 22:36:32    RealChip:Ctr:STEP 02(Success)
2021/08/10 22:36:32    Audio:Init:STEP 05
2021/08/10 22:36:32    Audio:Init:STEP 06
2021/08/10 22:36:32    Audio:Init:VST:STEP 01
2021/08/10 22:36:32    Audio:Init:VST:STEP 02
2021/08/10 22:36:32    Audio:Init:STEP 07
2021/08/10 22:36:32    Audio:Init:STEP 08
2021/08/10 22:36:32    Audio:Init:STEP 09
2021/08/10 22:36:32    Audio:Init:STEP 10
2021/08/10 22:36:33    Audio:Init:Complete
2021/08/10 22:36:33    起動時のAudio初期化処理完了
2021/08/10 22:36:33    frmMain(コンストラクタ):STEP 04
2021/08/10 22:36:33    frmMain_Load:STEP 05
2021/08/10 22:36:33    frmMain_Load:STEP 06
2021/08/10 22:36:33    frmMain_Load:STEP 07
2021/08/10 22:36:33    frmMain_Load:STEP 08
2021/08/10 22:36:33    frmMain_Load:STEP 09
2021/08/10 22:36:33    frmMain_Shown:STEP 09
2021/08/10 22:51:59    終了処理開始
2021/08/10 22:51:59    frmMain_FormClosing:STEP 00
2021/08/10 22:52:00    frmMain_FormClosing:STEP 01
2021/08/10 22:52:00    frmMain_FormClosing:STEP 02
2021/08/10 22:52:00    frmMain_FormClosing:STEP 03
2021/08/10 22:52:00    frmMain_FormClosing:STEP 04
2021/08/10 22:52:00    frmMain_FormClosing:STEP 05
2021/08/10 22:52:00    frmMain_FormClosing:STEP 06
2021/08/10 22:52:00    終了処理完了

**Comment by kuma4649** [comment]
これはシステム音を出したときのログですか？

**Comment by denjhang** [comment]
yes

**Comment by denjhang** [comment]
Now I try to play music again, there is still a system prompt.

2021/08/11 11:05:28    起動処理開始
2021/08/11 11:05:28    frmMain(コンストラクタ):STEP 00
2021/08/11 11:05:28    frmMain(コンストラクタ):STEP 01
2021/08/11 11:05:28    frmMain(コンストラクタ):STEP 02
2021/08/11 11:05:28    frmMain(コンストラクタ):STEP 03
2021/08/11 11:05:28    起動時のAudio初期化処理開始
2021/08/11 11:05:28    Audio:Init:Begin
2021/08/11 11:05:28    Audio:Init:STEP 01
2021/08/11 11:05:28    Audio:Init:STEP 02
2021/08/11 11:05:28    Audio:Init:STEP 03
2021/08/11 11:05:28    Audio:Init:STEP 04
2021/08/11 11:05:28    RealChip:Ctr:STEP 00(Start)
2021/08/11 11:05:28    RealChip:Ctr:Found SCCI.(Interface count=1)
2021/08/11 11:05:28    RealChip:Ctr:STEP 01
2021/08/11 11:05:28    RealChip:Ctr:Not found G.I.M.I.C.
2021/08/11 11:05:28    RealChip:Ctr:STEP 02(Success)
2021/08/11 11:05:28    Audio:Init:STEP 05
2021/08/11 11:05:28    Audio:Init:STEP 06
2021/08/11 11:05:28    Audio:Init:VST:STEP 01
2021/08/11 11:05:28    Audio:Init:VST:STEP 02
2021/08/11 11:05:28    Audio:Init:STEP 07
2021/08/11 11:05:28    Audio:Init:STEP 08
2021/08/11 11:05:28    Audio:Init:STEP 09
2021/08/11 11:05:29    Audio:Init:STEP 10
2021/08/11 11:05:29    Audio:Init:Complete
2021/08/11 11:05:29    起動時のAudio初期化処理完了
2021/08/11 11:05:29    frmMain(コンストラクタ):STEP 04
2021/08/11 11:05:29    frmMain_Load:STEP 05
2021/08/11 11:05:29    frmMain_Load:STEP 06
2021/08/11 11:05:29    frmMain_Load:STEP 07
2021/08/11 11:05:29    frmMain_Load:STEP 08
2021/08/11 11:05:29    frmMain_Load:STEP 09
2021/08/11 11:05:29    frmMain_Shown:STEP 09

**Comment by denjhang** [comment]
But when I click the NEXT button, there will be no beep. Only the music selected in the playlist will have an alert tone.

**Comment by kuma4649** [comment]
うーむログにも特に何も記録されていませんね。
こうなると原因わからないですね。。。

**Comment by denjhang** [comment]
It should be a problem with my own computer

**Comment by denjhang** [comment]
I found that I was running a translation software that would automatically copy text in the background, and it would automatically activate the ctrl+c button. This is the reason.
