### ISSUE TITLE
Playlist display error

### ISSUE THREAD

**Issue by denjhang** [kuma4649/MDPlayer#183]
![截图未命名0816233546](https://user-images.githubusercontent.com/61811583/129590693-cc4045ae-0d6d-4d04-9e9a-f56ccc39d85b.jpeg)

**Comment by kuma4649** [comment]
再現方法を教えてくださいませ。

**Comment by denjhang** [comment]
I use two displays. When the file displayed on the primary display is dragged into the MDplayer playlist placed on the secondary display, there is a certain probability that this bug will be triggered.

**Comment by denjhang** [comment]
https://user-images.githubusercontent.com/61811583/129657381-0f704ea0-0fb5-4e4c-86df-f6092c08e5f1.mp4

**Comment by kuma4649** [comment]
STBL193
にて対応しました。ご確認ください。

**Comment by denjhang** [comment]
ok

**Comment by kuma4649** [comment]
ではクローズしますね
