### ISSUE TITLE
Fading out icon is damaged

### ISSUE THREAD

**Issue by denjhang** [kuma4649/MDPlayer#184]
![截图未命名0817104428](https://user-images.githubusercontent.com/61811583/129657883-58b55a88-55b0-481b-8da3-5c85a7fa6251.jpeg)

**Comment by kuma4649** [comment]
発生手順をお願いします。

**Comment by denjhang** [comment]
This error occurs when dragging files to the playlist multiple times.

**Comment by denjhang** [comment]
有关调用实时(JIT)调试而不是此对话框的详细信息，
请参见此消息的结尾。

************** 异常文本 **************
System.InvalidOperationException: 对象当前正在其他地方使用。
   在 System.Drawing.Image.get_Flags()
   在 System.Windows.Forms.ControlPaint.IsImageTransparent(Image backgroundImage)
   在 System.Windows.Forms.Control.PaintBackground(PaintEventArgs e, Rectangle rectangle, Color backColor, Point scrollOffset)
   在 System.Windows.Forms.ButtonInternal.ButtonFlatAdapter.PaintBackground(PaintEventArgs e, Rectangle r, Color backColor)
   在 System.Windows.Forms.ButtonInternal.ButtonFlatAdapter.PaintUp(PaintEventArgs e, CheckState state)
   在 System.Windows.Forms.ButtonInternal.ButtonBaseAdapter.Paint(PaintEventArgs pevent)
   在 System.Windows.Forms.ButtonBase.OnPaint(PaintEventArgs pevent)
   在 System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer)
   在 System.Windows.Forms.Control.WmPaint(Message& m)
   在 System.Windows.Forms.Control.WndProc(Message& m)
   在 System.Windows.Forms.ButtonBase.WndProc(Message& m)
   在 System.Windows.Forms.Button.WndProc(Message& m)
   在 System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   在 System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   在 System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** 已加载的程序集 **************
mscorlib
    程序集版本:4.0.0.0
    Win32 版本:4.7.3468.0 built by: NET472REL1LAST_C
    基本代码:file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
MDPlayer
    程序集版本:1.0.0.0
    Win32 版本:1.0.0.0
    基本代码:file:///D:/Program%20Files%20(x86)/STBL181%2020210710%20binWithoutVST/MDPlayer.exe
----------------------------------------
System.Windows.Forms
    程序集版本:4.0.0.0
    Win32 版本:4.7.3515.0 built by: NET472REL1LAST_C
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    程序集版本:4.0.0.0
    Win32 版本:4.7.3451.0 built by: NET472REL1LAST_C
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    程序集版本:4.0.0.0
    Win32 版本:4.7.3221.0 built by: NET472REL1LAST_C
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
MDSound
    程序集版本:1.0.3.0
    Win32 版本:1.0.3.0
    基本代码:file:///D:/Program%20Files%20(x86)/STBL181%2020210710%20binWithoutVST/MDSound.DLL
----------------------------------------
netstandard
    程序集版本:2.0.0.0
    Win32 版本:4.7.3062.0
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/netstandard/v4.0_2.0.0.0__cc7b13ffcd2ddd51/netstandard.dll
----------------------------------------
System.Core
    程序集版本:4.0.0.0
    Win32 版本:4.7.3515.0 built by: NET472REL1LAST_C
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
NAudio
    程序集版本:1.10.0.0
    Win32 版本:1.10.0.0
    基本代码:file:///D:/Program%20Files%20(x86)/STBL181%2020210710%20binWithoutVST/NAudio.DLL
----------------------------------------
System.Xml
    程序集版本:4.0.0.0
    Win32 版本:4.7.3221.0 built by: NET472REL1LAST_C
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Configuration
    程序集版本:4.0.0.0
    Win32 版本:4.7.3324.0 built by: NET472REL1LAST_C
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
Microsoft.GeneratedCode
    程序集版本:1.0.0.0
    Win32 版本:4.7.3221.0 built by: NET472REL1LAST_C
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    程序集版本:1.0.0.0
    Win32 版本:4.7.3221.0 built by: NET472REL1LAST_C
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
musicDriverInterface
    程序集版本:1.0.0.0
    Win32 版本:1.0.0.0
    基本代码:file:///D:/Program%20Files%20(x86)/STBL181%2020210710%20binWithoutVST/musicDriverInterface.DLL
----------------------------------------
RealChipCtlWrap
    程序集版本:0.0.0.0
    Win32 版本:
    基本代码:file:///D:/Program%20Files%20(x86)/STBL181%2020210710%20binWithoutVST/RealChipCtlWrap.DLL
----------------------------------------
mucomDotNETCompiler
    程序集版本:1.0.0.0
    Win32 版本:1.0.0.0
    基本代码:file:///D:/Program%20Files%20(x86)/STBL181%2020210710%20binWithoutVST/plugin/driver/mucomDotNETCompiler.dll
----------------------------------------
mucomDotNETDriver
    程序集版本:1.0.0.0
    Win32 版本:1.0.0.0
    基本代码:file:///D:/Program%20Files%20(x86)/STBL181%2020210710%20binWithoutVST/plugin/driver/mucomDotNETDriver.dll
----------------------------------------
PMDDotNETCompiler
    程序集版本:1.0.0.0
    Win32 版本:1.0.0.0
    基本代码:file:///D:/Program%20Files%20(x86)/STBL181%2020210710%20binWithoutVST/plugin/driver/PMDDotNETCompiler.dll
----------------------------------------
PMDDotNETDriver
    程序集版本:1.0.0.0
    Win32 版本:1.0.0.0
    基本代码:file:///D:/Program%20Files%20(x86)/STBL181%2020210710%20binWithoutVST/plugin/driver/PMDDotNETDriver.dll
----------------------------------------
System.Windows.Forms.resources
    程序集版本:4.0.0.0
    Win32 版本:4.7.2053.0 built by: NET47REL1
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_zh-Hans_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------
Microsoft.GeneratedCode
    程序集版本:1.0.0.0
    Win32 版本:4.7.3221.0 built by: NET472REL1LAST_C
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.IO.Compression
    程序集版本:4.0.0.0
    Win32 版本:4.7.3062.0 built by: NET472REL1
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.IO.Compression/v4.0_4.0.0.0__b77a5c561934e089/System.IO.Compression.dll
----------------------------------------
System.IO.Compression.FileSystem
    程序集版本:4.0.0.0
    Win32 版本:4.7.3062.0
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.IO.Compression.FileSystem/v4.0_4.0.0.0__b77a5c561934e089/System.IO.Compression.FileSystem.dll
----------------------------------------
System.Drawing.resources
    程序集版本:4.0.0.0
    Win32 版本:4.7.2053.0 built by: NET47REL1
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing.resources/v4.0_4.0.0.0_zh-Hans_b03f5f7f11d50a3a/System.Drawing.resources.dll
----------------------------------------
mscorlib.resources
    程序集版本:4.0.0.0
    Win32 版本:4.7.2053.0 built by: NET47REL1
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_zh-Hans_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------

************** JIT 调试 **************
要启用实时(JIT)调试，
该应用程序或计算机的 .config 文件(machine.config)的 system.windows.forms 节中必须设置
jitDebugging 值。
编译应用程序时还必须启用
调试。

例如:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

启用 JIT 调试后，任何未经处理的异常
都将被发送到在此计算机上注册的 JIT 调试程序，
而不是由此对话框处理。

**Comment by kuma4649** [comment]
申し訳ありませんが、こちらでは20回ほどD&Dしましたが発生しません。

**Comment by denjhang** [comment]
https://user-images.githubusercontent.com/61811583/129786648-c02ef1c1-ac0d-4fb8-907b-add550c6bb40.mp4

**Comment by kuma4649** [comment]
発生した後ではなく、
発生する前をお願いします。。。

**Comment by kuma4649** [comment]
こちらでは５０回ほどD&Dを繰り返しましたが、
エラーがでなく、困っています

**Comment by denjhang** [comment]
I repeat it here about twenty times and it will appear once.

**Comment by denjhang** [comment]
https://user-images.githubusercontent.com/61811583/129792304-558931cc-b3f0-47da-87e8-9bae8ee632f3.mp4

**Comment by kuma4649** [comment]
とりあえず原因はわかっていないし再現もできていませんが、
STBL194で怪しいと思われる個所を修正してみました。
ご確認ください。

**Comment by kuma4649** [comment]
普通にD&Dしているだけで出るんですね。。。
こちらでは出ないんだよなぁorz

**Comment by denjhang** [comment]
There seems to be no such problem now.

**Comment by kuma4649** [comment]
ではクローズしますね
