### ISSUE TITLE
support K054539?

### ISSUE THREAD

**Issue by musicalman** [kuma4649/MDPlayer#186]
こんにちは。
私はコナミのK054539サウンドチップのサポートをお願いしています。
これはK053260の後継で、私の意見では大きく改善されています。
サポートを追加することは可能だと思いますか？お時間をいただきありがとうございます。

**Comment by kuma4649** [comment]
サポート済みですよ。。。

**Comment by musicalman** [comment]
申し訳ありませんが、MDPlayerではなくmml2vgmに入れたつもりでした。
この問題を閉じて、そちらで質問させていただきます。
