### ISSUE TITLE
PSG Inaccurate playback

### ISSUE THREAD

**Issue by denjhang** [kuma4649/MDPlayer#187]
[music0037.zip](https://github.com/kuma4649/MDPlayer/files/7435870/music0037.zip)

The sawtooth wave generated by the envelope generator is gone.

**Comment by kuma4649** [comment]
??

**Comment by denjhang** [comment]
I mean the core of PSG playback is not accurate. There is a VGM file in the above compressed package, and the sound played in the actual PSG chip is significantly different from MDPlayer.

**Comment by denjhang** [comment]
Even playing this vgm file with in_vgm 0.50 sounds much more accurate than MDPlayer.

**Comment by kuma4649** [comment]
Ch1のハードエンベの効き方がバグってる？

**Comment by kuma4649** [comment]
MDSoundのTOPICです...

MDSoundのAYはfmgenによるものですので、違いが出ているのかと思われます

**Comment by denjhang** [comment]
It should be no problem to use the MAME core.

**Comment by kuma4649** [comment]
「さっさとMAME版を移植しろ」と...w

**Comment by kuma4649** [comment]
直ぐはできませんが、頑張ってみます。

**Comment by kuma4649** [comment]
こんな感じで大丈夫でしょうか↓

https://twitter.com/kumakumakumaT_T/status/1456014501833166850?s=20

**Comment by kuma4649** [comment]
STBL207で対応してみました。
いかがでしょうか？

**Comment by kuma4649** [comment]
こちらはいかがでしょうか？

**Comment by denjhang** [comment]
ok

**Comment by kuma4649** [comment]
ではとじますね

**Comment by denjhang** [comment]
The SSG sound of YMF288's actual hardware is similar to that of fmgen, which is not accurate for PSG playback.
But the PSG playback of YM2608 hardware is very accurate.
