### ISSUE TITLE
Switching the audio output to ASIO caused a crash.

### ISSUE THREAD

**Issue by denjhang** [kuma4649/MDPlayer#189]
https://user-images.githubusercontent.com/61811583/140466073-f4cde7b4-3ded-44d4-ba87-4963f961b333.mp4

**Comment by denjhang** [comment]
草

**Comment by kuma4649** [comment]
すみません、voice ミーターは非対応です。

**Comment by denjhang** [comment]
I remember that when I used voice meeter last year, there was no such phenomenon.

**Comment by kuma4649** [comment]
そうですか。。。
としか言いようがありません。

**Comment by denjhang** [comment]
The previous version did not have such a problem. Such as STBL162

**Comment by denjhang** [comment]
I tried to switch ASIO several times with STBL162, and it didn't crash.

**Comment by denjhang** [comment]
And STBL162 uses voicemeeter to play music much smoother than STBL204.

**Comment by kuma4649** [comment]
私の環境ではVOICEミーターでも問題なく動作するんですよね。。。
なので、修正は困難です。
