### ISSUE TITLE
After switching the audio output, the program crashes with multiple SCCI icons

### ISSUE THREAD

**Issue by denjhang** [kuma4649/MDPlayer#190]
https://user-images.githubusercontent.com/61811583/140466265-5fe77006-057b-4f00-9b40-781bfee02a1b.mp4

**Comment by denjhang** [comment]
wwwwww

**Comment by kuma4649** [comment]
これはどちらかというとWindowsの仕様です。
クラッシュ時のアイコンをプログラムから消すのは恐らくできません。

**Comment by denjhang** [comment]
The previous version did not have such a problem. Such as STBL162

**Comment by kuma4649** [comment]
こちらは、Windowsの仕様ということでご理解ください。

**Comment by denjhang** [comment]
Can you provide an option to turn off SCCI?

**Comment by kuma4649** [comment]
それは考えております(^^
新しくISSUEの提起が必要そうですね。
