### ISSUE TITLE
Can you provide an option to turn off SCCI?

### ISSUE THREAD

**Issue by denjhang** [kuma4649/MDPlayer#191]
...

**Comment by kuma4649** [comment]
Memo
 SCCIとGIMICのどちらも使用しない・使用するを選べるようにする。

**Comment by kuma4649** [comment]
Thank you>denjhang

**Comment by kuma4649** [comment]
![image](https://user-images.githubusercontent.com/7453752/140627149-be9ba966-af1e-4d90-8e11-88ff3650c1d4.png)
STBL208で機能を抑制できるようにしました。お試しください。

**Comment by kuma4649** [comment]
こちらはいかがでしょうか

**Comment by denjhang** [comment]
ok

**Comment by kuma4649** [comment]
とじますね
