### ISSUE TITLE
After the setting is over, it crashes inexplicably

### ISSUE THREAD

**Issue by denjhang** [kuma4649/MDPlayer#192]
https://user-images.githubusercontent.com/61811583/140613705-ccdc15f7-0277-4c4c-b0dd-f6d244240a47.mp4

**Comment by denjhang** [comment]
STBL206

**Comment by kuma4649** [comment]
この現象は他のクラッシュの件と何かことなりますか？

**Comment by denjhang** [comment]
no difference.

**Comment by kuma4649** [comment]
ではとじますね。
(違いが無いのであれば、今回は他の件とまとめて対応です。)
