### ISSUE TITLE
"Cannot create a new stack protection page" from time to time

### ISSUE THREAD

**Issue by denjhang** [kuma4649/MDPlayer#193]
STBL206
![截图未命名1106224942](https://user-images.githubusercontent.com/61811583/140613834-82aaf853-77e1-40ad-8a68-2e0176b8267c.png)

**Comment by denjhang** [comment]
无法创建新的堆栈防护页面
新しいスタックガードページを作成できません

**Comment by kuma4649** [comment]
どのタイミングで発生しますか？

**Comment by denjhang** [comment]
There is a certain probability of occurrence.

**Comment by kuma4649** [comment]
何も操作しなくても？
起動した時？
終了時？
設定画面を閉じた時？
演奏停止時？
演奏開始時？

**Comment by kuma4649** [comment]
こちらはいかがでしょうか

**Comment by denjhang** [comment]
The probability of occurrence is small, and it has not happened for several days.

**Comment by kuma4649** [comment]
そうですか！では一旦閉じますね。
