### ISSUE TITLE
OPL3/OPL4 channel order

### ISSUE THREAD

**Issue by Weeppiko** [kuma4649/MDPlayer#194]
OPL3/OPL4 has a weird order for the channels, is this related with 4OP Mode somehow? If it is the case, how do I change it for 2OP Mode?
![image](https://user-images.githubusercontent.com/88540876/142946805-805147ab-4c36-48c5-95bd-62f9980fd147.png)

**Comment by knight-ryu12** [comment]
in OPL3, channel is paired like 1,4, 2,5,..
all channels are actually considered as a "slot".
this is chosen for easy rendering of both 2op and 4op mode
(where it will show 4op marker if channel is considered tied

**Comment by kuma4649** [comment]
knight-ryu12さんの仰る通りです...
