### ISSUE TITLE
Mega Drive ch6 PCM is silent on a certain VGM file

### ISSUE THREAD

**Issue by freq-mod** [kuma4649/MDPlayer#195]
07_Carnival_Night_1.zip(リンクは削除させていただきました。) - このファイルはSMPSPlayで生成されているようです。FMチャンネル6のPCMサンプルは無音. 他のVGMプレイヤーはこの問題を経験していない

**Comment by kuma4649** [comment]
STBL213にて修正しました。お試しください。

**Comment by freq-mod** [comment]
おつかれさまでした!
