### ISSUE TITLE
RESPFM + SPW2でSPPCMが選択できない

### ISSUE THREAD

**Issue by digi-fox-develop** [kuma4649/MDPlayer#198]
RESPFM + SPW2を使用時、OutputタブでSPPCMが選択できない。

SoundタブではYM2610やSEGAPCMでSPWとしてリストから選択可能。

**Comment by kuma4649** [comment]
確認してみます。。。

**Comment by kuma4649** [comment]
あ、これは選択できないのが正解です。
過去にSPPCMをサウンドデバイスとして使用する試みがあったのですが、
現在すすんでいなくて。申し訳ありません。

混乱するので次のリリース時には非表示にしようかと思います。

**Comment by digi-fox-develop** [comment]
残念。
BOSCONIANのMDXファイルで「Good Morning ～from BOSCONIAN-X68」のようにテンポが遅い曲だと
WasapiOutでも再生した時のPDXとの僅かなズレが気になっています。

**Comment by kuma4649** [comment]
あぁ...なるほどです...
でもWasapiでも気になるとなるとSPPCMよりも先ずはASIOを検討されたほうが良いのではないでしょうか...?

**Comment by digi-fox-develop** [comment]
一度、ズレに気が付くと厳しくなってしまって...

ASIOもあまり変わらないです。
DACへの通信でbulk転送を使用しているのと相性が悪いのかもしれません。
いろいろ試してみます。

SPFM Playerは持ってないのでSPW2がお蔵入りに(´;ω;｀)

**Comment by digi-fox-develop** [comment]
SPW2をSegaPCMやC140に割り当てて再生の確認できました。
OKI M6295やOKI M6258にも割り当てできれば．．．
![SPW2](https://user-images.githubusercontent.com/88435951/154076863-ef27d984-1c2a-4bbd-aa90-2f80fa50bcf3.png)


YM2610はYM2608+SPW指定で再生できましたが同時にDACからも音が出てきてビックリしました。
![YM2610](https://user-images.githubusercontent.com/88435951/154084477-033ff744-e9cc-477a-a3d9-6f3266d4910d.png)

**Comment by kuma4649** [comment]
対応しているんでしたっけ...
ちょっと見直してみよう...
>OKI M6295やOKI M6258にも割り当てできれば．．．

**Comment by digi-fox-develop** [comment]
SCCIDefines.hには M6295やM6258そのものは定義されていないですね...
YM2610でSPWを指定して再生できたのでちょっと期待した感じです。
