### ISSUE TITLE
SPFM LightでSlot１のみ使用した場合、選択リストのSlot番号が違う。

### ISSUE THREAD

**Issue by digi-fox-develop** [kuma4649/MDPlayer#200]
SPFM LightでSlot１（外側のスロット）のみ使用した場合、MD Playerの選択リストのSlot番号が"0"と表示される。

Slot1を使用したのはリボンケーブルでモジュールと接続するのに外側のスロットが都合よいからです。
当方の環境のみの現象かもしれませんが、複数のSPFM Lightで同じ現象が発生します。

![mdplayer_20220206](https://user-images.githubusercontent.com/88435951/152649525-c4e75049-ab89-4b9f-be96-46b06d014f02.png)

**Comment by kuma4649** [comment]
ここの値は、SLOTの位置を表しているのではなく、何個目のChipかを表しています。
（0からカウントしているから分かりづらくはあるのですけども...)
ですので恐らくこの場合ですと、SCCI上で両方YM3812として登録すれば
SLOT番号と個数が一致することになるかと思います。

なお、SCCIからスロット番号情報を取得することはできなかったと思います。

**Comment by digi-fox-develop** [comment]
ベースボードセレクトは問題なく行われているので、スロットを識別できる情報がSCCIから取得できているのかと思っておりました。

**Comment by digi-fox-develop** [comment]
SCCIから渡されるのはボードの情報が格納された配列のINDEXなんですね。
