### ISSUE TITLE
MultiPCM playback error

### ISSUE THREAD

**Issue by denjhang** [kuma4649/MDPlayer#205]
[03 Mega Driver.zip](https://github.com/kuma4649/MDPlayer/files/8364473/03.Mega.Driver.zip)

With MDPlayer only screeching noise can be heard, but with the latest version of in_vgm there is no such problem.

**Comment by kuma4649** [comment]
最新バージョンへの更新は優先順位が低いのでいつ対応できるかわからんっす

**Comment by kuma4649** [comment]
STBL225 をお試しください

**Comment by denjhang** [comment]
ok
