### ISSUE TITLE
Abnormal playback of OPLL VGM/MGS

### ISSUE THREAD

**Issue by denjhang** [kuma4649/MDPlayer#214]
[cv3x_04.zip](削除)
For the same piece of music, the music in mgs format is completely normal, and the music in vgz format lacks drum sounds.

**Comment by denjhang** [comment]
[soe009.zip](削除)
It seems that the mgs format also lacks drum sounds. It looks like MDPlayer's OPLL playback core needs fixing.

**Comment by kuma4649** [comment]
どのバージョンからでしょうか

**Comment by denjhang** [comment]
STBL256 20221015 3rd
Could it be that my version is too old?

**Comment by denjhang** [comment]
STBL266 2022/12/25
Using the latest version seems to solve the problem.

**Comment by denjhang** [comment]
I found that STBL266 can only play OPLL MGS normally, but there is no sound when playing OPLL VGM/VGZ.

https://user-images.githubusercontent.com/61811583/210347371-c409230f-aaad-47c4-b4f8-561aea9edcb9.mp4

**Comment by kuma4649** [comment]
なるほど、了解しました。
vgm/vgzは古いOPLLのプログラムを使っているからだと思います。
そのうち直します

**Comment by denjhang** [comment]
STBL267 2023/01/04 confirmed fixes
