### ISSUE TITLE
When playing MGS music, when using AY-3-8910 (mame) core, there is no PSG sound.

### ISSUE THREAD

**Issue by denjhang** [kuma4649/MDPlayer#215]
https://user-images.githubusercontent.com/61811583/210353236-dc76723b-334e-474a-8c9e-41ba9bc80ee3.mp4

笑

**Comment by kuma4649** [comment]
いつのバージョンからでしょうか

**Comment by denjhang** [comment]
> いつのバージョンからでしょうか

STBL266 2022/12/25

**Comment by kuma4649** [comment]
すみません、現象確認できましたので修正しました。

**Comment by denjhang** [comment]
STBL267 2023/01/04 confirmed fixes
