### ISSUE TITLE
zip file import error

### ISSUE THREAD

**Issue by denjhang** [kuma4649/MDPlayer#216]
https://user-images.githubusercontent.com/61811583/210808764-ce955bff-f8cc-4c63-98bf-2b8531c5ccfc.mp4

[okcsp1_vgm.zip](https://github.com/kuma4649/MDPlayer/files/10353081/okcsp1_vgm.zip)
Every time I import the zip file I get this error.

**Comment by kuma4649** [comment]
うーむ、調べてみましたが、
zipをD&Dしたときは自動で演奏開始にしないようにしないと駄目っぽいです。

**Comment by denjhang** [comment]
STBL270 20230107 has fixed this issue
