### ISSUE TITLE
Unable to play untrimmed VGM files

### ISSUE THREAD

**Issue by denjhang** [kuma4649/MDPlayer#218]
[sailormn.zip](削除)

https://user-images.githubusercontent.com/61811583/211187855-894ee7be-ef89-45d4-89a4-9afa20f43057.mp4

**Comment by denjhang** [comment]
now using STBL270 20230107

**Comment by kuma4649** [comment]
申し訳ありませんが、
vgmファイルとして壊れている状態のものまでサポートするつもりは無いですね...
