### ISSUE TITLE
Improved AY8910 visualization

### ISSUE THREAD

**Issue by denjhang** [kuma4649/MDPlayer#219]
https://user-images.githubusercontent.com/61811583/211332228-4ec7e0bf-8ee8-4432-91db-7a8d630c1da2.mp4

The VGM in the video has multiple channels using the envelope at the same time, so I hope that the T/N display can be changed to T/N/E. like this

![sshot-20230109-223354](https://user-images.githubusercontent.com/61811583/211332950-0715f55b-7019-4361-9c92-278908ba77e0.png)

**Comment by denjhang** [comment]
[music0033-ay.zip](削除)

**Comment by kuma4649** [comment]
面白いですね。時間のある時に対応してみます。
ただ、表示の仕方は希望に添えないかな...

**Comment by kuma4649** [comment]
STBL272にて対応
