### ISSUE TITLE
Suggestion: Show numeric values for channel volume

### ISSUE THREAD

**Issue by brickblock369** [kuma4649/MDPlayer#221]
I don't think a bar graph is enough to precisely know what volume a channel is playing in. Showing a numeric value for channel volume, just like the frequency or hardware ADSR data, would help us understand what's going on in the VGM files. This is in case we'd like to imitate the song but also modify it for fun (e.g. SiIvaGunner-like "HQ rips")

**Comment by kuma4649** [comment]
どのチップについて仰っていますか？
というのもFM音源系であれば、TLが音量値になるので...

**Comment by brickblock369** [comment]
I'm referring to PSG chips, such as SN7. This visualizer doesn't have a volume number display, only a bar visualizer.

(Just a sidenote: Sorry for not making this clear enough, today I learn that FM chips have the carrier's TL as the entire volume controller, no other values control it)

**Comment by kuma4649** [comment]
STBL272 にて対応

**Comment by brickblock369** [comment]
Thanks for your update, I've downloaded it. However, when I load MDPlayer.exe, I get this error, despite Jacobi.Vst.Interop.dll already being present inside the same folder. How do I fix this?
![Screenshot (11)](https://user-images.githubusercontent.com/59150779/213899478-26cb38f6-ee3e-4a65-aeb4-7552d84dd5db.png)

**Comment by kuma4649** [comment]
先ずは
removeZoneIdent.bat
を実行してみてください

**Comment by brickblock369** [comment]
Nope. Still getting the same error after running removeZoneIdent.bat.

**Comment by kuma4649** [comment]
binWithoutVST.zip
を使用してみてください。

**Comment by brickblock369** [comment]
Now that works, thanks!
And thanks for showing the numeric volume values 🙏

Though, I only thought of this idea just now, when playing T6W28 vgm files, maybe numeric values for panning could also be shown? Would that sound good?

**Comment by kuma4649** [comment]
T6W28?

**Comment by brickblock369** [comment]
The SN7-like sound chip that has adjustable panning, and noise channel with a frequency independent from channel 3, used in Neo Geo Pocket Color. Used in Sonic Pocket Adventure, for example. I don't know a better way to refer to this chip.

**Comment by kuma4649** [comment]
そのうち対応します

**Comment by kuma4649** [comment]
STBL308にて対応
