### ISSUE TITLE
OPLL drum channel cannot be closed

### ISSUE THREAD

**Issue by denjhang** [kuma4649/MDPlayer#222]
https://user-images.githubusercontent.com/61811583/212958030-b4843bfc-8a5d-4a5e-a52f-831b412a0e30.mp4

**Comment by kuma4649** [comment]
この前の対応の影響で暫定的に使用できなくなっていると思います。
そのうち対応します

**Comment by kuma4649** [comment]
STBL275で対応

**Comment by denjhang** [comment]
STBL275 确认ok
