### ISSUE TITLE
Playlist appears with multiple arrows

### ISSUE THREAD

**Issue by denjhang** [kuma4649/MDPlayer#227]
![sshot-20230310-213402](https://user-images.githubusercontent.com/61811583/224329942-b6822410-7316-4363-bd03-aed53483660e.png)
After I drag the vgm file into the playlist window, and then double-click a track at will, this will happen.

**Comment by kuma4649** [comment]
ちょっと英語ではわかりにくいので、すみませんが動画でお願いできますでしょうか？

**Comment by denjhang** [comment]
The latest version cannot reproduce this issue.
