### ISSUE TITLE
The pitch of the AY8910 VGM is raised by one octave when playing

### ISSUE THREAD

**Issue by denjhang** [kuma4649/MDPlayer#230]
[Digital-Espresso-Revision-2023-12-_01.zip](https://github.com/kuma4649/MDPlayer/files/11760830/Digital-Espresso-Revision-2023-12-_01.zip)
At this time, the sounds played by vgmplay and mdplayer are completely different, and the sound of mdplayer is higher than that of vgmplay.

**Comment by denjhang** [comment]
https://github.com/kuma4649/MDPlayer/assets/61811583/7ba88987-91f2-4968-91fc-308d1db099c9

**Comment by kuma4649** [comment]
うーむ、YM2149に対応していないからですね。
周波数を半分にするだけで良いみたいなので対応してみます。

**Comment by kuma4649** [comment]
STBL307にて対応
