### ISSUE TITLE
OPNB鍵盤の不具合

### ISSUE THREAD

**Issue by maro-suzuki** [kuma4649/MDPlayer#233]
YM2610のミュートが変です。
・ADPCM-Aだけミュートしてから再生すると、Aのミュートが解除される
・ADPCM-Bだけミュートしてから再生すると、AとBがミュートされる

YM2610のSSGが表示されない場合があります。
こちらの詳細はメールしましたので、ご確認ください。

**Comment by kuma4649** [comment]
STBL309にて対応

**Comment by maro-suzuki** [comment]
ありがとうございます。
