### ISSUE TITLE
Add Game Boy (GBS) Support

### ISSUE THREAD

**Issue by sttng** [kuma4649/MDPlayer#234]
Your player and visualizer is fantastic. It would be great to add Game Boy GBS playback.

**Comment by kuma4649** [comment]
CPUの実装が大変なんですよねぇ...

**Comment by sttng** [comment]
I understand. Maybe looking at Sameboy could help: https://github.com/LIJI32/SameBoy  It's sound emulation is very good.

**Comment by kuma4649** [comment]
こちら、一旦クローズします。
