### ISSUE TITLE
S98ファイルを読み込むとクラッシュします。

### ISSUE THREAD

**Issue by kkcokcom** [kuma4649/MDPlayer#235]
S98ファイルを読み込むとクラッシュします。
STBL327, STBL328でこの不具合が起きます。
STBL048では読み込むことができ、再生できました。
使用したS98ファイルはhootで出力させました。

確認をよろしくお願いします。

**Comment by kuma4649** [comment]
STBL330
にて修正しました。お試しください。

**Comment by kkcokcom** [comment]
STBL330 にて再生できることを確認しました。対応して頂きありがとうございました。
