### ISSUE TITLE
Unable to play MDX music using SPFM Light (RE1-YM2151).

### ISSUE THREAD

**Issue by denjhang** [kuma4649/MDPlayer#237]
https://github.com/kuma4649/MDPlayer/assets/61811583/6f1fac34-5ef6-4edf-9e35-cd0e04d10b01

When I select SPFM, it seems that YM2151 is invalid.

**Comment by kuma4649** [comment]
MDXは対応しておりません

**Comment by kuma4649** [comment]
STBL336で暫定対応しました
