### ISSUE TITLE
Playing some VGM using SPFM (RE1: YMF276), channel 6 disappears.

### ISSUE THREAD

**Issue by denjhang** [kuma4649/MDPlayer#239]
When I open the program for the first time, everything will work fine when playing this VGM, but when I play this VGM after playing other VGMs, the sixth channel will disappear.
[SotN Nocturne E.zip]()
This track dynamically switches the FM/PCM function of YM2612 6-channel, which is relatively rare.

**Comment by kuma4649** [comment]
初回起動時の再生でもそれ以外の再生でも、特に不具合は見られませんでした。
再現方法を教えてください。

**Comment by denjhang** [comment]
Please watch these two videos.

**Comment by denjhang** [comment]
削除しました

**Comment by kuma4649** [comment]
音声ではわかりませんでした。
手順を示して頂くようお願いします...

**Comment by denjhang** [comment]
This is very simple, you first play SotN Nocturne E, then play any other vgm track, and then play SotN Nocturne E again, the problem can be reproduced.

**Comment by kuma4649** [comment]
こちらでは再現しないのです

**Comment by kuma4649** [comment]
こちら、どうなりましたか？

**Comment by denjhang** [comment]
https://youtu.be/luHdwO--XNQ
https://youtu.be/tAmrl09Zi8o
Please note the difference between listening to these two videos.
The first video plays SotN Nocturne E.vgm entirely using hardware, and the sound of the FM6 channel disappears.
The second video uses YM2612 PCM emulation and then returns to normal.

**Comment by denjhang** [comment]
Many tracks that use OPN2's sixth channel to alternately play PCM and FM will have this problem, and the problem still exists when using STBL345.It seems that certain VGMs will induce this problem.

**Comment by kuma4649** [comment]
動画のほうは現象がわかりにくくてよくわかりませんが、
文章から察するに、恐らくハードウェアを制御するOS側の問題と思われます。

OPN2のPCMは送信側に非常に正確なタイミングでのデータ送信が求められます。
Windowsは非常に短く正確な間隔で処理することができないOSなので、
それを代替してくれる機能を持たない機器では満足なPCMの再生ができません。
（SCCIはその部類に属する機器です。）

よってMDPlayerでの対策は非常に困難です。

こちらクローズさせていただきます。

**Comment by denjhang** [comment]
It's not that I'm dissatisfied with the poor PCM playback effect of MDPlayer, but when the VGM uses YM2612-6CH's FM and PCM alternately, the 6CH's FM sound will disappear.
The problem is FM not PCM. You need to look into it carefully, I think the question needs to be reopened.

**Comment by kuma4649** [comment]
SCCIの仕様ということで納得してください
