### ISSUE TITLE
Use SPFM to play OPM music without any sound.

### ISSUE THREAD

**Issue by denjhang** [kuma4649/MDPlayer#240]
STBL337 2023/11/24 2nd, after updating this version, the OPM hardware cannot produce any sound, including MDX and VGM formats.
I looked at the indicator lights of the FT232 module and there was no data being sent to the serial port.

**Comment by denjhang** [comment]
There is no problem using STBL336 2023/11/24.

**Comment by kuma4649** [comment]
STBL337を作り直したので再ダウンロードお願いします。
インストール後、scciconfig.exeで設定を再度行ってください

**Comment by denjhang** [comment]
MDPlayer-STBL337_2nd has solved the problem and it seems that there is indeed a BUG.
