### ISSUE TITLE
When playing with RE1-YM2612 hardware, switching tracks produces noise.

### ISSUE THREAD

**Issue by denjhang** [kuma4649/MDPlayer#241]
ファイルは削除しました

**Comment by kuma4649** [comment]
こちらも同様、手順がわからないです。

**Comment by denjhang** [comment]
This phenomenon will occur just by simply playing and switching any VGM music.

**Comment by kuma4649** [comment]
こちらでは再現しないのです。

**Comment by kuma4649** [comment]
こちら、何か進展はありましたでしょうか

**Comment by denjhang** [comment]
This happens when simply switching VGM tracks. I found that using certain versions of SPFM Player V2 will also cause a 0.5s noise when switching tracks. Only OPN2 has this phenomenon, and other types of chips do not.

**Comment by kuma4649** [comment]
どのようなノイズなんでしょう。

**Comment by denjhang** [comment]
I'll record a video first.

**Comment by kuma4649** [comment]
始めの投稿のファイルのことであれば、観れなかったので消しました。

**Comment by denjhang** [comment]
https://youtu.be/F6DLcIB5CA0
MDPlayer Bug: When using SPFM to play OPN2 music, switching tracks will produce a brief sound error.

**Comment by kuma4649** [comment]
videoみれました。大分ひどいですね。。。再現するか確認してみます

**Comment by denjhang** [comment]
I take seriously every bug I find when using MDPlayer, and I will try my best to provide information. Many versions of SPFM Player V2 will also have the same problem, it seems that only specific versions will not do this.

**Comment by kuma4649** [comment]
STBL345にて対策しました。お試しください。

**Comment by denjhang** [comment]
I'll be testing this tonight.

**Comment by denjhang** [comment]
[STBL345](https://github.com/kuma4649/MDPlayer/releases/tag/STBL345)
The latest version has solved this problem.

**Comment by denjhang** [comment]
But when playing 23 - Beta - Walking Bottom.vgm, this problem still exists.
It seems that certain VGMs will induce this problem.

**Comment by denjhang** [comment]
[23 - Beta - Walking Bottom.zip]()

**Comment by denjhang** [comment]
https://youtu.be/mUKG666EiLc

**Comment by kuma4649** [comment]
データファイルの中には実Chipで演奏することを想定しておらず、
一度に大量のデータを実Chipへ送り付けることがあります。
この場合でも、実Chipはリアルタイムで処理を続けてしまうので音が雑音になって再生されてしまいます。

上記のようなケースと思われるので、データ作成者に問い合わせてください。

このISSUEはクローズとさせていただきます
