### ISSUE TITLE
An error occurred while playing FMP music.

### ISSUE THREAD

**Issue by denjhang** [kuma4649/MDPlayer#242]
有关调用实时(JIT)调试而不是此对话框的详细信息，
请参见此消息的结尾。

************** 异常文本 **************
System.InvalidOperationException: There was an error generating the XML document.
 ---> System.ArgumentException: '', hexadecimal value 0x01, is an invalid character.
   at System.Xml.XmlEncodedRawTextWriter.WriteElementTextBlock(Char* pSrc, Char* pSrcEnd)
   at System.Xml.XmlEncodedRawTextWriter.WriteString(String text)
   at System.Xml.XmlEncodedRawTextWriterIndent.WriteString(String text)
   at System.Xml.XmlWellFormedWriter.WriteString(String text)
   at System.Xml.Serialization.XmlSerializationWriter.WriteElementString(String localName, String ns, String value, XmlQualifiedName xsiType)
   at System.Xml.Serialization.XmlSerializationWriter.WriteElementString(String localName, String ns, String value)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterPlayList.Write4_Music(String n, String ns, Music o, Boolean isNullable, Boolean needType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterPlayList.Write5_PlayList(String n, String ns, PlayList o, Boolean isNullable, Boolean needType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterPlayList.Write6_PlayList(Object o)
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Serialize(XmlWriter xmlWriter, Object o, XmlSerializerNamespaces namespaces, String encodingStyle, String id)
   at System.Xml.Serialization.XmlSerializer.Serialize(TextWriter textWriter, Object o, XmlSerializerNamespaces namespaces)
   at System.Xml.Serialization.XmlSerializer.Serialize(TextWriter textWriter, Object o)
   at MDPlayer.PlayList.Save(String fileName)
   at MDPlayer.form.frmPlayList.Save()
   at MDPlayer.form.frmMain.frmMain_FormClosing(Object sender, FormClosingEventArgs e)
   at System.Windows.Forms.Form.OnFormClosing(FormClosingEventArgs e)
   at System.Windows.Forms.Form.WmClose(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

************** 已加载的程序集 **************
System.Private.CoreLib
    程序集版本:6.0.0.0
    Win32 版本:6.0.1523.11507
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.15/System.Private.CoreLib.dll
----------------------------------------
MDPlayerx64
    程序集版本:1.0.0.0
    Win32 版本:1.0.0.0
    代码库:file:///D:/MDPlayer/MDPlayerx64.dll
----------------------------------------
System.Runtime
    程序集版本:6.0.0.0
    Win32 版本:6.0.1523.11507
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.15/System.Runtime.dll
----------------------------------------
System.Windows.Forms
    程序集版本:6.0.2.0
    Win32 版本:6.0.1523.11702
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.15/System.Windows.Forms.dll
----------------------------------------
System.ComponentModel.Primitives
    程序集版本:6.0.0.0
    Win32 版本:6.0.1523.11507
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.15/System.ComponentModel.Primitives.dll
----------------------------------------
System.Windows.Forms.Primitives
    程序集版本:6.0.2.0
    Win32 版本:6.0.1523.11702
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.15/System.Windows.Forms.Primitives.dll
----------------------------------------
System.Runtime.InteropServices
    程序集版本:6.0.0.0
    Win32 版本:6.0.1523.11507
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.15/System.Runtime.InteropServices.dll
----------------------------------------
System.Drawing.Primitives
    程序集版本:6.0.0.0
    Win32 版本:6.0.1523.11507
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.15/System.Drawing.Primitives.dll
----------------------------------------
System.Collections.Specialized
    程序集版本:6.0.0.0
    Win32 版本:6.0.1523.11507
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.15/System.Collections.Specialized.dll
----------------------------------------
System.Collections
    程序集版本:6.0.0.0
    Win32 版本:6.0.1523.11507
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.15/System.Collections.dll
----------------------------------------
System.Threading
    程序集版本:6.0.0.0
    Win32 版本:6.0.1523.11507
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.15/System.Threading.dll
----------------------------------------
System.Diagnostics.TraceSource
    程序集版本:6.0.0.0
    Win32 版本:6.0.1523.11507
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.15/System.Diagnostics.TraceSource.dll
----------------------------------------
System.Diagnostics.Process
    程序集版本:6.0.0.0
    Win32 版本:6.0.1523.11507
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.15/System.Diagnostics.Process.dll
----------------------------------------
System.Drawing.Common
    程序集版本:6.0.0.0
    Win32 版本:6.0.1523.11507
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.15/System.Drawing.Common.dll
----------------------------------------
MDSound
    程序集版本:1.0.3.0
    Win32 版本:1.0.3.0
    代码库:file:///D:/MDPlayer/MDSound.dll
----------------------------------------
netstandard
    程序集版本:2.1.0.0
    Win32 版本:6.0.1523.11507
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.15/netstandard.dll
----------------------------------------
System.Xml.XmlSerializer
    程序集版本:6.0.0.0
    Win32 版本:6.0.1523.11507
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.15/System.Xml.XmlSerializer.dll
----------------------------------------
System.Private.Xml
    程序集版本:6.0.0.0
    Win32 版本:6.0.1523.11507
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.15/System.Private.Xml.dll
----------------------------------------
System.Text.Encoding.Extensions
    程序集版本:6.0.0.0
    Win32 版本:6.0.1523.11507
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.15/System.Text.Encoding.Extensions.dll
----------------------------------------
System.Resources.Extensions
    程序集版本:6.0.0.0
    Win32 版本:6.0.1523.11507
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.15/System.Resources.Extensions.dll
----------------------------------------
System.Memory
    程序集版本:6.0.0.0
    Win32 版本:6.0.1523.11507
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.15/System.Memory.dll
----------------------------------------
System.Collections.NonGeneric
    程序集版本:6.0.0.0
    Win32 版本:6.0.1523.11507
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.15/System.Collections.NonGeneric.dll
----------------------------------------
System.Runtime.Loader
    程序集版本:6.0.0.0
    Win32 版本:6.0.1523.11507
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.15/System.Runtime.Loader.dll
----------------------------------------
System.Text.RegularExpressions
    程序集版本:6.0.0.0
    Win32 版本:6.0.1523.11507
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.15/System.Text.RegularExpressions.dll
----------------------------------------
System.ObjectModel
    程序集版本:6.0.0.0
    Win32 版本:6.0.1523.11507
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.15/System.ObjectModel.dll
----------------------------------------
System.Reflection.Emit.ILGeneration
    程序集版本:6.0.0.0
    Win32 版本:6.0.1523.11507
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.15/System.Reflection.Emit.ILGeneration.dll
----------------------------------------
System.Reflection.Emit
    程序集版本:6.0.0.0
    Win32 版本:6.0.1523.11507
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.15/System.Reflection.Emit.dll
----------------------------------------
Microsoft.GeneratedCode
    程序集版本:1.0.0.0
    Win32 版本:6.0.1523.11507
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.15/System.Private.Xml.dll
----------------------------------------
System.Reflection.Primitives
    程序集版本:6.0.0.0
    Win32 版本:6.0.1523.11507
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.15/System.Reflection.Primitives.dll
----------------------------------------
Microsoft.GeneratedCode
    程序集版本:1.0.0.0
    Win32 版本:6.0.1523.11507
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.15/System.Private.Xml.dll
----------------------------------------
Microsoft.Win32.Primitives
    程序集版本:6.0.0.0
    Win32 版本:6.0.1523.11507
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.15/Microsoft.Win32.Primitives.dll
----------------------------------------
System.ComponentModel.EventBasedAsync
    程序集版本:6.0.0.0
    Win32 版本:6.0.1523.11507
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.15/System.ComponentModel.EventBasedAsync.dll
----------------------------------------
System.Threading.Thread
    程序集版本:6.0.0.0
    Win32 版本:6.0.1523.11507
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.15/System.Threading.Thread.dll
----------------------------------------
Accessibility
    程序集版本:4.0.0.0
    Win32 版本:6.0.1523.11702
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.15/Accessibility.dll
----------------------------------------
System.Text.Encoding.CodePages
    程序集版本:6.0.0.0
    Win32 版本:6.0.1523.11507
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.15/System.Text.Encoding.CodePages.dll
----------------------------------------
System.ComponentModel.TypeConverter
    程序集版本:6.0.0.0
    Win32 版本:6.0.1523.11507
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.15/System.ComponentModel.TypeConverter.dll
----------------------------------------
System.Numerics.Vectors
    程序集版本:6.0.0.0
    Win32 版本:6.0.1523.11507
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.15/System.Numerics.Vectors.dll
----------------------------------------
Microsoft.Win32.SystemEvents
    程序集版本:6.0.0.0
    Win32 版本:6.0.1523.11507
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.15/Microsoft.Win32.SystemEvents.dll
----------------------------------------
System.Collections.Concurrent
    程序集版本:6.0.0.0
    Win32 版本:6.0.1523.11507
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.15/System.Collections.Concurrent.dll
----------------------------------------
System.ComponentModel
    程序集版本:6.0.0.0
    Win32 版本:6.0.1523.11507
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.15/System.ComponentModel.dll
----------------------------------------
System.Drawing
    程序集版本:6.0.2.0
    Win32 版本:6.0.1523.11702
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.15/System.Drawing.dll
----------------------------------------
System.Linq
    程序集版本:6.0.0.0
    Win32 版本:6.0.1523.11507
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.15/System.Linq.dll
----------------------------------------
System.Console
    程序集版本:6.0.0.0
    Win32 版本:6.0.1523.11507
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.15/System.Console.dll
----------------------------------------
System.IO.Compression
    程序集版本:6.0.0.0
    Win32 版本:6.0.1523.11507
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.15/System.IO.Compression.dll
----------------------------------------
System.IO.Compression.ZipFile
    程序集版本:6.0.0.0
    Win32 版本:6.0.1523.11507
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.15/System.IO.Compression.ZipFile.dll
----------------------------------------
System.Private.Uri
    程序集版本:6.0.0.0
    Win32 版本:6.0.1523.11507
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.15/System.Private.Uri.dll
----------------------------------------
NAudio.Midi
    程序集版本:2.1.0.0
    Win32 版本:2.1.0.0
    代码库:file:///D:/MDPlayer/NAudio.Midi.dll
----------------------------------------
NAudio
    程序集版本:2.1.0.0
    Win32 版本:2.1.0.0
    代码库:file:///D:/MDPlayer/NAudio.dll
----------------------------------------
NAudio.Core
    程序集版本:2.1.0.0
    Win32 版本:2.1.0.0
    代码库:file:///D:/MDPlayer/NAudio.Core.dll
----------------------------------------
musicDriverInterface
    程序集版本:1.0.0.0
    Win32 版本:1.0.0.0
    代码库:file:///D:/MDPlayer/musicDriverInterface.dll
----------------------------------------
NAudio.WinMM
    程序集版本:2.1.0.0
    Win32 版本:2.1.0.0
    代码库:file:///D:/MDPlayer/NAudio.WinMM.dll
----------------------------------------
NAudio.Wasapi
    程序集版本:2.1.0.0
    Win32 版本:2.1.0.0
    代码库:file:///D:/MDPlayer/NAudio.Wasapi.dll
----------------------------------------
NAudio.Asio
    程序集版本:2.1.0.0
    Win32 版本:2.1.0.0
    代码库:file:///D:/MDPlayer/NAudio.Asio.dll
----------------------------------------
RealChipCtlWrap64
    程序集版本:0.0.0.0
    Win32 版本:
    代码库:file:///D:/MDPlayer/RealChipCtlWrap64.dll
----------------------------------------
mscorlib
    程序集版本:4.0.0.0
    Win32 版本:6.0.1523.11507
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.15/mscorlib.dll
----------------------------------------
System.Runtime.CompilerServices.VisualC
    程序集版本:6.0.0.0
    Win32 版本:6.0.1523.11507
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.15/System.Runtime.CompilerServices.VisualC.dll
----------------------------------------
Jacobi.Vst.Host.Interop
    程序集版本:2.0.3.0
    Win32 版本:
    代码库:file:///D:/MDPlayer/Jacobi.Vst.Host.Interop.dll
----------------------------------------
Jacobi.Vst.Core
    程序集版本:2.0.0.0
    Win32 版本:2.0.0.0
    代码库:file:///D:/MDPlayer/Jacobi.Vst.Core.dll
----------------------------------------
System.Runtime.Extensions
    程序集版本:6.0.0.0
    Win32 版本:6.0.1523.11507
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.15/System.Runtime.Extensions.dll
----------------------------------------
mucomDotNETCompiler
    程序集版本:1.0.0.0
    Win32 版本:1.0.0.0
    代码库:file:///D:/MDPlayer/plugin/driver/mucomDotNETCompiler.dll
----------------------------------------
mucomDotNETDriver
    程序集版本:1.0.0.0
    Win32 版本:1.0.0.0
    代码库:file:///D:/MDPlayer/plugin/driver/mucomDotNETDriver.dll
----------------------------------------
PMDDotNETCompiler
    程序集版本:1.0.0.0
    Win32 版本:1.0.0.0
    代码库:file:///D:/MDPlayer/plugin/driver/PMDDotNETCompiler.dll
----------------------------------------
PMDDotNETDriver
    程序集版本:1.0.0.0
    Win32 版本:1.0.0.0
    代码库:file:///D:/MDPlayer/plugin/driver/PMDDotNETDriver.dll
----------------------------------------
MoonDriverDotNETCompiler
    程序集版本:1.0.0.0
    Win32 版本:1.0.0.0
    代码库:file:///D:/MDPlayer/plugin/driver/moonDriverDotNETCompiler.dll
----------------------------------------
MoonDriverDotNETDriver
    程序集版本:1.0.0.0
    Win32 版本:1.0.0.0
    代码库:file:///D:/MDPlayer/plugin/driver/MoonDriverDotNETDriver.dll
----------------------------------------
NAudio.WinForms
    程序集版本:2.1.0.0
    Win32 版本:2.1.0.0
    代码库:file:///D:/MDPlayer/NAudio.WinForms.dll
----------------------------------------
Microsoft.Win32.Registry
    程序集版本:6.0.0.0
    Win32 版本:6.0.1523.11507
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.15/Microsoft.Win32.Registry.dll
----------------------------------------
System.Threading.ThreadPool
    程序集版本:6.0.0.0
    Win32 版本:6.0.1523.11507
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.15/System.Threading.ThreadPool.dll
----------------------------------------
System.Windows.Forms.resources
    程序集版本:6.0.2.0
    Win32 版本:6.0.1523.11702
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.15/zh-Hans/System.Windows.Forms.resources.dll
----------------------------------------
Microsoft.GeneratedCode
    程序集版本:1.0.0.0
    Win32 版本:6.0.1523.11507
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.15/System.Private.Xml.dll
----------------------------------------
System.IO.FileSystem.Watcher
    程序集版本:6.0.0.0
    Win32 版本:6.0.1523.11507
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.15/System.IO.FileSystem.Watcher.dll
----------------------------------------
System.Threading.Overlapped
    程序集版本:6.0.0.0
    Win32 版本:6.0.1523.11507
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.15/System.Threading.Overlapped.dll
----------------------------------------
System.Runtime.Serialization.Formatters
    程序集版本:6.0.0.0
    Win32 版本:6.0.1523.11507
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.15/System.Runtime.Serialization.Formatters.dll
----------------------------------------
System.Runtime.CompilerServices.Unsafe
    程序集版本:6.0.0.0
    Win32 版本:6.0.1523.11507
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.15/System.Runtime.CompilerServices.Unsafe.dll
----------------------------------------
System.Xml.ReaderWriter
    程序集版本:6.0.0.0
    Win32 版本:6.0.1523.11507
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.15/System.Xml.ReaderWriter.dll
----------------------------------------
System
    程序集版本:4.0.0.0
    Win32 版本:6.0.1523.11507
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.15/System.dll
----------------------------------------
Microsoft.GeneratedCode
    程序集版本:1.0.0.0
    Win32 版本:6.0.1523.11507
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.15/System.Private.Xml.dll
----------------------------------------
PMDDotNETCommon
    程序集版本:1.0.0.0
    Win32 版本:1.0.0.0
    代码库:file:///D:/MDPlayer/plugin/driver/PMDDotNETCommon.dll
----------------------------------------
Microsoft.GeneratedCode
    程序集版本:1.0.0.0
    Win32 版本:6.0.1523.11507
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.15/System.Private.Xml.dll
----------------------------------------
System.Diagnostics.StackTrace
    程序集版本:6.0.0.0
    Win32 版本:6.0.1523.11507
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.15/System.Diagnostics.StackTrace.dll
----------------------------------------
System.Reflection.Metadata
    程序集版本:6.0.0.0
    Win32 版本:6.0.1523.11507
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.15/System.Reflection.Metadata.dll
----------------------------------------
System.Collections.Immutable
    程序集版本:6.0.0.0
    Win32 版本:6.0.1523.11507
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.15/System.Collections.Immutable.dll
----------------------------------------

************** JIT 调试 **************

**Comment by denjhang** [comment]
![sshot-20231222-000351](https://github.com/kuma4649/MDPlayer/assets/61811583/53731747-6ca9-408e-922e-2a4b441d6f41)

**Comment by denjhang** [comment]
This error prevents me from closing MDPlayer.

**Comment by kuma4649** [comment]
例によって、私の環境ではエラーが発生しないので原因が分からず、直せません。

メッセージをみるとプレイリストを保存しようとしたところでエラーになっているようなのでその原因になっているファイルが絞れるかもしれません。どんなデータをプレイリストに並べていますか？
多数ある場合はできるだけ少なくなるまで原因を絞ってください。

**Comment by denjhang** [comment]
https://github.com/kuma4649/MDPlayer/assets/61811583/251300ee-2597-44ef-9753-bb2c34e8e72c

**Comment by denjhang** [comment]
I use the following paths to store music in formats OPI and OVI.
F:\存储器备份\2023.1.17 音乐档案\mdxo_-_fmppmd_complete__bc967\FMPPMD\Game\Falcom\Sorcerian\PC98-KID

As long as these music are dragged into MDPlayer and played, this BUG will be triggered.
But sometimes the BUG is not triggered, which is strange.

**Comment by denjhang** [comment]
[PC98-KID.zip](削除しました)

**Comment by kuma4649** [comment]
原因が依然としてわかりませんが怪しい所に対策を入れてみました。
もし当たっていたら、エラーメッセージボックスが表示され、終了すると思います。

＞STBL342

**Comment by kuma4649** [comment]
全然解決にはなりませんが。

**Comment by kuma4649** [comment]
これどうなりましたでしょうか

**Comment by kuma4649** [comment]
#MDPlayer STBL343 2023/12/28
をお試しください。

**Comment by kuma4649** [comment]
こちらどうなりましたか

**Comment by denjhang** [comment]
This issue has not been found yet and seems to have been resolved.

**Comment by kuma4649** [comment]
であれば閉じます
