### ISSUE TITLE
ADPCM and FM are out of sync when using SPFM to play FMP music

### ISSUE THREAD

**Issue by denjhang** [kuma4649/MDPlayer#244]
When I use SPFM to play FMP music, MDPlayer seems to go into a frozen state for a few seconds (no RD icon is displayed) when loading ADPCM, and then starts producing sound. FM and ADPCM are out of sync for the first few seconds, and after about 5 seconds Just completely synchronized.

**Comment by denjhang** [comment]
https://youtu.be/ldm9BPcm06E
Here is a video showing this bug. I used a USB audio collector to input the SPFM sound into the computer.

**Comment by kuma4649** [comment]
恐らく原因は実音源はADPCMのメモリにデータを転送するのに時間がかかることだと思います。
が、これに対応するにはFMP側に仕掛けを追加する必要があります。
しかしFMPはソースを公開していないのでほぼ無理かと思われます。

**Comment by kuma4649** [comment]
#MDPlayer STBL343 2023/12/28
をお試しください。

**Comment by kuma4649** [comment]
こちら、効果ありましたか？

**Comment by denjhang** [comment]
I'll look into it today.

**Comment by denjhang** [comment]
The latest version synchronizes FM and ADPCM faster. Currently, synchronization can be achieved within 1 second, but the initial 1 second is very chaotic.

**Comment by denjhang** [comment]
It looks like it caused other bugs, FM tracks playback is now much slower using FM only.

**Comment by denjhang** [comment]
https://youtu.be/7F6DlOKOMJY
Here is the test video.

**Comment by kuma4649** [comment]
こちらも対策したうえでの現状であるならばこれ以上の改善は難しいですね。
（ちなみに例によって私の環境では発生しません）

ハードウェアが悪いかチェックするとか、他人のPCでも現象がでるかとか試しましたか？
またオーディオデバイスはハードウェアのASIOを使用していますか？
(MDPlayerは実Chipであってもオーディオデバイスの性能が絡んできます)

**Comment by denjhang** [comment]
I don't use ASIO, I use WaveOUT.

**Comment by kuma4649** [comment]
できるだけ、AsioOutか、無理ならWasapiOutを選択してください。
WaveOutやDirectSoundは緊急向け又は、おまけでつけています。
![image](https://github.com/kuma4649/MDPlayer/assets/7453752/f187d202-bb3f-4e6a-96af-b0dcd00c84e9)

**Comment by kuma4649** [comment]
![image](https://github.com/kuma4649/MDPlayer/assets/7453752/99b90681-bc56-4820-a8c1-1e10e90f39c7)
また、Asio Out以外の場合は、「遅延時間(レンダリングバッファ)」をできるだけ小さくしてください。
(但し小さすぎると音切れを起こしたりハングアップしたりします)

**Comment by kuma4649** [comment]
こちらどうなりましたか

**Comment by denjhang** [comment]
STBL347 still has this problem, and the FM part playback speed is 2 times the PCM speed, which is very inconsistent.
The video first shows the sound played using SPFM (abnormality).
Then I used the emulation core to play OZI (normally).
https://youtu.be/BH-kndG0J_A


By the way, there is no such problem in the STBL345 version. At that time, there was just a delay in ADPCM and it would automatically return to normal after a few seconds.
The STBL347 version can't even hear the ADPCM sound because the playback speed is too fast.

**Comment by kuma4649** [comment]
![image](https://github.com/kuma4649/MDPlayer/assets/7453752/b9f06b18-0996-40bc-a8f6-471a1bc9437f)
ここのチェックマークを消してみて試してもらえますか。

あと、AsioOutか、無理ならWasapiOutを選択してください。

**Comment by denjhang** [comment]
I hope the code related to OZI falls back to STBL345, which is acceptable.

**Comment by kuma4649** [comment]
FMP関連のコードに大きな違いは無いです

**Comment by kuma4649** [comment]
参考用に私の設定を。
![image](https://github.com/kuma4649/MDPlayer/assets/7453752/b6f3444f-2d7d-405b-b317-e449321678f5)
![image](https://github.com/kuma4649/MDPlayer/assets/7453752/9ba1c763-e42e-49ed-b0ed-20a23922e40c)

**Comment by denjhang** [comment]
In the STBL345 version, no matter which audio output I choose, there is no big problem, and the out-of-sync phenomenon only occurs in the first two seconds. But STBL347 is in a similar situation no matter which setting is selected.
I don't have hardware USB ASIO, can you test the output using wasapi or a few other options?

**Comment by kuma4649** [comment]
Wasapiでも問題なく演奏できてます。
![image](https://github.com/kuma4649/MDPlayer/assets/7453752/1d41da50-d4d7-4a35-8eae-62c7f9a76e27)
これ、チェックオフしましたか？

**Comment by denjhang** [comment]
In the STBL345 version, ADPCM syncs fine with your setup.

**Comment by denjhang** [comment]
In the STBL347 version, ADPCM syncs fine with your setup.

**Comment by kuma4649** [comment]
![image](https://github.com/kuma4649/MDPlayer/assets/7453752/0c6db47b-d313-4e96-9b0e-99fed39f9c4e)

これ、チェックオフしましたか？

**Comment by denjhang** [comment]
![sshot-20240113-224128](https://github.com/kuma4649/MDPlayer/assets/61811583/d45f4456-95ea-4717-bf4a-4e914fdb79d1)
Yes, that's how it was set up, and now it's completely normal, it's amazing.

**Comment by kuma4649** [comment]
Yes！
正しく演奏されますか？

**Comment by denjhang** [comment]
yes

**Comment by kuma4649** [comment]
ではクローズします

**Comment by denjhang** [comment]
So I want MDPlayer to adapt to SPFM-Y8950, Y8950 and YM2608 are very similar, in rebirth hardware, they use the same DRAM.
