### ISSUE TITLE
When playing MGS music, MDPlayer cannot be closed.

### ISSUE THREAD

**Issue by denjhang** [kuma4649/MDPlayer#246]
![sshot-20231225-000153](https://github.com/kuma4649/MDPlayer/assets/61811583/f0b5cde2-626a-41ae-b519-c03d7148f2b1)

**Comment by denjhang** [comment]
[mgs.zip](削除)

**Comment by kuma4649** [comment]
保存できないようなファイル名や、曲情報があると思われます。
どのファイルが原因になっているか教えていただけないでしょうか。

**Comment by kuma4649** [comment]
#MDPlayer STBL343 2023/12/28
をお試しください。

**Comment by kuma4649** [comment]
こちらどうなりましたか

**Comment by denjhang** [comment]
This problem no longer occurs.

**Comment by kuma4649** [comment]
では閉じます
