### ISSUE TITLE
YM2612 support for c86ctl

### ISSUE THREAD

**Issue by redonj** [kuma4649/MDPlayer#249]
Megadrive OPN2 (YM2612) was added to GIMIC as a STIC module. It would be nice to be able to enable it within options.
OPN2C (YM3438C-D) and Game Gear's 315-5377 were also released but priority for them is low I guess.

**Comment by kuma4649** [comment]
STBL352をお試しください。
その際、c86ctl.dllは例えばc86ctl_.dllなどにファイル名を変更して、
本来のc86ctlを無効にしてください。

**Comment by redonj** [comment]
YM2612と315-5377を試して無事に鳴りました！
