### ISSUE TITLE
When using SPFM to play OPN2+DCSG music, the DCSG noise is wrong.

### ISSUE THREAD

**Issue by denjhang** [kuma4649/MDPlayer#250]
Please watch this video and listen to the sound.
https://youtu.be/5EiNwDqKnPQ
Question #241 also appeared in the video.
https://github.com/kuma4649/MDPlayer/issues/241

**Comment by kuma4649** [comment]
「DCSGのノイズがおかしい」とは、どのようにおかしいのか動画をみてもいまいちわかりません。
もう少し詳しく教えていただけませんか？

あと#241のバグがまた発生するのでしょうか。


どうにもお互いの意図が伝わりにくくコミュニケーションをとるのが辛いです。

**Comment by denjhang** [comment]
I need to record another video to compare the sound produced by spfm and emulation core. You will know after comparison.

**Comment by kuma4649** [comment]
こちらどうなりましたか

**Comment by denjhang** [comment]
STBL347 still has this problem, please watch the video:https://youtu.be/8QTHIlEpWpM
The video first shows the use of the simulation core to play the sound of SN76489 (white noise is normal),
The sound using SPFM-SN76489 is then shown (sounds like white noise mode wrong).

**Comment by kuma4649** [comment]
なるほど、noiseが出せないのですね。
しかしこれも私の環境では発生しません。
申し訳ないですが修正はできそうにありません。

**Comment by kuma4649** [comment]
https://github.com/kuma4649/MDPlayer/assets/7453752/ef2cdc5f-c14b-4e4a-a935-c5e47226d0dc
私の環境では正しく演奏されます

**Comment by denjhang** [comment]
It does run normally on your computer. On my side, when playing music using only DCSG, the noise is normal, but when playing OPN2+DCSG, it is not normal.

**Comment by kuma4649** [comment]
申し訳ないですけど環境の問題としか言いようが無いです。

**Comment by denjhang** [comment]
I have a question, have you ever used MD's music for testing? Maybe it's caused by differences in music files? Your music in the video was compiled by MucomMD2vgm.

**Comment by denjhang** [comment]
I carefully checked the schematic diagram of RE1-SN76489. This should not be a difference caused by hardware. So please test the music here again:
[sonic3.zip](削除)

**Comment by denjhang** [comment]
If a large amount of MD music cannot be played correctly, then there is still a BUG somewhere.

**Comment by kuma4649** [comment]
問題なく鳴ってます。

**Comment by kuma4649** [comment]
いや、確認できた！
調査します。

**Comment by denjhang** [comment]
😅😅😅😅😅So don't be too impatient, I'm not making trouble for nothing.

**Comment by kuma4649** [comment]
調査をしたところ、
「特定の条件で「C0」を実チップへ送信すると発生する現象」
であることが判明しました。

当然ながらMD実機での演奏は問題ないので、
もしかするとSCCI特有の現象かもしれません。

対策としては、
「SCCIに「C0」を送信しようとしたら強制的に「C1」に変換」
するようにします。
これによりMDと比較して再生結果に若干の差がでますが、
現象は回避できます。

**Comment by kuma4649** [comment]
STBL350をお試しください。

**Comment by denjhang** [comment]
Today I will test this, in fact the latest version of SPFM Player V2 also has this problem, however the authors of SCCI and SPFM refuse to communicate and fix any existing BUG. Thank you for your work.

**Comment by denjhang** [comment]
This is of course a SCCI-specific BUG, because there is no such problem in other hardware OPN2+DCSG players.

**Comment by denjhang** [comment]
STBL350 Perfectly solved, this is a problem that SPFM Player and SCCI have not solved for ten years. Since the SCCI author refuses to communicate, only you have completed this.

**Comment by kuma4649** [comment]
それではクローズします
