### ISSUE TITLE
STBL345 play OZI music, loading speed and music speed are very slow, PPZ8 is lost.

### ISSUE THREAD

**Issue by denjhang** [kuma4649/MDPlayer#251]
MDPlayer BUG: When using the STBL345 version to play music in OZI format, the loading speed and music speed are very slow, and PPZ8 is lost.
OVI and OZI playback speed is very slow.
https://youtu.be/JnacF6ERqog
[Spindizzy.zip]()

**Comment by kuma4649** [comment]
こちらでは現象は発生しません。
何か関係ありそうなログとかありませんか。
![image](https://github.com/kuma4649/MDPlayer/assets/7453752/78ae50a0-78ff-4348-a950-2023a7f7ab15)

**Comment by denjhang** [comment]
When I check the log, I will record a video again and check the log while playing OZI, OVI music.

**Comment by kuma4649** [comment]
こちらどうなりましたか

**Comment by denjhang** [comment]
How to open the console, I can't find it.

**Comment by kuma4649** [comment]
![image](https://github.com/kuma4649/MDPlayer/assets/7453752/d4402370-403e-45d1-bbf6-d303075681ee)
Option > Omake > Debug Mode > Show Console(startup only) > OK > プログラム終了 > プログラム起動
の順で設定してみてください。
（ただし、スクリーンショットではLogLevelをTraceにしていますが、この選択はかなり負荷をかけます。)

**Comment by kuma4649** [comment]
こちらどうなりましたか

**Comment by denjhang** [comment]
STBL347 still has this problem, and the FM part playback speed is 2 times the PCM speed, which is very inconsistent.

**Comment by denjhang** [comment]
The video first shows the sound played using SPFM (abnormality).
Then I used the emulation core to play OZI (normally).
https://youtu.be/BH-kndG0J_A

**Comment by kuma4649** [comment]
これはひどい。(T_T
ログも特にエラーが出ているわけでもなさそうで、原因わかりません。
更に自分のところでは再現しないので調査も出来ないので、お手上げです。
申し訳ありませんが、諦めてください。

**Comment by kuma4649** [comment]
https://github.com/kuma4649/MDPlayer/assets/7453752/31238072-7b4a-4f6c-94de-bda65dff9fd7

私の環境では問題ありません。

**Comment by denjhang** [comment]
problem solved.
