### ISSUE TITLE
MDPlayer BUG: When STBL345 plays M (PMD), it freezes in the first two seconds.

### ISSUE THREAD

**Issue by denjhang** [kuma4649/MDPlayer#252]
https://youtu.be/9IgXC-RGz8U
[FM大王.zip](削除)
The compressed package contains files for testing.

**Comment by kuma4649** [comment]
対策したうえでモタっているのでこれ以上はむずかしいです。
（ちなみに私の環境では発生しません)

解凍処理にてまどっているのかもしれないのでzipのままをやめてみるとか、
ウィルス対策ソフトが邪魔している可能性があるかもしれないのでそれを終了させて試してみるとか、
かなり難しいかとは思いますが、元ファイルを改造して演奏開始前に少し休符をいれるとか
しか対策が思い浮かびません。申し訳ございません。

**Comment by denjhang** [comment]
There is no problem listening to music using the emulator core. I will try SPFM again using the latest version of MDPlayer.

**Comment by kuma4649** [comment]
こちらどうなりましたか

**Comment by denjhang** [comment]
STBL347 does not have this problem.

**Comment by kuma4649** [comment]
ではクローズします
