### ISSUE TITLE
Feature request: Add hotkey for next song.

### ISSUE THREAD

**Issue by denjhang** [kuma4649/MDPlayer#253]
Currently, MDPlayer only has the function of moving the cursor through shortcut keys, and there is no hotkey to directly switch to the next song.
![sshot-20240113-114121](https://github.com/kuma4649/MDPlayer/assets/61811583/64d0baec-87bf-4f30-b8e5-c9ea4aed37ff)
![sshot-20240113-114037](https://github.com/kuma4649/MDPlayer/assets/61811583/c5fa3bfc-6a99-474c-8d3a-ad031be24a4a)

**Comment by kuma4649** [comment]
![image](https://github.com/kuma4649/MDPlayer/assets/7453752/28720d79-2347-4914-b5fd-13d558b92709)
これ設定してください

**Comment by denjhang** [comment]
> ![image](https://private-user-images.githubusercontent.com/7453752/296436766-28720d79-2347-4914-b5fd-13d558b92709.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUxMzE2NDcsIm5iZiI6MTcwNTEzMTM0NywicGF0aCI6Ii83NDUzNzUyLzI5NjQzNjc2Ni0yODcyMGQ3OS0yMzQ3LTQ5MTQtYjVmZC0xM2Q1NThiOTI3MDkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTNUMDczNTQ3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTNiYzBkOTc2YTIzNzZkOTQyOTUxZjdiN2JkMjM5MWU1NzlmN2U0MDRlYTE4MzA3MjJkNTljMWMwMjA0Mjc1ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.a4-zPu9WxKpfcMwh2SaTatMwAk7kbg5T68BlJvwVzbY) これ設定してください

It turns out that this function already exists, but I didn't understand Fwd and prev.
