### ISSUE TITLE
Feature Request: When using SPFM, pressing the pause hotkey also pauses the sound.

### ISSUE THREAD

**Issue by denjhang** [kuma4649/MDPlayer#254]
![sshot-20240113-161551](https://github.com/kuma4649/MDPlayer/assets/61811583/1bfcf5a1-8c2e-4df1-8eb1-d7ac61c0088c)
![sshot-20240113-161601](https://github.com/kuma4649/MDPlayer/assets/61811583/82b6b108-9350-4b54-b520-0f0c4bf19130)

I hope when using SPFM, "Don't render when paused", will also work.
Currently, when I click pause when using SPFM, the sound will not stop.

**Comment by denjhang** [comment]
https://youtu.be/oJknTO2y1E4

**Comment by kuma4649** [comment]
これは、実チップでは無理です。
復帰が困難だからです。
