### ISSUE TITLE
Channel names do not turn yellow when using SPFM-OPL3.

### ISSUE THREAD

**Issue by denjhang** [kuma4649/MDPlayer#255]
![sshot-20240114-031435](https://github.com/kuma4649/MDPlayer/assets/61811583/2fd0cdc2-5ef8-4a16-9d64-2ff4f7a8db9a)

**Comment by denjhang** [comment]
When other chips use real hardware, the channel name will automatically turn yellow.
![sshot-20240114-031839](https://github.com/kuma4649/MDPlayer/assets/61811583/090b2b5c-45f2-4b3b-b94d-d89a9b1c9687)

**Comment by kuma4649** [comment]
STBL348をお試しください。

**Comment by denjhang** [comment]
ok
