### ISSUE TITLE
Recommendations for optimizing YM2612 PCM transmission.

### ISSUE THREAD

**Issue by denjhang** [kuma4649/MDPlayer#258]
I found that the PCM pitch of the YM2612 is on the high side when using SPFM, can you lower the PCM pitch slightly? That might sound better.
This function is implemented in the 20170920 version of SPFM Player V2. You can compare it. The PCM played by this version sounds relatively normal.
[SPFMPlayerV2_20170920.zip](https://github.com/kuma4649/MDPlayer/files/13959095/SPFMPlayerV2_20170920.zip)

**Comment by kuma4649** [comment]
OPN2のPCM再生は現状維持でお願いします。
仕様と思ってください。
