### ISSUE TITLE
STBL358 residual process after the main program is closed

### ISSUE THREAD

**Issue by denjhang** [kuma4649/MDPlayer#259]
![sshot-20240217-223646](https://github.com/kuma4649/MDPlayer/assets/61811583/db90749b-5966-45e9-b5e7-af784847de95)

**Comment by denjhang** [comment]
https://youtu.be/DrjP3u7VPOk

**Comment by denjhang** [comment]
The STBL350 version does not have this problem.

**Comment by kuma4649** [comment]
こちらでは再現しないので対応困難です。

**Comment by denjhang** [comment]
This may be an environmental issue, if there is only one computer like this then it is not an issue with MDPlayer. I will test the latest version again on another computer.

**Comment by denjhang** [comment]
It has been confirmed that this happens to only one computer. I use STBL361 on another computer and this problem does not occur.

**Comment by kuma4649** [comment]
では対応困難であるのでとりあえずクローズします
