### ISSUE TITLE
YM2151のエミュレーターを切り替えられない

### ISSUE THREAD

**Issue by ieno98** [kuma4649/MDPlayer#263]
STBL095からSTBL374に更新しました。STBL095ではYM2151のエミュレーションをfmgenからmameに切り替えられましたがSTBL374ではうまくいきません。
OptionsのSoundタブのEmu(mame)もしくはEmu(X68Sound)ラジオボタンを押してもfmgenの音のままです。

**Comment by kuma4649** [comment]
STBL375で修正しました。
お試しください。

**Comment by ieno98** [comment]
STBL375で設定できるようになったのを確認しました。ですがEmu(X68Sound)では音がでますが、Emu(mame)を選択すると音が出ません。

**Comment by kuma4649** [comment]
此方で試してみましたが問題なさそうでした。
とりあえずファイルの形式を教えていただけますでしょうか。
mdxは対応していませんので...

**Comment by ieno98** [comment]
mdxを読み込ませていました。試しにvgmを再生したところ、無事Emu(mame)でも音がなりました。
私の環境でも問題ないようです、失礼しました。対応ありがとうございました。

**Comment by kuma4649** [comment]
STBL377で対応してみました。
申し訳ないですが、とりあえず演奏できるようにしただけなので何か不具合があるかもしれません。
今まで対応していなかったのは確か理由があったはずなのですがどうも思い出せなくて...

よろしくお願いいたします。

**Comment by ieno98** [comment]
驚きました。早速、同じ曲データでmdxとvgmをそれぞれ再生してみましたが、出力の面では違いが見られませんでした。
それよりも、急にMicrosoft Defenderがウイルスと誤検知するようになったことが気になりますね。
タイトルの問題は解決したように思いますので、Closeするかどうかの判断はおまかせします。

**Comment by kuma4649** [comment]
のらアプリの宿命みたいなところなので仕方が無いかなぁと思います..
