### ISSUE TITLE
OPM "LFOSQ"

### ISSUE THREAD

**Issue by RaijinXBlade** [kuma4649/MDPlayer#265]
OPM has LFOSQ here.
![image](https://github.com/kuma4649/MDPlayer/assets/67564869/a2f3b564-57d1-4dc9-881e-7f9eca529fc1)
What does it do?

Lastly, it's unrelated, but...
[example.zip](https://)
Do you know what is happening here in channel 5?

**Comment by kuma4649** [comment]
LFOSQ -> LFO SYNC

>Do you know
わかりません。。。
