### ISSUE TITLE
HIGHDPI設定時のオプション画面におけるテキストのはみ出し問題について

### ISSUE THREAD

**Issue by yuuqilin** [kuma4649/MDPlayer#267]
HIGHDPI設定が有効な環境では、オプション画面のテキストが拡大表示されることにより、画面内に収まりきらず、一部が切れてしまう現象が発生しています。以下の画像をご参照ください：
![Snap1](https://github.com/user-attachments/assets/16d9175f-9939-484c-95b6-cced642bf50d)

**Comment by kuma4649** [comment]
ごめんなさい。HIGH DPIには対応していません。
