### ISSUE TITLE
OPL4のVGZを再生したときに一部の音声が正しく再生されない

### ISSUE THREAD

**Issue by src3453** [kuma4649/MDPlayer#269]
MDPlayer STBL488
vgz file: [05 encounter the unknown environment.vgz.zip](https://github.com/user-attachments/files/18035347/05.encounter.the.unknown.environment.vgz.zip) (VGMPlayで正常に再生されることを確認済み)
keyboard上では正しく再生されているように見えますが、実際は一部のチャンネルが抜け落ちて正しく再生されません。

**Comment by src3453** [comment]
[comparison.zip](https://github.com/user-attachments/files/18035495/comparison.zip)
比較MP3

**Comment by kuma4649** [comment]
先ずは以下の内容の確認をお願いします。

・YMF278Bのエミュレーション時、MoonSoundの音色を鳴らすために以下のROMファイルが必要です。
作成方法は申し訳ありませんがお任せします。
yrw801.rom

**Comment by src3453** [comment]
ありがとうございます、ファイルが不足していました。
romファイルはどこに配置すればよろしいでしょうか？
確認次第issue閉じさせていただきます。

**Comment by src3453** [comment]
解決しました。
