### ISSUE TITLE
[Bug] Player doesn't work with Windows 10 1803 (17134.1)

### ISSUE THREAD

**Issue by katananja** [kuma4649/MDPlayer#31]
MDPlayer doesn't work with Windows 10 April 2018 Update.
.Net Framework 4.5/4.5.2 is incompatible with Windows 10 1803 (17134.1)
.Net Framework 4.7/4.7.1 is incompatible with Windows 10 1803 (17134.1)

**Comment by knight-ryu12** [comment]
it does work under Windows 10, any revision.
(Tested and it worked.)

**Comment by kuma4649** [comment]
先ずは以下のプログラム３つがインストールされているかご確認ください。
これでも駄目な場合はまたご連絡くださいませ。

・.NET Framework4.5/4.5.2
・Visual Studio 2012 更新プログラム 4 の Visual C++ 再頒布可能パッケージ 
・Microsoft Visual C++ 2015 Redistributable(x86) - 14.0.23026

**Comment by katananja** [comment]
.Net Framework 4.5/4.5.2 is **incompatible (互換性のない)** with Windows 10 1803 (17134.1), doesn't matter if I download it and try to install it, it say I have a new version already installed and quits.

Microsoft Visual C++ 2015 Redistributable(x86) - 14.0.23026 - Same issue, the system version is newer, I've the 14.0.24215

Visual C++ Redistributable for Visual Studio 2012 Update 4 - Installed both, x86 and x64.

MDPlayer say that it can't load "NScci.dll" because a dependency is missing. Loading "NScci.dll" in "[dependency walker](http://www.dependencywalker.com/)" it show problems.
![nscci dll](https://user-images.githubusercontent.com/9029191/39651008-a87059a2-4fc0-11e8-95b3-ba70056dd87c.png)

Download the ISO from Microsoft and do a fresh install, the bug will show up. The bug doesn't happen if you just update the Windows.
https://www.microsoft.com/pt-br/software-download/windows10ISO

**Comment by katananja** [comment]
Now I know what is happening.
NScci.dll require **vcruntime140.dll** that comes with **Microsoft Visual C++ 2015 Redistributable (x86)**, BUT, the available version is newer on Windows 10 1803 (17134.1), the available version to download is older. To make matters worse, the C:\Windows\System32\vcruntime140.dll file is x64 and not x32, causing all the trouble.

For now, is necessary to install **Visual C++ Redistributable for Visual Studio 2012 Update 4 (x86)**, find a x86 version of **vcruntime140.dll** and paste it over MDPlayer folder.

This fix the issue with MDPlayer, for now, in the future Microsoft might issue a update to handle this properly.
![nscci dll_runtime](https://user-images.githubusercontent.com/9029191/39659719-4cef11dc-5005-11e8-924a-5be3132cbfe7.png)

**Comment by kuma4649** [comment]
つまり、x32のvcruntime140.dllが必要な位置にx64が入っていたというこうとですね？

**Comment by knight-ryu12** [comment]
そうですね

2018年5月5日(土) 15:12 kuma <notifications@github.com>:
