### ISSUE TITLE
TAG008以降のリリースにおいてMIDI変換機能が正常に働かない

### ISSUE THREAD

**Issue by doranarasi** [kuma4649/MDPlayer#32]
タイトル通りなのですが調べてもこのような問題に困っている方はいらっしゃらないようなので、
私だけが発生しているのかそうでないのかわかりませんが…
YM2151のデータは持っていないので試した変換はYM2161だけです。

最新のTAG061で試した結果、
MIDIExport.csのバージョンを一つ戻すだけでとりあえずまともに変換できるようになるみたいです。
44100.0 の部分が common.SampleRate に変わったのが原因のようなのですが、
当方プログラミングについてろくに知識がないので、
これで何か別の問題が起きてしまわないのかとかそういったことはさっぱりわかりません。

**Comment by doranarasi** [comment]
更新お疲れ様です、問題なく変換できました。

**Comment by kuma4649** [comment]
ご確認いただきありがとうございました。
また何かありましたら是非よろしくお願いします。
