### ISSUE TITLE
Muting/unmuting channels on OPL4 doesn't work

### ISSUE THREAD

**Issue by raphaelgoulart** [kuma4649/MDPlayer#35]
Tested with these songs: https://soundcloud.com/naruto2413/moondriver-for-opl3-demo-001-004

I can confirm muting works with the YM2612 and YM2608 (OPNA) sound chips. Only on the OPL4 chip it doesn't work.

Thanks in advance.

**Comment by kuma4649** [comment]
こんにちは。
ごめんなさい！
今のところ OPL4のミュート機能は実装されていません。

近日中に 対応させていただきます。

**Comment by kuma4649** [comment]
実装完了しました。
お待たせしました。
楽しんで！
