### ISSUE TITLE
Output directory bug

### ISSUE THREAD

**Issue by katananja** [kuma4649/MDPlayer#37]
こんにちは!
久しぶりですね。

If you set a output folder like this and latter delete the folder:
![](https://s6.postimg.cc/emrg85ae9/mdplayer-bug.png)

It show this error:
![](https://s6.postimg.cc/6h9e9zefl/mdplayer-bug-02.png)

And it won't stop showing that message until it reach the end of the play list. Why not ask the user if he want to create it?

よろしくお願いいたします。😌

**Comment by kuma4649** [comment]
毎度どうも〜
こんにちは。

まだ詳しく見ていないので想像です;p
1 wav出力時に
  フォルダが無い
  すでにファイルが存在する
という場合には ユーザーに問い合わせを
して欲しいということですね？

2 再生時にエラーが発生すると
プレイリストの次の曲に進んでしまう。
運が悪いと残りの曲数分だけ何回もエラーが出てしまう。
エラーが出たら次の曲に進むのを
やめてほしいということですね？

**Comment by katananja** [comment]
Hello!
This one is hard.
* wav出力時に再生する前にフォルダが存在するかどうか確認してくれます
* フォルダがあればすずく。なければ新しいフォルダを作成するかどうかをユーザーに尋ねる

この状態がなければ、再生は停止しません。たとえば、プレイリストに100個のアイテムがある場合、MDPlayerはそのプレイリストの最後に到達するまで停止しません。コントロールの喪失。エラーメッセージが繰り返し何度も繰り返される。

それだけです。
よろしくお願いいたします。😌

**Comment by kuma4649** [comment]
承知しました。
はじめに、エラーがでたら次の再生をしないように修正します。
次にチェック処理を追加してみようと思います。

**Comment by kuma4649** [comment]
修正してみました。いかがでしょうか。

**Comment by katananja** [comment]
すごいはやい！
さすがですね。

お疲れ様でした。
ありがとうございました!!!
