### ISSUE TITLE
C140でのノート表示がVGMの表示とずれてる

### ISSUE THREAD

**Issue by knight-ryu12** [kuma4649/MDPlayer#38]

**Comment by kuma4649** [comment]
がーん。8KHzをo4cで表示するよう修正します。

**Comment by knight-ryu12** [comment]
o3cのほうがいいのでは？

2018年10月13日(土) 16:49 kuma <notifications@github.com>:

**Comment by knight-ryu12** [comment]
というか多分それでも8252Hzとかだったら修正しようがないんだよなこれ・・・

**Comment by kuma4649** [comment]
他が一応、8kHzをo4cでやってるのでそれにあわせようかと。あまりにもという場合は後から調整かな。

**Comment by kuma4649** [comment]
AYもずれてる

**Comment by kuma4649** [comment]
というわけで、修正完了しましたのでクローズします。
