### ISSUE TITLE
OPNでクリックするとウィンドウが開きません

### ISSUE THREAD

**Issue by katananja** [kuma4649/MDPlayer#40]
Hello @kuma4649, how are you doing?
これです！
![opn](https://user-images.githubusercontent.com/9029191/48492981-1f7ad880-e812-11e8-83c8-e65353da475c.png)
`PRI` OPN = **NG**
`SEC` OPN = OK

です！😉
ご不便おかけしてすみませんでした。

よろしくお願いします。😌

**Comment by kuma4649** [comment]
こんにちわ。

試してみましたが、開きますよ。。。？

**Comment by katananja** [comment]
こんにちわ。
おかしな…ウィンドウが画面の外にいるけど選択することはできません.

**Comment by kuma4649** [comment]
オプション＞Other＞ウィンドウ位置をリセット＞OK＞アプリの再起動
でいかがでしょうか？

**Comment by katananja** [comment]
それしても戻らないですね。
![mdplayer_screen](https://user-images.githubusercontent.com/9029191/48544846-a62fc400-e8ab-11e8-9f15-a902ee96000a.jpg)

**Comment by katananja** [comment]
画面外にロックされています。

**Comment by kuma4649** [comment]
Option＞Other＞設定フォルダを開く
Setting.xmlをTextエディタで開く

**Comment by kuma4649** [comment]
<PosYm2203>
      <Point>
        <X>0</X>
        <Y>0</Y>
      </Point>
      <Point>
        <X>0</X>
        <Y>0</Y>
      </Point>
    </PosYm2203>

**Comment by kuma4649** [comment]
![image](https://user-images.githubusercontent.com/7453752/48545073-6b0fae00-e908-11e8-9068-e8566411a0ce.png)

**Comment by kuma4649** [comment]
上記のようにxとyを0にしたら、保存。
これでいかがでしょうか。
表示位置が左上になるようにしています。

**Comment by katananja** [comment]
ダメですね。0に変更すると-32000に戻ります
```
    <PosYm2203>
      <Point>
        <X>-32000</X>
        <Y>-32000</Y>
      </Point>
      <Point>
        <X>0</X>
        <Y>0</Y>
      </Point>
    </PosYm2203>
```

**Comment by kuma4649** [comment]
アプリが動いていない状態で、書き換えても駄目でしょうか？

**Comment by katananja** [comment]
はいだめですね。多分それはWindowsのアップデートと関連していますかな？

**Comment by katananja** [comment]
Setting.xmlを削除しました。今わ大丈夫です。

**Comment by kuma4649** [comment]
いえ、多分バグです(T_T

**Comment by kuma4649** [comment]
症状がでていたとき、メインパネルは表示されていましたか？

**Comment by katananja** [comment]
はい。

**Comment by katananja** [comment]
これは設定のバックアップです。
[Setting.zip](https://github.com/kuma4649/MDPlayer/files/2584767/Setting.zip)

**Comment by kuma4649** [comment]
座標の情報が見つからないとき、MDPlayerはメインパネルの下にウィンドウを開こうとします。
なのでそこらへんに　バグがいるのかもしれない。。。

**Comment by kuma4649** [comment]
設定ファイルありがとうございます。
マルチモニター環境でしょうか？

**Comment by katananja** [comment]
いえ。普通の単一のモニターです。

**Comment by kuma4649** [comment]
うーむ。。。わからん^^;;;

**Comment by katananja** [comment]
ほんとだね。
よろしくお願いいたします。😌

**Comment by kuma4649** [comment]
対策しました。
これで様子をみてくださいませ。

**Comment by katananja** [comment]
まだですね。かわてないですね。

**Comment by katananja** [comment]
その設定を使用すると、問題は解決しません。
```
<X>-32000</X>
<Y>-32000</Y>
```

**Comment by katananja** [comment]
https://www.youtube.com/watch?v=8hhzlXLJeNQ

**Comment by kuma4649** [comment]
Chips(右から4つめ）>Primary>OPN
を2回選びなおしても駄目でしょうか？

**Comment by katananja** [comment]
そこから大丈夫です。ウィンドウをちゃんと見ます。
それを一度クリックするとすべてが動作します。

仮想デスクトップがオフになっている。

**Comment by kuma4649** [comment]
原因が不明のままですが、とりあえず逃げ道を作ったということでよろしくお願いします。orz

**Comment by katananja** [comment]
いえ、ありがとうございました。😌

**Comment by kuma4649** [comment]
原因、わかりました！
ウィンドウが最小化した状態で閉じると
正しい位置が取得できず(-32000,-32000)を取得してしまう。
これを修正しました。

**Comment by katananja** [comment]
すみません。
これかんけあるかないかわからないですね。
誤認を表示する。
https://youtu.be/qhJFmzzbsH0

**Comment by kuma4649** [comment]
使用していないチップ名のところがずっと点灯している現象ですよね？
これ、ずっと直せてないんです。原因がわからなくって。

**Comment by katananja** [comment]
あなたにこのようなトラブルを引き起こすことは大変申し訳ありません。
ほんとにありがとうございました。😌

**Comment by katananja** [comment]
楽しみにしています。
ありがとうございました。😌

**Comment by kuma4649** [comment]
この修正で、多分なおりました。
