### ISSUE TITLE
起動時に「オブジェクト参照がオブジェクトインスタンスに設定されていません。」

### ISSUE THREAD

**Issue by erio2018** [kuma4649/MDPlayer#43]
TAG135以降、起動時にException Messageが出て起動できません。
TAG134まで戻したら起動出たので確認したところ、プレイリストにvgmファイルが残っていて、それを「全ての曲を除去」したら確認ダイアログOK後に同じExceptionが出ました。（アプリは落ちませんでした）
再度「曲を追加」からzip圧縮されたvgzファイルを登録して「全ての曲を除去」してみましたがエラーは再現されませんでした。（演奏中/停止中共）
リストを空にしてアプリを終了し、再度TAG135以降のexeを起動しましたが再度同じエラーが出て起動できませんでした。

実行環境は　Win10Pro ver.1809 です。
よろしくお願いします。

**Comment by kuma4649** [comment]
こんにちは。ご報告ありがとうございます。
恐らく、新規で追加した実チップを操作するラッパのプログラムが
正しく動作していないものと思われます。

すぐに対策済みのプログラムをリリースしようと思いますので
お手数ですが、それで試していただいてよろしいでしょうか。

**Comment by kuma4649** [comment]
こんにちわ。使用していただきありがとうございます。

**Comment by kuma4649** [comment]
TAG138をリリースしました。よろしくお願いします！

**Comment by erio2018** [comment]
無事起動と問題なく演奏出来るのを確認しました！
素早い対応ありがとうございました。

**Comment by kuma4649** [comment]
よかった。。。
今後ともよろしくお願いいたします！

**Comment by erio2018** [comment]
mucomMD2vgmやmml2vgmも一緒に楽しく使わせてもらっています。
～2vgmシリーズはLinuxでもBuild出来るので重宝してます。
こちらこそよろしくお願いします！
