### ISSUE TITLE
[HES] Deflemaskで生成されたHESファイルが正常に再生できない。

### ISSUE THREAD

**Issue by knight-ryu12** [kuma4649/MDPlayer#49]
今のMDPlayerの初期化チェックがうまく機能していなく、Deflemaskで生成されたHESが再生できない。

**Comment by kuma4649** [comment]
Defleは全滅、
それ以外では問題なく演奏できるものもあり。

初期化処理の時点で演奏が開始されてしまう。
(恐らく初期化処理が演奏処理と分離していない)
