### ISSUE TITLE
OPNA vgzはシンバルを再生できません

### ISSUE THREAD

**Issue by hrzboy** [kuma4649/MDPlayer#51]
OPNA vgzはシンバルを再生できません
foobar2000でfoo_gep.dll v1.213を使用すると正常に動作します
https://vgmrips.net/[REDACTED]
リンク先が権利者を侵害する可能性がある為削除させて戴きましたご了承ください
トラック26のImpatienceりを見る

**Comment by knight-ryu12** [comment]
is symbal wav present on same directory as MDPlayer.exe?

シンバルのwavがMDPlayer.exeと同じディレクトリにないのでは？

**Comment by kuma4649** [comment]
ご報告ありがとうございます
先ずは
Chromaryuさんが仰る通りリズム音を鳴らすのに必要なwavファイルがプログラムと同じフォルダーに入っていない可能性があります。
ご確認くださいませ。
後　申し訳ありませんが
リンクの方はカットさせていただきました。

**Comment by hrzboy** [comment]
ご返事ありがとうございます。

リンクの変更に感謝します。

ご迷惑をおかけしました

また確認しました。

でも、wavファイルは確かにMDplayerと同じフォルダに存在します。

これはS 98録音からVgzの音楽に変換されます。

この音楽はリズム音源としてfm 2チャネルを使用している。

Cymbalもfm 2チャンネルにあるようです。

最初だけは聞き取れませんでした。後ろからずっとcymbalが聞こえます。

ファイルの変換時にファイルが不正になったと思います。

しかし、foobar2000のfoo_gepはこのファイルを正確に解析することができます。

だからこの質問があります



MDplayerは私に先輩の道を学ぶ上で多くの利益を得させて、ここでたいへん感謝します。

**Comment by kuma4649** [comment]
うーん。。。自分の環境では問題なさそうです。
foobar+foo_gep.dll(v1.214)でも確認しましたが違いは見られませんでした。

質問
1.現象はOPNAのリズム音源であるcymbalが最初の１音だけ鳴らないということですか？
2.現象は他のvgzファイルでも発生しますか？
3.S98ファイルをhrzboyさんが変換してvgzを作成したのでしょうか？
4.fm2チャンネルをリズム音源として使用しているということについて、
詳しく教えていただけますでしょうか。。
5.現象がでている前後2秒程度の動画を作っていただくことは可能でしょうか。

**Comment by hrzboy** [comment]
1.はい、OPNAのリズム音源の中で、最初の音だけはcymbalは鳴らないです。
2.他のvgzはまだ発見されていません。よく聞き取れません。
3.私はs 98を変えていません。作者は他の人がいます。
4.私はmml言語についてはよく分かりません。今はただリズムがfmチャネルを占有することを観測しています。時々adpcmチャネルを占有します。つまりサンプルです。各チャンネルを無効にしてテストしたものです。
5.はい、https://github.com/hrzboy/temp、
また、カートンはビデオ収録時にcpuの過負荷によるものです。

**Comment by kuma4649** [comment]
>5
ファイルがないみたいです
クリックすると404になります^^::

**Comment by hrzboy** [comment]
https://github.com/hrzboy/temp
すみません、リンクの一番後ろに番号があります。

**Comment by kuma4649** [comment]
動画ありがとうございます。
リズム音源再生用のファイルが読み込めていないと思われます。
https://www.google.com/search?q=2608_BD.WAV
検索結果から、wavファイルを入手し、
mdplayer.exeと同じフォルダーにそのwavファイルをコピー後
再度試していただけますでしょうか。

この曲の場合、FM音源のCh2でもリズムの音色を使用している為、
最初だけなっていないように見えていたのだと思います。

**Comment by hrzboy** [comment]
ご丁寧な回答ありがとうございます。

あなたの答えは完璧に解決されました。

過去のwavファイルは同じフォルダでサンプルレートフォーマットが問題ないように見えますが、まだ読み込めないので、再ダウンロードすればいいです。

**Comment by kuma4649** [comment]
おぉ！解決されたようですね？

>過去の〜
翻訳のせいか、意味がわからないので
原文のままお願い出来ますでしょうか🥺

**Comment by hrzboy** [comment]
Thank you very much for your patience,
things have worked perfectly fine now.

I finally figured out, it was the frequency of wav files I used were 48KHZ rather than 44.1KHZ. So to replace them with desired files by your suggestion makes it works like a charm. φ(゜▽゜*)♪

**Comment by kuma4649** [comment]
なるほど！了解しました。
MDPlayerで是非楽しいvgmライフをお過ごしください！

**Comment by hrzboy** [comment]
本当にありがとうございます！
楽しい生活を過ごしてください！
万事がうまくいった！
