### ISSUE TITLE
[Feature Req.] レジスタ表示の量

### ISSUE THREAD

**Issue by knight-ryu12** [kuma4649/MDPlayer#55]
チップによってはレジスタの量が少ないのでそこまでいっぱいレンダリングする必要はなさそう。

**Comment by kuma4649** [comment]
フォームのサイズ自動変更が必要そうですかねぇ

**Comment by kuma4649** [comment]
これもchipごとに少しずつ進めたほうがよさそう。
どのchipから対応してみます？

**Comment by knight-ryu12** [comment]
というよりチップごとに指定できたら良さそう。

**Comment by knight-ryu12** [comment]
たぶん、drawが呼ばれたときに一回だけフレームバッファを消去するだけで動きそうな予感もする。

**Comment by kuma4649** [comment]
全部のパラメータを毎回書き直すようなロジックだったので、
必要なパラメータだけ描きなおすようにしないと。
