### ISSUE TITLE
[Need Fix]  intとbyteのキャストコード

### ISSUE THREAD

**Issue by knight-ryu12** [kuma4649/MDPlayer#58]
PR #57 関連。

**Comment by kuma4649** [comment]
ぶっちゃけDCSGはアドレスを持たないので、常に１バイトのデータのみでやり取りが行われます。
では取得できる８つの数値はなぁに？
ということになるのですが、
これは、エミュレーションするプログラムが、自身が処理を行うのに都合がよいように
受け取ったデータを整理した結果の数値になります。
自身の都合に合わせた数値なので、int型が含まれていたりします。

(MDPlayerでは鍵盤表示が必要なので、自身でその8つの数値にあたるものを用意するべきなのですが、
めんどくさいので拝借していますｗ)

**Comment by kuma4649** [comment]
つまり、MDPlayerのDCSGのレジスタ表示は、1byteのデータを表示すれば良いので、
byte以外の表示方法を考える必要は無いということになります。

将来、byte以外の送信が必要なchipのレジスタ表示をすることになるときまで考えるのはやめときませんか。。。？
ｗ

**Comment by knight-ryu12** [comment]
まぁそうですよね〜。
ただ16bitのチップも存在するので、そこらへんはどうにかしないといけませんね。

**Comment by kuma4649** [comment]
それもやはり対応するときに考えることにしようと思います。
ということでとりあえずそれまでは本件を一旦クローズします。。。
