### ISSUE TITLE
GIMICでVGMのOPNA ADPCMが正しく再生されない

### ISSUE THREAD

**Issue by rerrahkr** [kuma4649/MDPlayer#62]
MDPlayer-c86ctl-GIMICでVGMファイルのOPNAのADPCMがうまく再生されないことがあるようです。
[adpcm.zip](https://github.com/kuma4649/MDPlayer/files/4586869/adpcm.zip)
zipには同じ曲のVGMとS98を纏めています。

2.vgmをエミュレーションで鳴らす場合は問題ありませんが、GIMICで鳴らすと酷いノイズが発生して上手くサンプルを再生できていないように思えます。GIMICのスタンドアロンモードで再生した場合は通常通り再生されました。S98は正しく再生されるので、VGMとS98の構造の違いからVGMのData block関係の処理に起因する問題かと考えています。
ただOPNAのADPCMを使用したVGMファイルを私はあまり持っておらず、他のプログラムで作成したVGMでも同様の事象が起こるかは確認できていません。
あまりはっきりした報告ができず申し訳ありません。

**Comment by kuma4649** [comment]
おはようございます。ご報告ありがとうございます。
まだ確認していないのですが、取り急ぎ。。。
OPNAのADPCMの特定のモードのサポートがvgmファイルでは不可能なものが確か存在したと思います。
それかもしれません。。。
(エミュレーションの場合は強引に変換をかけられるので問題なく再生できるのですが、
実チップの場合は難しかったような記憶があります。。。)

また後で調査させていただきます。

**Comment by kuma4649** [comment]
調べてみました。
やはりvgmではカバーできていない機能を使っていました。
仰る通りDataBlockの機能を使う為発生します。

rerrahkrさんはとても詳しい方のはずwなのでちょっと突っ込んで話しますと。。。
DataBlockで送信するデータが、
OPNAの(port:1 address=0x01 ADPCMのcontrol2のD1(bit1)が1の)
x8bitモードを使用したPCMデータの場合に発生します。

多くのデータはx1bitモードなのと、OPNAのエミュレーションプログラムがそのモードの違いを
吸収したコードになっているので、実チップ以外では現象は発生しません。
(無論、その挙動をわざわざ再現したエミュレーションであれば発生します)

DataBlockの内容を実チップに送信するにはそのx8bitモードを指定したうえで
送信する必要がありますが、そのモードを判定するための情報がDataBlockには用意されておりません。たぶん。
MDPlayerは現状x1bitモードで実チップにデータを送信します。
よって、PCMの音がおかしな状態になります。

**Comment by rerrahkr** [comment]
ご確認ありがとうございます。書き込みモードの違いには気づいておりませんでした。
上で添付しましたデータはBambooTrackerで作成したもので、トラッカーではx8bitモードを使用していました。VGMの仕様の問題ということで、プレーヤーでは対応が難しそうですね。VGMの作成の段階でx1bitかx8bitかを選択できるようこちらで対処しようと思います。もっとも、VGM自体にモード指定情報が追加されることが一番良いのですが。
迅速なご対応、ありがとうございました。

**Comment by kuma4649** [comment]
一応、今コードを追加してまして頂いたデータは鳴らせるようにしました。。。
パンを設定するときのデータを事前に調べるようにしていますw
でもこれでも完全ではないんですけどね。。。

**Comment by kuma4649** [comment]
個人的にはvgm形式の場合はx1bit固定にしていただけると嬉しいですw

...と思ってたのですが、割とちゃんと動いてくれているみたいなので
今はx8bitでもx1bitでもどんとこいという気持ちになってます。。。(^^;;

**Comment by kuma4649** [comment]
とりあえず対応完了しましたご確認ください！

**Comment by rerrahkr** [comment]
ede32e0 で正しく再生されることを確認しました。ご対応ありがとうございました！
