### ISSUE TITLE
OPNBの情報パネル上のPSG1~PSG3をクリックすると、FM7～FM9にそれぞれ表示が置き換わってしまう

### ISSUE THREAD

**Issue by sdhizumi** [kuma4649/MDPlayer#63]
使用バージョン: STBL039

OPNBの情報パネル上のPSG1, PSG2, PSG3をクリックしてミュート状態(赤文字化)した際に、FM7, FM8, FM9にそれぞれ表示が置き換わってしまい、ミュート解除した際にもFM7, FM8, FM9表示のままアンミュートされてPSG1, PSG2, PSG3に戻らなくなります。
恐らくミュート時に変化する対象の設定が、が元にしたチップの設定のままではないかと思います。

**Comment by kuma4649** [comment]
ありがとうございます！確認後修正します！

**Comment by kuma4649** [comment]
修正完了しました。ご確認お願いします。

**Comment by sdhizumi** [comment]
STBL044になってしまいましたが確認しました。ばっちりです！ありがとうございますー
