### ISSUE TITLE
[Future Req.] QSound鍵盤

### ISSUE THREAD

**Issue by knight-ryu12** [kuma4649/MDPlayer#64]

**Comment by katananja** [comment]
[libvgm](https://github.com/ValleyBell/libvgm) has a accurate QSound engine.

**Comment by knight-ryu12** [comment]
this is about its keyboard view so… yea

2020年6月3日(水) 3:34 katananja <notifications@github.com>:

**Comment by katananja** [comment]
ごめんね日本語よく使わないからちょっとわすれているみたいですね。😓
