### ISSUE TITLE
VGM/VGZ形式のVRC 7を使用した音楽ファイルは正常に再生できません。

### ISSUE THREAD

**Issue by denjhang** [kuma4649/MDPlayer#68]
例えばLagrange Pointは、半年前のバージョンでは、MDplayerはVRC 7をym 2413と識別し

**Comment by knight-ryu12** [comment]
Is it possible to make true VRC7 music in VGM?

**Comment by denjhang** [comment]
> 是否可以在VGM中制作真正的VRC7音乐？

https://（URLは削除させていただきました。ご了承ください...）

**Comment by kuma4649** [comment]
どうやら、クロック値の最上位ビットでOPLLかVRC7か判断できるようですね。
対応させていただきます。

**Comment by kuma4649** [comment]
対応しました。鍵盤表示がOPLLのままですがこれは気にしないでくださいorz

**Comment by kuma4649** [comment]
特に問題なさそうなので、本件は閉じさせていただきます。
