### ISSUE TITLE
add SAA1099 soundchip emulater

### ISSUE THREAD

**Issue by SocialSisterYi** [kuma4649/MDPlayer#72]

**Comment by kuma4649** [comment]
直ぐはできませんが、検討させていただきます！

**Comment by kuma4649** [comment]
追加しましたのでご確認ください。

**Comment by SocialSisterYi** [comment]
ALL OK,but have some bugs
soundchip channel not visible in mixer
pause music can't stop tone

**Comment by kuma4649** [comment]
mixerは今のところ未対応です。
また、ポーズは基本的に音は止まりません。
データ送信が止まるだけだからです。

**Comment by kuma4649** [comment]
mixer実装完了

**Comment by kuma4649** [comment]
＞また、ポーズは基本的に音は止まりません。
すみません、嘘でした。
「オプション」画面＞「Other」タブ＞「ポーズ時にレンダリングしない」にチェックをいれることで、
ポーズ時に音が止まるようになります。

**Comment by kuma4649** [comment]
一通り対応済みということで本件はクローズさせていただきます。
