### ISSUE TITLE
Abnormal PSGPCM (PPS) playback of YM2608-VGM/VGZ

### ISSUE THREAD

**Issue by denjhang** [kuma4649/MDPlayer#75]
When playing rusty's VGM, you can only hear very low PPS drums, and the sound is not complete.

**Comment by kuma4649** [comment]
確認します...

**Comment by kuma4649** [comment]
STBL084で対応してみました
いかがでしょうか？

**Comment by denjhang** [comment]
It feels OK. However, PSG channel 3 does not have a volume indication or keyboard display.
