### ISSUE TITLE
STBL084 のMDPlayer.exe実行でエラー

### ISSUE THREAD

**Issue by ymbon** [kuma4649/MDPlayer#77]
STBL084のbin.zipをダウンロードしてMDPlayer.exeを実行したところ下記エラーとなってしまいました。

Windows 10 64bit
バージョン 1909 (OS ビルド 18363.1110)

![2020-10-09](https://user-images.githubusercontent.com/71640260/95586215-551ab180-0a7b-11eb-9f26-a7a04dc84407.png)

**Comment by kuma4649** [comment]
こんにちは。
ゾーン識別子の件かもしれません。
以下のページを参照し、batファイルを実行後、再度ご確認くださいませ。

https://kuma4649.github.io/index.html

**Comment by ymbon** [comment]
ご提示の方法で解決しました。ありがとうございます。
dllの名前で検索をかけてしまったためFAQにたどり着かず自力解決できずお手数をおかけいたしました。

**Comment by kuma4649** [comment]
いえいえ、解決して良かったです！！
この件、何とかしたいのですが良い方法が無くて。。。
