### ISSUE TITLE
When playing mdx, changing tracks causes the volume to decrease exponentially

### ISSUE THREAD

**Issue by denjhang** [kuma4649/MDPlayer#79]
When I reduce the OPM volume (assumed to be - 8), changing tracks causes the OPM volume to decrease to - 16, and switching tracks again reduces the volume to - 32. If replaced enough, the volume of OPM will be reduced to - 192 (no sound).

**Comment by kuma4649** [comment]
現象確認しました。
調査します。

**Comment by kuma4649** [comment]
バグを修正しましたのでご確認くださいませ。

**Comment by kuma4649** [comment]
一旦クローズします。現象出るようでしたら再度オープンしてくださいませ。
