### ISSUE TITLE
Z-MUSIC(zms/zmd)に対応してほしい

### ISSUE THREAD

**Issue by sdhizumi** [kuma4649/MDPlayer#82]
Z-MUSICデータの再生環境がX68k実機、X68kエミュ、ZMDRIVEぐらいしか挙げられるものが無い現状で、
ZMDRIVEも安定性や使い勝手の面で難を感じる為、手軽に扱えるプレイヤーと言えるものが現在無い事に気付きまして、対応して頂けたらとても嬉しいなと感じました。

ただzmsはコンパイル→再生と処理が必要かと思われるので、事実上z-musicdotnetを開発する羽目になってしまう…？と書きながら気づきましたが、
口に出さないと需要は可視化されないとも思ったので、リクエストとして送らせていただきます。

**Comment by kuma4649** [comment]
こちらはFMPとは違いソースが公開されてますので、
作者さんに連絡とってみて大丈夫そうなら。。。
でも、今、moonDriverDotNETを作っている最中なのでその後になるかなと

**Comment by sdhizumi** [comment]
moonDriverですか！確かにこちらもあまりプレイヤーがありませんね…そちらも期待しています！
Z-MUSICはv2とv3とある分お手間掛けてしまいそうですが、確かにソース公開のドライバでしたね。
v2は西川さんのサイトからは現在見当たりませんが、
当時の配布アーカイブを保存・公開している場所は知っているので、必要であればお伝えできます。

**Comment by kuma4649** [comment]
ありがとうございます！よろしくお願いします。

**Comment by denjhang** [comment]
https://sites.google.com/site/yyagisite/zmcman/aboutz

**Comment by denjhang** [comment]
https://nfggames.com/X68000/Documentation/Zmusic/zmusic3.txt

**Comment by denjhang** [comment]
https://web.archive.org/web/20210118065645/http://z-z-z.jp/zmusic/index.html

**Comment by denjhang** [comment]
@sdhizumi I found it

**Comment by kuma4649** [comment]
本件、対応完了とさせていただきます。
