### ISSUE TITLE
FM musical instrument extraction format

### ISSUE THREAD

**Issue by denjhang** [kuma4649/MDPlayer#83]
In the keyboard display window, is it possible to add the function of extracting general FM musical instrument formats, such as vopm, TFI, Y12, DMP, WOPN, wopl and so on?
It will be convenient for people like me who like to compose music again.

**Comment by kuma4649** [comment]
![image](https://user-images.githubusercontent.com/7453752/103427270-3a338580-4c03-11eb-9dfc-73bd90caf9e4.png)

明けましておめでとうございます。
Y12、DMP、WOPNは無いです。仕様書がどこかにありますでしょうか。

**Comment by kuma4649** [comment]
DMPは見つけました。これは対応できそうです。

**Comment by kuma4649** [comment]
WOPNは仕様書いただくことができましたが、
見たところ、MDPlayerには向かないフォーマットでしたので代わりにOPNIフォーマットに対応させていただきます。

**Comment by denjhang** [comment]
Try this. Maybe OPLI format is suitable for OPL series VGM
https://github.com/Wohlstand/OPL3BankEditor/tree/master/Specifications

**Comment by denjhang** [comment]
For OPL, these two formats can also be considered :
SBI,INS

**Comment by kuma4649** [comment]
STBL096にてdmp/opniに対応しました

**Comment by kuma4649** [comment]
OPLIはできそうですが、SBI/INSとは？仕様がわからないと...

**Comment by denjhang** [comment]
http://www.shikadi.net/moddingwiki/IMF_Format
http://www.shikadi.net/moddingwiki/CMF_Format
http://www.shikadi.net/moddingwiki/SBI_Format
http://www.shikadi.net/moddingwiki/AdLib_Instrument_Bank_Format

**Comment by kuma4649** [comment]
ありがとうございます。一通り確認しました。
OPLの状況に詳しくないのですが、
一気にたくさん対応はするつもりはないです。
申し訳ないですが、今回はOPLIだけ追加させてください。

その他ご提示いただいたファイル対応は今後順々に様子を見ながら追加していこうと思います。

**Comment by denjhang** [comment]
With OPLI and OPNI, I'm very satisfied.

**Comment by kuma4649** [comment]
OPLI対応ですが、手間取っています。。。

**Comment by kuma4649** [comment]
STBL098にてOPLI対応しました。

**Comment by denjhang** [comment]
The sound of the exported opni instrument is abnormal and cannot be played back correctly in opn2 bank editor

**Comment by denjhang** [comment]
DMP is correctly identified and voiced

**Comment by denjhang** [comment]
Opli is correctly recognized and voiced, but when VGM uses 2x2op instruments, only two operators' instrument data can be extracted. If I want to reproduce the timbre on OPL3 bank editor, I need to extract it twice and merge instruments manually.

**Comment by denjhang** [comment]
The problem of opli seems to have a lot to do with OPL3 driver. The real 4op mode can extract the whole 4op instrument at one time without manual operation.

**Comment by kuma4649** [comment]
OPLIに問題がありそうだというのはわかりました。
しかし詳細があなたの文章から読み取れていません。ごめんなさい。

もう少し具体的に示していただけますでしょうか。。。

**Comment by denjhang** [comment]
[beat zero trimmed.zip](https://github.com/kuma4649/MDPlayer/files/5759702/beat.zero.trimmed.zip)

For example, there is an opna VGM file in the zip, but there is a problem in extracting opni musical instruments. It can't sound normally in the opn2 musical instrument editor.
Other ym2612 or ym2151 VGM can extract DMP and make sound normally in bamboo tracker. However, the ssg-eg parameter of the instrument extracted by VGM in the zip package seems to be unnecessary. After removing the ssg-eg, it can make a correct sound. If the ssg-eg is not removed, the sound of the instrument is very strange.

**Comment by denjhang** [comment]
For OPL3, there are not so many problems. The extraction of opli is completely correct, and it can make sound correctly in OPL3 instrument editor.
It's just that there are some small problems in the extraction of 2x2op and 4op instruments of OPL3.
Here are several working modes of OPL3, which I can't make clear.
There are two VGM / vgz files in the following zip package, which use 2x2op and 4op respectively.

[2x2op and 4op ymf262.zip](https://github.com/kuma4649/MDPlayer/files/5759705/2x2op.and.4op.ymf262.zip)

**Comment by kuma4649** [comment]
OPLIは問題なくてOPNIが問題なんですね？

**Comment by denjhang** [comment]
yes

**Comment by denjhang** [comment]
OPLI needs to be fixed

**Comment by kuma4649** [comment]
OPNIの現象と原因確認できました。修正します。

**Comment by kuma4649** [comment]
STBL099で対応しました。ご確認ください。

**Comment by denjhang** [comment]
ONIとDMP形式で抽出した楽器はちょっと問題があります。楽器のSSG-EGパラメータが正しくありません。抽出されたssg-egの値は15ですが、実際には0です。

**Comment by denjhang** [comment]
OPNIとDMP形式で抽出した楽器はちょっと問題があります。楽器のSSG-EGパラメータが正しくありません。抽出されたssg-egの値は15ですが、実際には0です。

**Comment by denjhang** [comment]
There is a little problem with the instruments extracted from opni and DMP formats. The ssg-eg parameters of the instruments are not correct. The extracted SSG eg value is 15, but actually it should be 0

**Comment by denjhang** [comment]
It seems that only when extracting DMP/OPNI from OPN2/OPN2C VGM, there is no problem with OPM VGM.

**Comment by denjhang** [comment]
I found that this OPN2C VGM has problems in extracting OPNI and DMP.

[kuma4649 : すみません、06.New.Year.zip　は削除させていただきました。]

**Comment by kuma4649** [comment]
うわ、2612の修正が抜けてました。ありがとうございます。

**Comment by denjhang** [comment]
A new problem is found. No matter what the actual situation is,OPNI's AL= 0

**Comment by kuma4649** [comment]
??

**Comment by denjhang** [comment]
To illustrate, I'll show you two screenshots, paying attention to the circled part. I extracted the opni format instruments of FM1 channel, and found that the al value was significantly different.
![截图0103222734](https://user-images.githubusercontent.com/61811583/103481102-8a813200-4e13-11eb-8a1f-130258b2c125.jpeg)
![截图0103222931](https://user-images.githubusercontent.com/61811583/103481104-8ce38c00-4e13-11eb-9a5d-75151cfc4929.jpeg)

**Comment by denjhang** [comment]
![截图0103222734](https://user-images.githubusercontent.com/61811583/103481124-a84e9700-4e13-11eb-8a3a-ca97bd1fca72.jpeg)

**Comment by denjhang** [comment]
![截图0103222734](https://user-images.githubusercontent.com/61811583/103481160-febbd580-4e13-11eb-8a8f-0a1acd601b87.jpeg)

**Comment by denjhang** [comment]
![截图0103222931](https://user-images.githubusercontent.com/61811583/103481204-58bc9b00-4e14-11eb-8223-b191e1a17455.jpeg)

**Comment by kuma4649** [comment]
おぉ！ありがとうございます。
確認します。

**Comment by kuma4649** [comment]
STBL102で対応しました。ご確認ください！

**Comment by kuma4649** [comment]
閉じます
