### ISSUE TITLE
When importing multiple VGM files to the player list, the speed is very slow

### ISSUE THREAD

**Issue by denjhang** [kuma4649/MDPlayer#84]
Usually I is too laggy to drag multiple mdplayer into VGM, and I find it very cate, the software is going to crash (no response), and every file is loaded with one second.

**Comment by kuma4649** [comment]
一曲ずつ中身を解析してから次を読み込むからなのですが、
プレイリストを予め作っておくことで次からそれを読み込むと良いと思います。

ファイルのリストだけ読み込んで、
後から余裕のある時に随時情報を解析する方法もありますが、
直ぐに改修できるような内容ではありません。

**Comment by kuma4649** [comment]
D&D時の読み込み速度を改善しました

**Comment by kuma4649** [comment]
こちら、いかがでしょうか？

**Comment by denjhang** [comment]
Now it's better, but after I add ASIO to my computer, the whole software runs much faster

**Comment by denjhang** [comment]
It is suggested to add in the home page and readme: installing ASIO can greatly improve the efficiency of the software.

**Comment by kuma4649** [comment]
playListの動作は問題なさそう。。。ですね？
クローズします。
