### ISSUE TITLE
When playing some opna / OPL3 VGM, the software will report an error

### ISSUE THREAD

**Issue by denjhang** [kuma4649/MDPlayer#85]
When I play some several megabyte opna VGM (using ppz to output SSG channel as PCM), sometimes the system will pop up and report an error, such as exceeding the array limit.
When playing OPL3 VGM, when I click the FM instrument data in the piano keyboard interface, a similar system pop-up error will appear.

**Comment by kuma4649** [comment]
現象の起きるサンプルファイルを送っていただいてもよろしいでしょうか。
詳細を知りたいので...

**Comment by denjhang** [comment]
![Uploading 截图0101103328.jpeg…]()

**Comment by denjhang** [comment]
![截图0101103328](https://user-images.githubusercontent.com/61811583/103432684-6a3c5200-4c1e-11eb-879f-856d8e892c2a.jpeg)

**Comment by denjhang** [comment]
[OPL3 VGMs.zip](https://github.com/kuma4649/MDPlayer/files/5758591/OPL3.VGMs.zip)

**Comment by denjhang** [comment]
![截图0101104926](https://user-images.githubusercontent.com/61811583/103432708-0e25fd80-4c1f-11eb-85b9-76372f2a286a.jpeg)

**Comment by denjhang** [comment]
![截图未命名0101105333](https://user-images.githubusercontent.com/61811583/103432744-e1beb100-4c1f-11eb-87d8-0843d72b5076.jpeg)

**Comment by denjhang** [comment]
[meet u (22khz)OPNA PPZ.zip](https://github.com/kuma4649/MDPlayer/files/5758599/meet.u.22khz.OPNA.PPZ.zip)

**Comment by kuma4649** [comment]
お陰様で、原因判明しました。ありがとうございます！
STBL097にて対応しました。ご確認ください。

**Comment by kuma4649** [comment]
閉じます。
