### ISSUE TITLE
The software cannot be opened after updating the driver of the graphics card

### ISSUE THREAD

**Issue by denjhang** [kuma4649/MDPlayer#86]
Some computers cannot open mdplayer, even if they are sure that the required runtime is installed.
As shown in the jpeg below
![mdplayer 打不开](https://user-images.githubusercontent.com/61811583/103414980-2b28e500-4bbb-11eb-81ea-8f46d6b3c536.jpeg)

**Comment by denjhang** [comment]
![mdplayer 打不开](https://user-images.githubusercontent.com/61811583/103415012-53184880-4bbb-11eb-85d1-a53908ef443b.jpeg)

**Comment by denjhang** [comment]
I tried to upload the picture, but it didn't seem to work.

**Comment by denjhang** [comment]
工ラ
不明工ラ一凳生ま。
 Exception Message:
未能加载文件或程序集“netstandard, Version=2.0.0.0
 Cultureneutral, PublicKeyToken=cc7b3ffcd2ddd51或它的某一个依赖项。系统找不到指定的文件。

**Comment by denjhang** [comment]
Workers
An unidentified worker is born on a bench.
Exception Message:
Failed to load file or assembly 'netstandard, version = 2.0.0.0'
Culture neutral, publickeytoken = cc7b3ffccd2ddd51 or one of its dependencies. The system cannot find the specified file.

**Comment by kuma4649** [comment]
エラーのメッセージから想像すると、DotNET standard をインストールする必要があるようですね...
試していただいてよろしいでしょうか。

**Comment by kuma4649** [comment]
PMDDotNETなどがDotNETstandard2を使用しているからのようです。
申し訳ないのですが仕様になります。。。
