### ISSUE TITLE
When the Bluetooth headset is disconnected, a pop-up error will appear

### ISSUE THREAD

**Issue by denjhang** [kuma4649/MDPlayer#87]
Play music through the Bluetooth headset. When the Bluetooth headset is suddenly disconnected, pop-up windows such as "beyond the array limit" will appear.

**Comment by kuma4649** [comment]
ハードウェア持ってないから試しようがないです。。。w

**Comment by denjhang** [comment]
See this .
![截图0103225817](https://user-images.githubusercontent.com/61811583/103481652-590a6580-4e17-11eb-8af4-492add092e83.jpeg)

**Comment by kuma4649** [comment]
もしこのエラーを補足出来たとして、専用のエラーメッセージを出すにしても、
ユーザーが行う対処は同じになると思いますよ...
すなわち、アプリを一旦終了させて、環境を整えてから起動しなおすことになります。。。

何故かと言われれば、
画面の様なエラーの状況で頑張って動作し続けるのは、
不安定な動作状態を続けてしまう可能性が高いと私は思うからです。

**Comment by kuma4649** [comment]
閉じます
