### ISSUE TITLE
Some FM instruments have extra noise when playing OPN2 VGM.

### ISSUE THREAD

**Issue by denjhang** [kuma4649/MDPlayer#88]
Is the VGM player core too old? I encountered this problem in the VGM player about 9 years ago, and then it was fixed.
This is a reference to the VGM file, with different VGM player contrast to know.
In 0 to 6 seconds of the tune, the instrument in FM2 channel is abnormal. I can confirm that.

[kuma4649:申し訳ないです、03 - Witch's Theme.zipは削除させていただきました。]

**Comment by kuma4649** [comment]
現象確認しました。
修正はMDSoundのほうで行います。
MDSoundのOPN2はGensのコードを使用しています。
GensのOPN2はSSG-EGのエミュレーションが完全ではないようです。
mameのOPN2を移植しようと思います。
時間がかかるかもしれません。
とりあえず、Nuked-OPN2を選択すると現象は改善するようです。

**Comment by kuma4649** [comment]
mame版OPN2を追加しましたのでご確認ください。

**Comment by kuma4649** [comment]
閉じます
