### ISSUE TITLE
When playing VGM music, click stop button, the music can't stop

### ISSUE THREAD

**Issue by denjhang** [kuma4649/MDPlayer#89]
After clicking the stop button, the concert will stop, but after a few seconds, it will appear the same situation as the music pause, that is, to play the note at the moment of stopping, and it will continue.

**Comment by kuma4649** [comment]
停止状態でも、鍵盤が初期状態に戻らないということでしょうか？
もしそうであれば、仕様です。

**Comment by denjhang** [comment]
When I press the stop button, the piano keyboard will remain in the instant state when it stops. After a few seconds, there is a certain probability that the music will play automatically.
Sometimes it happens, sometimes it doesn't.

**Comment by kuma4649** [comment]
うーむ...どのくらいの頻度でしょう。
此方では発生しないので対処できないのです...

**Comment by denjhang** [comment]
I find:When I play a VGM,
1. I open the OPN2 keyboard window,
2. Then click the stop button,
3. After closing the OPN2 keyboard window,
4. The sound will come out like a pause,
It's strange.

**Comment by kuma4649** [comment]
こちらでは発生しないです。。。
動画とかないでしょうか。。。？

**Comment by denjhang** [comment]
https://user-images.githubusercontent.com/61811583/105714585-7e424d80-5f57-11eb-97ae-dd6a2e1c2497.mp4

**Comment by denjhang** [comment]
In the video above, the symptom appeared in 25 seconds

**Comment by denjhang** [comment]
https://user-images.githubusercontent.com/61811583/105715126-2c4df780-5f58-11eb-8918-1af2ed27da9b.mp4

In the video above, the symptom appeared in 38 seconds

**Comment by kuma4649** [comment]
うーむ
何回か繰り返すと発症する感じ？

**Comment by denjhang** [comment]
It won't happen at the beginning.

**Comment by denjhang** [comment]
I repeat this operation a few times, there is a probability that it will happen

**Comment by kuma4649** [comment]
素早く操作する感じでしょうか

つまり　ゆっくり操作すると発症しない？

**Comment by knight-ryu12** [comment]
Which sound device are you using? is this actual hardware running? or is it emulator running?
What kind of buffer setting are you using?

**Comment by denjhang** [comment]
@knight-ryu12  Using waveout, emulator,It's all the default settings

**Comment by kuma4649** [comment]
STBL114で試してみてください

**Comment by kuma4649** [comment]
なおりましたか？

**Comment by kuma4649** [comment]
？

**Comment by denjhang** [comment]
There is no problem at the moment

**Comment by kuma4649** [comment]
ではクローズしますね
