### ISSUE TITLE
[Request] NSFのFDSでの$8000-$DFFFの書き込み無効化

### ISSUE THREAD

**Issue by knight-ryu12** [kuma4649/MDPlayer#9]
NSFPlayなどでできるオプション
(実機では再生できないNSF(FDS+VRC6+VRC7)などを再生できるようにする)

**Comment by kuma4649** [comment]
あまりよく知らないのですが、FDSで該当アドレスがカキコできるとVRC6/7の邪魔をしてしまう(アドレスが重複？）ということなのでしょうか。

**Comment by knight-ryu12** [comment]
そうですね。

2017/09/21 午後10:37 "kuma" <notifications@github.com>:

**Comment by kuma4649** [comment]
NSFPlayerの実装を解析してみます。

**Comment by kuma4649** [comment]
実装完了。
