### ISSUE TITLE
SN76489（DCSG）DAC Mode VGM

### ISSUE THREAD

**Issue by denjhang** [kuma4649/MDPlayer#90]
MDPlayer can't play it.

**Comment by denjhang** [comment]
kuma4649:申し訳ないですがリンクは削除させていただきました。
[SN76489（DCSG）DAC Mode.zip]

**Comment by kuma4649** [comment]
DCSGはDACに対応してません、多分。
また提示されたvgmファイルはv1.00であり、MDPlayerではサポートしません。
1.01以上です

**Comment by kuma4649** [comment]
STBL103でバージョンが古くても通過するようにしてみました。

**Comment by denjhang** [comment]
At present, there is no problem. It can play normally. DCSG is sure that DAC mode exists. Recently, I was studying the DAC mode of DCSG and used an old program more than ten years ago to convert wav to VGM (that's why the VGM version in the compressed package is very old). And after the actual chip test (esp32 driving sn76489), this is completely feasible.
I also tried to use dcsg to generate pulse wave, triangle wave, sawtooth wave and sine wave.It's just that these strange notes don't normally appear on the piano keyboard. They always flash at the highest note.
DCSG is an interesting chip :P

**Comment by kuma4649** [comment]
問題が解決できてよかったです。。。
OPNのSSGも音量を変化させることによってPCM再生させることができていたので、
それと同じ方法なんでしょうかねぇ。

ちなみに今、mameのOPN2移植が難航しています...>完了！
