### ISSUE TITLE
DMG piano keyboard display cannot close a channel

### ISSUE THREAD

**Issue by denjhang** [kuma4649/MDPlayer#91]
I click on a channel with my mouse and nothing changes

**Comment by denjhang** [comment]
To close a channel is to mask it.

**Comment by kuma4649** [comment]
DMGの鍵盤はマスク機能をサポートしてません。
他のサポートしていない鍵盤も沢山ありんす。。。
ごめんなさい。

**Comment by kuma4649** [comment]
DMGのmute機能を実装しました
