### ISSUE TITLE
There is a problem with RF5C keyboard mask

### ISSUE THREAD

**Issue by denjhang** [kuma4649/MDPlayer#92]
After masking, the sound will not disappear

**Comment by kuma4649** [comment]
バグだと思うのですがイマイチ原因がはっきりしなくて直ぐには直せそうにないです...

**Comment by kuma4649** [comment]
直接の原因はわからなかったので、ミュートの方法を変えてみました。

**Comment by denjhang** [comment]
Now it's OK
