### ISSUE TITLE
Piano keyboard display shortcut button adjustment

### ISSUE THREAD

**Issue by denjhang** [kuma4649/MDPlayer#96]
![截图未命名210128193938](https://user-images.githubusercontent.com/61811583/106133829-bab4ba00-61a0-11eb-8012-6f5e07c0dc1e.jpeg)
As shown in the red circle in the figure, can I customize and adjust the keyboard types displayed? It's better to arrange them automatically according to the frequency of my use, and hide the ones that are not commonly used.

**Comment by kuma4649** [comment]
自動で鍵盤表示するから、ここのショートカット、あまり使わないのよね。。。
機能削ろうかなとちょっと思ってます。
どう思います？

**Comment by denjhang** [comment]
ok

**Comment by kuma4649** [comment]
そんなわけで、機能削ってしまいましたー。
閉じますね。
