### ISSUE TITLE
Auto pop up piano keyboard window

### ISSUE THREAD

**Issue by denjhang** [kuma4649/MDPlayer#97]
Adding such an option will automatically pop up the corresponding piano keyboard when playing a certain chip, which may be more convenient

**Comment by kuma4649** [comment]
![image](https://user-images.githubusercontent.com/7453752/106141400-5bac7080-61b3-11eb-89a0-3f9c4b966483.png)

ありますよー

**Comment by denjhang** [comment]
ok

**Comment by kuma4649** [comment]
とじますね
