### ISSUE TITLE
There is something wrong with the noise channel and 3ch of T6W28(Neo Geo Pocket)

### ISSUE THREAD

**Issue by denjhang** [kuma4649/MDPlayer#98]
VGM format

**Comment by kuma4649** [comment]
この内容からは今一つ内容がわからないですね。。。(^^;;;;

**Comment by kuma4649** [comment]
STBL117で、NGP対応してみました。いかがでしょうか。

**Comment by denjhang** [comment]
There is improvement, but SFX plays the wrong tone

**Comment by denjhang** [comment]
[01b Title Screen (with SFX).zip](https://github.com/kuma4649/MDPlayer/files/5897452/01b.Title.Screen.with.SFX.zip)

**Comment by kuma4649** [comment]
すみません、ファイルへのリンクは削除しましたー。

**Comment by kuma4649** [comment]
多分、これは再生周波数の問題かなと思うので「仕様」ということでお願いします。

**Comment by denjhang** [comment]
It's much better now, but there's something wrong with the treble of channel 4, such as this file.

**Comment by denjhang** [comment]
02 Options Screen.zip

kuma4649 : Delete File ...orz

**Comment by kuma4649** [comment]
高音がおかしいってことでしょうかねぇ.
バグかなぁ...もう一度みなおしてみます

**Comment by kuma4649** [comment]
調査した結果、SN76489のエミュレーションプログラムが違うからみたいです。
よって仕様です。
vgmplayはデフォルトでmameを使用してますが、maximに変えると同じ状態になると思います

mameにしたい...？

**Comment by kuma4649** [comment]
vgmplayはデフォルトでmameを使用してますが、maximに変えると同じ状態になると思います

**Comment by kuma4649** [comment]
これどうしましょうか？

**Comment by denjhang** [comment]
Try using MAME emulation core

**Comment by kuma4649** [comment]
STBL129 にて実装
![image](https://user-images.githubusercontent.com/7453752/107118249-2266b580-68c3-11eb-96d6-dba0fb201b82.png)
SN76489でmame版を2つ選んでください
2つ選ばないとNGPは正常になりません。

**Comment by kuma4649** [comment]
これ、いかがでしょうか？

**Comment by denjhang** [comment]
ok

**Comment by kuma4649** [comment]
ありがとうございます。とじますね
