### ISSUE TITLE
T6W28(Neo Geo Pocket) Pan display error

### ISSUE THREAD

**Issue by denjhang** [kuma4649/MDPlayer#99]
Always show as center

**Comment by kuma4649** [comment]
これはバグですね、心当たりがあるのでMDSoundのソースを見ながら調整してみます。

**Comment by kuma4649** [comment]
バグとかではなく、NGP向けに対応をいれないと駄目そうです。。。
DCSG2つ使って処理してしまうvgmの都合もあって、どのような対応が妥当か考える必要がありそう。

**Comment by kuma4649** [comment]
対応しました。

**Comment by denjhang** [comment]
OK at the moment, but there is a little problem.

**Comment by kuma4649** [comment]
こっちは閉じますね
